fixup onResetStore docs, convert to hooks
apollographql/apollo-client pull request #10047
Opened 2022-08-28 18:21 UTC by henryqdineen

Found a couple issues with the existing `onResetStore` docs
- `componentDidUnmount` doesn't exists (`componentWillUnmount` does though)
- `this.state.reset` is always `false` and wasn't correctly being set
- It references the old `@apollo/react-hoc` module from `react-apollo`, which has not been mentioned if reading the docs in order

For this PR I also migrated to hooks since the HOCs are deprecate. Let me know if you would prefer it to be fixed up but still use the HOC. Thanks!

2022-09-01 18:47 UTC, jpvajda reviewed
Thanks for this contribution! I noticed up the page (on line 49) we have another code sample which does use `withApollo`

```js

export default withApollo(graphql(PROFILE_QUERY, {
  props: ({ data: { loading, currentUser }, ownProps: { client }}) => ({
    loading,
    currentUser,
    resetOnLogout: async () => client.resetStore(),
  }),
})(Profile));
```

We can probably update that as well in this PR, did you want to make that change?

2022-09-01 20:17 UTC, jpvajda commented
@henryqdineen good question! I'll defer to some of the team on that. cc @benjamn  @hwillson  @MrDoomBringer   @alessbell

2022-09-12 18:53 UTC, MrDoomBringer requested changes
Thanks for the PR @henryqdineen, I have some small suggestions but other than that this looks great!

2022-09-12 18:53 UTC, MrDoomBringer commented on docs/source/caching/advanced-topics.mdx
> +    });
```suggestion
  const [reset, setReset] = useState(0);
  const client = useApolloClient();

  useEffect(() => {
    const unsubscribe = client.onResetStore(() => 
      new Promise(()=>setReset(reset + 1))
    );
```

2022-09-12 18:53 UTC, MrDoomBringer commented on docs/source/caching/advanced-topics.mdx
> +    });
`client.onResetStore` expects a function returning a `Promise`, so I believe this won't compile. It feels a little clunky to me, but wrapping `setReset` in an anonymous function returned by a Promise works.

Also IMO it's slightly better to use incrementing values for your setReset hook, so `onResetStore()` reloads the UI every time it's called, rather than just once.

2022-09-12 18:53 UTC, MrDoomBringer commented on docs/source/caching/advanced-topics.mdx
> +    });
Here's a link to a quick codesandbox I spun up that tests all this: https://codesandbox.io/s/onresetstore-example-pvi8i1?file=/src/index.jsx

2022-09-12 18:58 UTC, MrDoomBringer commented
>Would something like this work? I can update this branch.

@henryqdineen Not a blocking request, but it might be better to use something like this, purely because it might be a little easier for people to drop-in to existing code.
```js
function Profile() {
    const { data, loading, client } = useQuery(PROFILE_QUERY);
    if (loading) return <p>Loading</p>;
    return (
      <Fragment>
        <p>Current user: {data?.currentUser}</p>
        <button onClick={async ()=>client.resetStore()}>
            Log out
        </button>
      </Fragment>
    );
}
```

2022-09-19 17:24 UTC, MrDoomBringer commented
LGTM! @henryqdineen I went ahead and committed an update to that first example for `client.resetStore`, as it looked like you were alright with the suggestion. Thanks for the other changes.

All the best,
Emmanuel, Intern :-)

2022-09-19 17:24 UTC, merged