Fix typos
apollographql/apollo-client pull request #10045
Opened 2022-08-27 18:27 UTC by CompuWiser

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2022-08-27 18:28 UTC, apollo-cla commented
@CompuWiser: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2022-08-27 19:38 UTC, apollo-cla commented
@CompuWiser: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2022-08-30 04:30 UTC, MrDoomBringer requested changes

2022-08-30 04:30 UTC, MrDoomBringer commented on docs/source/api/react/hooks.mdx
> +  (options?: LazyQueryHookOptions<TVariables>) => Promise<LazyQueryResult<TData, TVariables>>,
```suggestion
  (options?: LazyQueryHookOptions<TData, TVariables>) => Promise<LazyQueryResult<TData, TVariables>>,
```
I think we also want TData in this, but otherwise LGTM!

2022-09-01 14:26 UTC, jpvajda commented
@MrDoomBringer I committed your suggestion, this should be good to go now if you want to approve this change.  Thanks for the contribution @CompuWiser! 🙏

2022-09-02 01:30 UTC, MrDoomBringer approved these changes
LGTM

2022-09-02 13:45 UTC, MrDoomBringer commented
Thanks for the PR @CompuWiser, and welcome to the repository!

Best,
Emmanuel, Intern :-)

2022-09-02 13:45 UTC, merged