chore(docs): add useFragment_experimental documentation
apollographql/apollo-client pull request #10099
Opened 2022-09-12 18:08 UTC by alessbell

Adds `useFragment_experimental` documentation.

### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

2022-09-12 18:32 UTC, alessbell commented on docs/source/data/defer.mdx
> +> ⚠️ **The `@defer` directive is currently at the [preview stage](https://www.apollographql.com/docs/resources/release-stages/#preview) in Apollo Client, and is available by installing `@apollo/clien
Two small unrelated nits in this file (`Apollo Client Web` vs `Apollo Web Client` and a missing period)

2022-09-12 18:32 UTC, alessbell commented on docs/source/api/react/hooks-experimental.mdx
> +<UseFragmentOptions />
Followed a convention I noticed where options are documented in their own `.mdx` file

2022-09-12 19:57 UTC, StephenBarlow approved these changes
Approved on the docs side with suggestions!

2022-09-12 19:57 UTC, StephenBarlow commented on docs/shared/useFragment-options.mdx
> +<tr>
This is awesome! To match the exact style of other "field tables":

* Add `class="required"` to each `tr` for a required field (this applies a subtle shading to the row)
* You can omit "**Optional**" for optional parameters

2022-09-12 19:57 UTC, StephenBarlow commented on docs/shared/useFragment-options.mdx
> +**Optional.** The name of the fragment defined in the `fragment` document to use in the call.
```suggestion
The name of the fragment defined in the [`fragment`](#fragment) document to use in the call.
```

2022-09-12 19:57 UTC, StephenBarlow commented on docs/shared/useFragment-options.mdx
> +**Optional.** The name of the fragment defined in the `fragment` document to use in the call.
This ability for cross-parameter linking is a big part of why we use this absurd syntax for field tables 😄

2022-09-12 19:57 UTC, StephenBarlow commented on docs/shared/useFragment-options.mdx
> +**Optional.** The name of the fragment defined in the `fragment` document to use in the call.
Hm I wonder if the anchor will work for a shared MDX snippet... I guess we'll see!

2022-09-12 19:57 UTC, StephenBarlow commented on docs/shared/useFragment-options.mdx
> +You don't need to provide this value if the `fragment` document includes only one fragment.
```suggestion
**Required** if the `fragment` document includes more than one fragment, optional otherwise.
```

2022-09-12 19:57 UTC, StephenBarlow commented on docs/shared/useFragment-options.mdx
> +You don't need to provide this value if the `fragment` document includes only one fragment.
One of these weird parameters that's required only under certain circumstances 😄 I think I usually go for a middle ground like this where the table row isn't shaded, but we still emphasize the case where the parameter _is_ necessary ahead of when it's optional.

2022-09-12 19:57 UTC, StephenBarlow commented on docs/source/api/react/hooks-experimental.mdx
> +> ⚠️ **The `useFragment_experimental` hook is currently at the [preview stage](https://www.apollographql.com/docs/resources/release-stages/#preview) in Apollo Client and is available by installing `@
```suggestion
> ⚠️ **The `useFragment_experimental` hook is currently at the [preview stage](/resources/release-stages/#preview) in Apollo Client and is available by installing `@apollo/client@beta`.** If you have feedback on it, please let us know via [GitHub issues](https://github.com/apollographql/apollo-client/issues/new?assignees=&labels=&template=bug.md).
```

2022-09-12 19:57 UTC, StephenBarlow commented on docs/source/api/react/hooks-experimental.mdx
> +Beginning with version `3.7.0`, Apollo Client Web has preview support for the `useFragment_experimental` hook which which represents a lightweight live binding into the `ApolloCache`, returning an al
```suggestion
Beginning with version `3.7.0`, Apollo Client Web has preview support for the `useFragment_experimental` hook, which which represents a lightweight live binding into the Apollo Client Cache. This hook returns an always-up-to-date view of whatever data the cache currently contains for a given fragment. `useFragment_experimental` never triggers network requests of its own.
```

2022-09-12 19:57 UTC, StephenBarlow commented on docs/source/api/react/hooks-experimental.mdx
> +`useFragment_experimental` allows Apollo Client to broadcast very specific fragment results to individual components, though it is worth noting the `useQuery` hook remains the sole hook responsible f
```suggestion
`useFragment_experimental` enables Apollo Client to broadcast very specific fragment results to individual components. Note that the `useQuery` hook remains the sole hook responsible for querying and populating data in the cache ([see the API reference](./hooks#usequery)). As a result, the component reading the fragment data via `useFragment_experimental` is still subscribed to all changes in the query data, instead of only changes to the fragment's data.
```

2022-09-12 19:57 UTC, StephenBarlow commented on docs/source/api/react/hooks-experimental.mdx
> +We can first use the `useQuery` hook to retrieve a list of items with `id`s.
````suggestion
```

We can first use the `useQuery` hook to retrieve a list of items with `id`s:
````

2022-09-12 19:57 UTC, StephenBarlow commented on docs/source/api/react/hooks-experimental.mdx
> +We can then use `useFragment_experimental` from within the `<Item>` component to create a live binding for each item by providing the `fragment` document, `fragmentName` and object reference via `fro
````suggestion
```

We can then use `useFragment_experimental` from within the `<Item>` component to create a live binding for each item by providing the `fragment` document, `fragmentName`, and object reference via `from`:
````

2022-09-13 00:04 UTC, jpvajda commented
@StephenBarlow thanks for all the great bits of feedback. 🙏  I like this a lot, but I'm curious if we could add a clear use case or example as I find it nice when we say things like:

Let's say you want to do  X with Y... Well here is how you can with this new thing we are releasing... 

@alessbell

2022-09-13 00:13 UTC, StephenBarlow commented
@jpvajda That addition might make the most sense as a separate section (marked "experimental") in this doc: https://www.apollographql.com/docs/react/caching/cache-interaction

The hook is always for reading and reacting to changes in cached data, correct?

2022-09-13 01:21 UTC, StephenBarlow commented on docs/source/api/react/hooks-experimental.mdx
> +> ⚠️ **The `useFragment_experimental` hook is currently at the [preview stage](https://www.apollographql.com/docs/resources/release-stages/#preview) in Apollo Client and is available by installing `@
Totally, absolute URLs definitely work! I _think_ there's an issue with our cross-docset link validator catching broken links if they're absolute though. I'm going to confirm tomorrow to make sure I'm not recommending things due to outdated information 😬 

In any case, definitely not a blocker for this link to use _either_ format!

2022-09-13 01:32 UTC, alessbell commented on docs/source/api/react/hooks-experimental.mdx
> +> ⚠️ **The `useFragment_experimental` hook is currently at the [preview stage](https://www.apollographql.com/docs/resources/release-stages/#preview) in Apollo Client and is available by installing `@
Interesting, thanks for the context! Will also take a look tomorrow :)

2022-09-13 01:38 UTC, alessbell commented
Thanks for the review, @StephenBarlow! I like the idea of adding a section to the [cache-interaction](https://www.apollographql.com/docs/react/caching/cache-interaction) page - I should be able to wrap this up tomorrow 😄

2022-09-13 01:41 UTC, alessbell commented on docs/shared/useFragment-options.mdx
> +**Optional.** The name of the fragment defined in the `fragment` document to use in the call.
Looks like it does 😁🎉

2022-09-13 15:04 UTC, jpvajda approved these changes

2022-09-13 15:59 UTC, benjamn requested changes
Details 😈

2022-09-13 15:59 UTC, benjamn commented on docs/source/api/react/hooks-experimental.mdx
> +`useFragment_experimental` enables Apollo Client to broadcast very specific fragment results to individual components. Note that the `useQuery` hook remains the sole hook responsible for querying and
```suggestion
`useFragment_experimental` enables Apollo Client to broadcast very specific fragment results to individual components. Note that the `useQuery` hook remains the primary hook responsible for querying and populating data in the cache ([see the API reference](./hooks#usequery)). As a result, the component reading the fragment data via `useFragment_experimental` is still subscribed to all changes in the query data, but receives updates only when the fragment's data changes.
```
rewording for accuracy

2022-09-13 15:59 UTC, benjamn commented on docs/shared/useFragment-options.mdx
> +**Required.** The cached object (or object reference) for the fragment being retrieved.
```suggestion
**Required.** An object containing a `__typename` and primary key fields (such as `id`) identifying the entity object from which the fragment will be retrieved, or a `{ __ref: "..." }` reference, or a `string` ID (uncommon)
```
Need to be a little more specific than "the cached object"

2022-09-13 15:59 UTC, benjamn commented on docs/shared/useFragment-result.mdx
> +An object or string containing an error message or path to cached items with corresponding error messages.
```suggestion
An object or string containing an error message or path to cached items with corresponding error messages.
```
A tree of all `MissingFieldError` messages reported during fragment reading, where the branches of the tree indicate the paths of the errors within the query result

2022-09-13 15:59 UTC, benjamn commented on docs/shared/useFragment-result.mdx
> +A boolean indicating whether the data returned for the fragment is complete.
```suggestion
A boolean indicating whether the data returned for the fragment is complete. When `false`, the `missing` field should explain which fields were responsible for the incompleteness.
```

2022-09-13 16:25 UTC, alessbell commented on docs/shared/useFragment-options.mdx
> +**Required.** The cached object (or object reference) for the fragment being retrieved.
Thanks, +1 for the details. I took this from the `InMemoryCache` docs [section on the `identify` method's signature](https://github.com/apollographql/apollo-client/blob/ee2ff81b7efeb4d3e90a2e2868accf1ef46553ca/docs/source/api/cache/InMemoryCache.mdx#identify) and would be happy to update it there too.

2022-09-13 17:37 UTC, alessbell commented on docs/shared/useFragment-result.mdx
> +An object or string containing an error message or path to cached items with corresponding error messages.
Makes sense - I'm curious about the best way to solicit feedback here but that's a more general question about the way we gather input on features in beta/preview.

2022-09-14 15:31 UTC, merged