Make in-flight deduplication behave more like the cache
apollographql/apollo-client pull request #10163
Opened 2022-10-05 16:18 UTC by chughes87

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2022-10-12 22:59 UTC, jpvajda commented
@chughes87 To move this into a review state, could you look at all the failed tests that are occurring?

2022-10-21 17:46 UTC, chughes87 commented
@jpvajda I was able to get the tests passing locally! I'm not 100% on this implementation however. It depends on the `definitions` array being the same order for there to be a deduplication "hit". I'm not sure that it is reasonable to assume that.

2022-11-02 22:45 UTC, jerelmiller commented on src/__tests__/client.ts
> +    const q2 = client.query({ query: queryDoc, context: { queryDeduplication: true } });
Hey @chughes87! I was glancing at this PR and happened to notice this test. Is this `query` call meant to use `queryDoc2`?

2022-11-10 17:41 UTC, chughes87 commented on src/__tests__/client.ts
> +    const q2 = client.query({ query: queryDoc, context: { queryDeduplication: true } });
oh yes it is thanks for the catch!

2022-11-20 22:38 UTC, chughes87 commented on src/__tests__/client.ts
> +    const q2 = client.query({ query: queryDoc, context: { queryDeduplication: true } });
Updated. Thanks again.

2022-11-21 18:34 UTC, jerelmiller requested changes
Hey @chughes87! Thanks so much for this PR! I think this will be a great addition to the library. I had a couple minor suggestions for you to consider. 

I also noticed that the bundle size check is failing for you. Feel free to tweak that value since its expected that with more code, the library would grow in size. You can find that value in [`config/bundlesize.ts#6`](https://github.com/apollographql/apollo-client/blob/main/config/bundlesize.ts#L6). You can use `npm run bundlesize` locally to check to ensure this check passes.

2022-11-21 18:34 UTC, jerelmiller commented on src/__tests__/client.ts
> +      expect(result2.data.author.name).toEqual(data.author.name);
Could you add a bit more validation here to ensure that `language` is not present on this response since this query specifically didn't include that field in the request? We want to make sure the response data honors the query itself, otherwise I'd consider this a bug.

2022-11-21 18:34 UTC, jerelmiller commented on src/core/QueryManager.ts
> +              inFlightLinkObservables.splice(index);
You'll want to pass in a `deleteCount` to `splice`, otherwise you end up removing everything after the start index.

```suggestion
              inFlightLinkObservables.splice(index, 1);
```

Since tests currently pass, you may want to consider adding a test to ensure in flight observables are removed/kept as expected. What do you think?

2022-11-25 23:49 UTC, chughes87 commented on src/core/QueryManager.ts
> +              inFlightLinkObservables.splice(index);
Oh good catch. Yeah I had hoped that existing tests would catch something like that! I'll see what I can do.

2022-11-25 23:50 UTC, chughes87 commented on src/__tests__/client.ts
> +      expect(result2.data.author.name).toEqual(data.author.name);
Yes this makes sense to me.

2022-11-26 00:00 UTC, chughes87 commented on src/core/QueryManager.ts
> +              inFlightLinkObservables.splice(index);
oh also my findIndex isn't quite right.. I think I am going to implement this with .filter after all. It's simpler overall and I don't think there is really any performance difference.

2022-11-27 23:43 UTC, chughes87 commented on src/core/QueryManager.ts
> +              inFlightLinkObservables.splice(index);
Okay, I adjusted the logic such that it should be right. I am not sure how to set up a test that will make sure we don't have regressions on this cleanup however. I can try and figure it out at a later time. For now I'm feeling done with this.

2022-12-02 18:35 UTC, jerelmiller commented on src/__tests__/client.ts
> +      expect(result2.data.author).not.toHaveProperty('language')
@chughes87 I added a commit to ensure this property is not set ([038a853](https://github.com/apollographql/apollo-client/pull/10163/commits/038a8539f721d46bad1a0d5908e2222e3fee412a)) to ensure the data returned matches the original query.

Looks like the tests all pass 🎉 however I'm seeing a warning in the console:

```
    Cache data may be lost when replacing the author field of a Query object.

    To address this problem (which is not a bug in Apollo Client), define a custom merge function for the Query.author field, so InMemoryCache can safely merge these objects:

      existing: {"name":"Jonas","language":"en"}
      incoming: {"name":"Jonas"}

    For more information about these options, please refer to the documentation:

      * Ensuring entity objects have IDs: https://go.apollo.dev/c/generating-unique-identifiers
      * Defining custom merge functions: https://go.apollo.dev/c/merging-non-normalized-objects
```

Would you expect this warning? Or is this something you feel should be addressed in this PR?

2022-12-05 04:32 UTC, chughes87 commented on src/__tests__/client.ts
> +      expect(result2.data.author).not.toHaveProperty('language')
Okay thanks.

Re: adding the explicit .not.toHaveProperty, I was thinking the .toEqual above it would implicitly test for the absence of a language property. I don't see anything wrong with explicitly checking though.

Re: the new warning. Hm this is interesting. It seems that the results of in flight deduplication feed into the cache in a way I didn't expect. Maybe this is why things were implemented as they were initially. I'll do some investigation to see if this affects the cache as I fear it may..

2022-12-05 05:10 UTC, jerelmiller commented on src/__tests__/client.ts
> +      expect(result2.data.author).not.toHaveProperty('language')
> adding the explicit .not.toHaveProperty

Oh you're right 😅. I've been using `toMatchObject` quite a bit lately and confused the two when looking at the PR. I'll undo my commit since your assertion is sufficient enough to work on its own.

2022-12-05 05:27 UTC, chughes87 commented
After some investigation, I have found that the query merging using mergeDeep may not be a viable way to perform the query comparisons we need to do here. The reason being that the attributes in a given query are stored as an array of objects. Merging arrays simply depends on the ordering and not the content of the objects in the array. Which makes sense. But for this application, it doesn't work in our favor.. It seems we will have to perform a more manual implementation of query comparison. Or I will need to find some other part of the Apollo Client codebase that can help me with this concern. For now, I will close this PR since the current implementation is not a valid solution.

2022-12-05 05:27 UTC, closed without merging