doc(static-typing): rewrite with GraphQL Code Generator setup
apollographql/apollo-client pull request #10173
Opened 2022-10-11 09:08 UTC by charlypoly

Hi Apollo team 👋🏼 

I am Charly, a member of The Guild and current lead of the [GraphQL Code Generator project](https://github.com/dotansimha/graphql-code-generator/).

As we [recently collaborated on AS4 documentation update on Types Generation](https://github.com/apollographql/apollo-server/pull/6904), we thought that we could also help in updating AS3 (and upcoming AS4) documentation regarding best practices when using TypeScript with GraphQL.

GraphQL Code Generator rapidly evolved in the last months and now provides a way smoother way to get typed queries, mutations, and subscriptions, that no longer rely on generated types or hooks.

Example:

```tsx
import React from 'react'
import { useQuery } from '@apollo/client'
 
import './App.css'
import Film from './Film'
import { graphql } from '../src/gql'
 
const allFilmsWithVariablesQueryDocument = graphql(/* GraphQL */ `
  query allFilmsWithVariablesQuery($first: Int!) {
    allFilms(first: $first) {
      edges {
        node {
          ...FilmItem
        }
      }
    }
  }
`)
 
function App() {
  // `data` is typed!
  const { data } = useQuery(allFilmsWithVariablesQueryDocument, { variables: { first: 10 } })
  return (
    <div className="App">
      {data && <ul>{data.allFilms?.edges?.map((e, i) => e?.node && <Film film={e?.node} key={`film-${i}`} />)}</ul>}
    </div>
  )
}
 
export default App
```

Please consider the following changes as a starting draft, I would love to work together in providing documentation that recommends the best developer experience for all GraphQL developers out there.

----

N.B notes/questions:
- Do we still want to include documentation for render props and HoC?

2022-10-12 20:45 UTC, StephenBarlow commented
Hi @charlypoly! Thanks for this PR. Many Apollo folks are taking a breather after our big conference last week, but we'll take a look at this properly next week 👍

2022-10-13 08:21 UTC, charlypoly commented
Hi @StephenBarlow, 

Thank you for the update!

2022-11-08 18:21 UTC, bignimbus reviewed
LGTM @charlypoly - I added a couple of tiny corrections and one question for you.  Thanks so much!

2022-11-08 18:21 UTC, bignimbus commented on docs/source/development-testing/static-typing.md
> +This docs will guide you in installing and configuring it to type hooks, render prop components and high order components.
```suggestion
This docs will guide you in installing and configuring it to type hooks, render prop components and higher-order components.
```

2022-11-08 18:21 UTC, bignimbus commented on docs/source/development-testing/static-typing.md
> +    "codegen": "graphql-codegen -w"
I don't have a strong opinion on this, but WDYT about defining a script with watch mode and a script without?  That way we could add a sentence or two specifying that the watch mode is ideal for development, whereas the default execution is good for git hooks and CI.  Just a thought, I think this is good to merge as-is, we can always iterate later

2022-11-08 18:21 UTC, bignimbus commented on docs/source/development-testing/static-typing.md
> +Since the result of a query will be sent to the wrapped component as props, we want to be able to tell our type system the shape of those props. Here is an example setting types for an operation usin
```suggestion
Since the result of a query will be sent to the wrapped component as props, we want to be able to tell our type system the shape of those props. Here is an example setting types for an operation using the `graphql` higher-order component (**note**: the follow sections also work for the query, mutation, and subscription hocs).
```

2022-11-08 19:43 UTC, rkoron007 requested changes
Thank you so much for this PR [charlypoly](https://github.com/charlypoly)! 🙏 So sorry for my late review here, my suggestions mostly revolve around style, but _please_ feel free to push back if anything doesn't feel good to you.

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +  // `data` is typed!
```suggestion
  // data is typed!
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +Typing `useMutation()` works in a similar way as `useQuery()`.
```suggestion
We can type our `useMutation()` hooks the same way we type our `useQuery()` hooks.
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +By defining your GraphQL document with the generated `gql()` function, your mutation variables and data will get automatically typed.
```suggestion
We can use the generated `gql()` function to define our GraphQL mutations, ensuring our mutation's variables and data are typed:
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +import { gql } from '../src/gql';
```suggestion
import { gql } from '../src/__generated__/gql';
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +  // `data` is typed!
```suggestion
  // data is typed!
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +    // variables are also typed
```suggestion
    // our variables are also typed!
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +By defining your GraphQL document with the generated `gql()` function, your subscriptions variables and data will get automatically typed.
```suggestion
We can use the generated `gql()` function to define our GraphQL subscriptions, ensuring our subscription's variables and data are typed:
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +Your first need to write your GraphQL documents with the generated `gql()` function, exported from `./src/gql`.
```suggestion
To type your render prop components, you'll first define a GraphQL query using the generated `gql()` function (from `src/__generated__/gql`). This creates a type for that query and its variables, which you can then pass to your `Query` component: 
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +This will generate the associated Query and Query variables types that will be passed to the `<Query>` component:
My previous suggestion combines these two sentences :) 
```suggestion
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +import { graphql, AllPeopleQuery, AllPeopleQueryVariables } from '../src/gql';
Do we need to import `graphql` here? I'm honestly curious, I'm not sure. Updating the import for my previous suggestion:

```suggestion
import { graphql, AllPeopleQuery, AllPeopleQueryVariables } from '../src/__generated__/gql';
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +Your first need to write your GraphQL documents with the generated `gql()` function exported from `./src/gql`.
```suggestion
To type high-order components, begin by defining your GraphQL documents with the generated `gql()` function (from `./src/__generated__/gql`).
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +This will generate the associated Query and Query variables types: `GetCharacterQuery` and `GetCharacterQueryVariables`.
```suggestion
In the below example, this generates the query and variable types (`GetCharacterQuery` and `GetCharacterQueryVariables`).
```

2022-11-08 19:43 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +Since the result of a query will be sent to the wrapped component as props, we want to be able to tell our type system the shape of those props. Here is an example setting types for an operation usin
Further suggestions for style: 
```suggestion
Our wrapped component receives the query's result as props. So, we need to tell our type system the _shape_ of these props. Below is an example of setting types for an operation using the `graphql` higher-order component. 

> The following logic also works for the query, mutation, and subscription higher-order components!
```

2022-11-16 15:04 UTC, charlypoly commented on docs/source/development-testing/static-typing.md
> +    "codegen": "graphql-codegen -w"
```suggestion
    "compile": "graphql-codegen", 
    "watch": "graphql-codegen -w",
```

2022-11-16 15:11 UTC, charlypoly commented on docs/source/development-testing/static-typing.md
> +    "codegen": "graphql-codegen -w"
Updated!

2022-11-16 15:12 UTC, charlypoly commented
@bignimbus, @rkoron007, thank you for your thorough review! I've applied the suggestion and committed some changes.

2022-11-17 17:34 UTC, rkoron007 reviewed
I had a few small suggestions, but since they are mainly tiny tweaks, I can take care of batching and committing them so this merged in sooner!

2022-11-17 17:34 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +Below, we'll guide you through installing and configuring GraphQL Code Generator to generate types for your hooks and components.
We'll need to insert a line here to break this out to a separate paragraph:
```suggestion

Below, we'll guide you through installing and configuring GraphQL Code Generator to generate types for your hooks and components.
```

2022-11-17 17:34 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +To get started using GraphQL Code Generator to generate TypeScript types, we'll begin by installing the following packages (using Yarn or NPM):
Making this sentence a little less wordy:
```suggestion
To get started using GraphQL Code Generator, we'll begin by installing the following packages (using Yarn or NPM):
```

2022-11-17 17:34 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +import { CodegenConfig } from '@graphql-codegen/cli'
```suggestion
import { CodegenConfig } from '@graphql-codegen/cli';
```

2022-11-17 17:34 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +export default config
```suggestion
export default config;
```

2022-11-17 17:34 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
>  }
```suggestion
};
```

2022-11-17 17:34 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +There are multiple ways to [specify a schema](https://www.the-guild.dev/graphql/codegen/docs/config-reference/schema-field#root-level) in your `codegen.ts`, so pick the way that works best for your p
Thinking about this further, I think this note would make a lovely callout:
```suggestion
> There are multiple ways to [specify a schema](https://www.the-guild.dev/graphql/codegen/docs/config-reference/schema-field#root-level) in your `codegen.ts`, so pick the way that works best for your project setup.
```

2022-11-17 17:34 UTC, rkoron007 commented on docs/source/development-testing/static-typing.md
> +GraphQL Code Generator generates types based on our GraphQL schema if we run either code-generation scripts above:
This was probably my suggestion's bad:
```suggestion
GraphQL Code Generator generates types based on our GraphQL schema if we run either code-generation script above:
```

2022-11-17 17:35 UTC, rkoron007 approved these changes

2022-11-17 22:04 UTC, merged

2022-11-18 10:53 UTC, charlypoly commented
@rkoron007 @bignimbus @StephenBarlow, thank you for your valuable and fast feedback! ⚡