Add troubleshooting tips to the reactive var documentation.
apollographql/apollo-client pull request #10235
Opened 2022-10-27 02:30 UTC by larrymyers

This PR adds examples to the docs on how to avoid some common pitfalls when using reactive vars.  It should hopefully help people get some time back when trying to triage issues with reactive vars mutations not triggering component updates in React applications.

2022-10-27 02:30 UTC, apollo-cla commented
@larrymyers: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2022-11-11 15:48 UTC, bignimbus commented
Thanks so much @larrymyers for your contribution!  We'll be taking a look at this soon 🙏🏻

2022-11-15 04:05 UTC, bignimbus requested changes
Thanks @larrymyers! I left some notes for your consideration 🙏🏻

2022-11-15 04:05 UTC, bignimbus commented on docs/source/local-state/reactive-variables.mdx
> +const errorLink = onError((error: ErrorResponse) => {
This is an interesting example but it doesn't seem like an idiomatic use of reactive variables to me.  I am probably missing something though and am eager to learn!  Could you help me understand why GraphQL operation errors couldn't be handled conventionally through `QueryResult#error` / error policies?

2022-11-15 14:18 UTC, larrymyers commented on docs/source/local-state/reactive-variables.mdx
> +Currently `useReactiveVar` only triggers component updates when new values are passed to the reactive var, since it uses strict equality checks (the `===` operator). Make sure you are alway passing c
Good catch. 😁

2022-11-15 14:18 UTC, larrymyers commented on docs/source/local-state/reactive-variables.mdx
> +const errorLink = onError((error: ErrorResponse) => {
@bignimbus The specific use case here is if you want to make errors visible to the user in a common UI. Imagine that any time an error happens in the React app you want to capture the error and display a friendly error message in a modal. While you could use a React Portal here, having a reactive variable means you can have a React modal component at the top level of the virtual DOM just update on reactive variable changes and render correctly as a modal.

2022-11-15 14:19 UTC, larrymyers commented on docs/source/local-state/reactive-variables.mdx
> +### Updating Arrays
@bignimbus I've pushed an update to the PR and moved my examples up to the Modifying section, and make the example consistent with the existing one.

2022-11-17 15:21 UTC, bignimbus requested changes
Thanks @larrymyers for the quick updates!  I suggested some further edits to the reactive variables section.  Once we get those in and remove the "Troubleshooting" section I think we'll be good to merge 😃

2022-11-17 15:21 UTC, bignimbus commented on docs/source/local-state/reactive-variables.mdx
> +
Can we be more concise here?  An extra couple of lines in the above code block should be sufficient:

---

To modify the value of your reactive variable, call the function returned by `makeVar` with one argument (the variable's new value):

```js
const cartItemsVar = makeVar([]);
const cartItemIds = [100, 101, 102];

cartItemsVar(cartItemIds);

// Output: [100, 101, 102]
console.log(cartItemsVar());

// Don't mutate an existing object or array.
// cartItemIds.push(456) will not trigger an update.
// Instead, pass a new copy:
cartItemsVar([...cartItemIds, 456]);

// Output: [100, 101, 102, 456]
console.log(cartItemsVar());
```

2022-11-17 15:21 UTC, bignimbus commented on docs/source/local-state/reactive-variables.mdx
> +const errorLink = onError((error: ErrorResponse) => {
Thanks for your reply @larrymyers  - I'm glad this approach is working for your application.  Still, I don't think the Apollo Client docs are the right place for this sample code so I'll ask that we omit this section to get this PR into a mergeable state 🙏🏻

2022-11-18 12:08 UTC, larrymyers commented on docs/source/local-state/reactive-variables.mdx
> +const errorLink = onError((error: ErrorResponse) => {
@bignimbus that's fair. I can certainly do a deeper dive into reactive variables with Apollo as a blog post.

2022-11-18 12:13 UTC, larrymyers commented on docs/source/local-state/reactive-variables.mdx
> +
Done. I agree your suggestion still calls out the important bits of modifying reactive variables to avoid unexpected behavior around triggering updates.

2022-11-18 12:19 UTC, larrymyers commented
@bignimbus I think we're good to go here.  Thanks for your time getting this distilled down to a much smaller change that still conveys the core concept in the docs.

2022-11-21 20:10 UTC, merged