fix: error when server throws and we are also querying for a local field
apollographql/apollo-client pull request #10362
Opened 2022-12-13 11:38 UTC by mccraveiro

closes #10345

2022-12-19 20:28 UTC, jerelmiller commented
Hey @mccraveiro 👋 ! Thanks for your contribution and your patience!

I'd like to take a bit more time to understand the root issue here, and when I do, I'd be happy to provide a review. It's very likely your fix is the correct one here.

Just as an FYI, with the holidays coming up, I can't guarantee I'll be able to review this before the New Year as I've got a few commits I'm working on. I'll keep it on my radar though to come back to it as soon as I can!

2023-01-04 00:12 UTC, jerelmiller requested changes
Hey @mccraveiro 👋 ! Thanks so much for this fix! 

I think this looks great. I'd be happy to approve and merge if we can wordsmith the description of the test a bit more as I'd like to see if we can capture the scenario that is being tested a bit more. See the comment for more details.

2023-01-04 00:12 UTC, jerelmiller commented on src/__tests__/local-state/general.ts
> +      expect(operation.operationName).toBe('GetUser');
```suggestion
```

Since this test is focused on checking that local resolvers are handled correctly when parent fields are null, I don't think we need this extra expectation. Let's omit it to reduce noise in the test.

2023-01-04 00:12 UTC, jerelmiller commented on src/__tests__/local-state/general.ts
> +  itAsync('should handle server errors when field is required', (resolve, reject) => {
I'm not quite sold on the description here. While I get the reason behind this, I'd like to be a bit more specific about when this situation arises. 

I'm understanding the exception to be thrown when the root `data` property returns null. In cases where partial data is returned, local resolvers work as expected. Perhaps we could update this to something like:

```suggestion
  itAsync('handles server errors when root data property is null', (resolve, reject) => {
```

Feel free to wordsmith this a bit more, but I think something like this better captures the scenario we are testing. There are a variety of reasons the server might return `null` for the root `data` field, not just because a field is non-null, so I'd love for the test to reflect this.

2023-02-02 16:44 UTC, alessbell approved these changes

2023-02-02 16:56 UTC, alessbell commented
Went ahead and committed those suggestions, thanks @jerelmiller!

This looks ready to go, thanks @mccraveiro! 🙌

2023-02-02 16:57 UTC, merged

2023-02-03 20:54 UTC, mccraveiro commented
Thanks @alessbell and @jerelmiller! I was on vacation and moving to another city so I missed this notification 😉

2023-02-03 20:55 UTC, jerelmiller commented
No problem! Hope your vacation was great!