Fixes support for defer in mutations
apollographql/apollo-client pull request #10368
Opened 2022-12-14 18:40 UTC by alessbell

To do:
- [ ] test case: errors on incremental items
- [ ] test case: custom update function
- [ ] docs

2022-12-14 18:41 UTC, alessbell commented on src/utilities/common/incrementalResult.ts
> +import { ExecutionPatchIncrementalResult } from "../../link/core";
Formatting only in this file

2022-12-14 18:41 UTC, alessbell commented on src/core/QueryManager.ts
> +              // TODO: does this still make sense?
Still need to add a test case for custom update functions (see PR TODO)

2022-12-15 07:14 UTC, jerelmiller requested changes
This PR has lots of really good stuff. The refactors are also great so thanks for putting in the effort to do so!

Many of my comments are [nit] related and you can use your best judgement on whether you'd like to address them or not. There are really only 1 or 2 comments in here that I'd like to see addressed before this PR is merged (specifically the one about the `delete` functionality). 

Really great work! I'm excited to get this in 🎉 🎉 🎉

2022-12-15 07:14 UTC, jerelmiller commented on src/core/QueryManager.ts
> +      if (isExecutionPatchResult(result) && isNonEmptyArray(result.incremental)) {
```suggestion
      if (isExecutionPatchIncrementalResult(result) && isNonEmptyArray(result.incremental)) {
```

Would it make sense to use `isExecutionPatchIncrementalResult` here? It might be a bit more meaningful since this chunk of data operates on incremental chunks

2022-12-15 07:14 UTC, jerelmiller commented on src/core/QueryManager.ts
> +        const mergedData = mergeIncrementalData<TData | undefined>(diff.result, result);
```suggestion
        const mergedData = mergeIncrementalData(diff.result, result);
```
Since you've typed `cache.diff` above with `TData`, do you need to pass this generic? I think type inference will work here since it should be able to infer `TData` from the first argument.

2022-12-15 07:14 UTC, jerelmiller commented on src/core/QueryManager.ts
> +            throw new ApolloError({ graphQLErrors });
```suggestion
            throw new ApolloError({ graphQLErrors: mergeGraphQLErrors(result) });
```

[suuuuuuppperrrrrr nit] If you want to reduce to a single line, I find this readable as well.

2022-12-15 07:14 UTC, jerelmiller commented on src/react/hooks/__tests__/useMutation.test.tsx
> +      expect(onError).toHaveBeenCalledTimes(1);
[nit] You might consider extracting this to a separate test. This expectation isn't really captured in the test name nor is it really part of the goal of this test, which is to check the resolved value of the mutation.

2022-12-15 12:32 UTC, alessbell commented on src/utilities/common/incrementalResult.ts
>    return !!(value as ExecutionPatchIncrementalResult).incremental;
Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/f394e60f26db374dd4f4deadec9784da02ed6bb7.

2022-12-15 12:33 UTC, alessbell commented on src/utilities/common/incrementalResult.ts
> +  value: any
I like the idea of using type signature for communicating the intent of the type guard 👍 Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/f394e60f26db374dd4f4deadec9784da02ed6bb7.

2022-12-15 12:34 UTC, alessbell commented on src/utilities/common/incrementalResult.ts
> +    !!(value as ExecutionPatchInitialResult).hasNext &&
Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/f394e60f26db374dd4f4deadec9784da02ed6bb7.

2022-12-15 12:34 UTC, alessbell commented on src/utilities/common/incrementalResult.ts
> +  value: any
Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/f394e60f26db374dd4f4deadec9784da02ed6bb7.

2022-12-15 15:14 UTC, alessbell commented on src/core/QueryManager.ts
> +        const mergedData = mergeIncrementalData<TData | undefined>(diff.result, result);
Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/31949b340454b176fba65b0f46d92afc23b3a735.

2022-12-15 15:14 UTC, alessbell commented on src/core/QueryManager.ts
> +            throw new ApolloError({ graphQLErrors });
Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/31949b340454b176fba65b0f46d92afc23b3a735#diff-5fb8ad16cfbcb51bc035d32b5963734561c440b48417a1c2dbf80a16098be67bR255-R257.

2022-12-15 15:15 UTC, alessbell commented on src/core/QueryManager.ts
> +                result = { ...result as FetchResult, data: diff.result };
Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/31949b340454b176fba65b0f46d92afc23b3a735#diff-5fb8ad16cfbcb51bc035d32b5963734561c440b48417a1c2dbf80a16098be67bR255-R257.

2022-12-15 15:18 UTC, alessbell commented on src/core/QueryManager.ts
> +              (isExecutionPatchIncrementalResult(result) && !result.hasNext)
I thought about pulling this into its own boolean and forgot to 😄 And totally agree—I avoid applying the DRY principle just for the sake of it but +1 to improved readability here. Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/31949b340454b176fba65b0f46d92afc23b3a735#diff-5fb8ad16cfbcb51bc035d32b5963734561c440b48417a1c2dbf80a16098be67bR255-R257.

2022-12-15 15:19 UTC, alessbell commented on src/core/QueryManager.ts
> +        const hasErrors = graphQLResultHasError(result);
Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/31949b340454b176fba65b0f46d92afc23b3a735.

2022-12-15 15:33 UTC, alessbell commented on src/utilities/common/errorHandling.ts
> +export function mergeGraphQLErrors(result: FetchResult<unknown>) {
Makes sense 👍 Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/9e6330838bdadb767381ef4e79f3b159415bb011.

2022-12-15 16:22 UTC, alessbell commented on src/react/hooks/__tests__/useMutation.test.tsx
> +              variablesMatched = true;
I borrowed from the existing test for the update function to bootstrap a test quickly, and while I changed much of it, this line remained. Agree this is redundant, removed in https://github.com/apollographql/apollo-client/pull/10368/commits/390640c43852f8a91d599169ecbd6091af1a92b8.

2022-12-15 16:22 UTC, alessbell commented on src/react/hooks/__tests__/useMutation.test.tsx
> +    it('update function', async () => {
I totally put that name in as a placeholder and forgot to update it 😅 yours is much better, thanks! Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/390640c43852f8a91d599169ecbd6091af1a92b8.

2022-12-15 16:23 UTC, alessbell commented on src/react/hooks/__tests__/useMutation.test.tsx
> +    it('should handle defer directive', async () => {
Totally agree, thanks for your wordsmithing here! Resolved in https://github.com/apollographql/apollo-client/pull/10368/commits/390640c43852f8a91d599169ecbd6091af1a92b8.

2022-12-15 16:24 UTC, alessbell commented on src/react/hooks/__tests__/useMutation.test.tsx
> +      expect(onError).toHaveBeenCalledTimes(1);
I've updated the title of the test to `resolves with resulting errors and calls onError callback`, as I think that captures the intent better 👍

2022-12-15 16:33 UTC, alessbell commented on src/react/hooks/__tests__/useMutation.test.tsx
> +        await createTodo({ variables });
Wow, thanks for such a detailed reply here! I really love the idea of each test as a story that guides the reader through the surface area/behavior being validated, and the importance of a logical chronology. I've updated this test based on your feedback [starting on L2371 here](https://github.com/apollographql/apollo-client/pull/10368/commits/390640c43852f8a91d599169ecbd6091af1a92b8#diff-17612b300c794aebf7a23095f2c6212fe0ba653bd8a771ee3ff501c1307053d4R2371).

It turned out that both creating the promise and awaiting it had to be wrapped in `act` lest the dreaded React act warning appear, and in the end I didn't `wait` between `simulateResult` calls (which I was able to call directly instead of inside `setTimeout`s) as it didn't seem necessary for either readability or the test's execution. Now the test follows an order much closer to how it would be invoked in an actual app 😄

2022-12-15 16:38 UTC, alessbell commented
Thanks so much for the review, @jerelmiller! 🙏

I've incorporated all of your feedback and left the one comment unresolved that I wanted your thoughts on. (All other comments should have been resolved with a link to the commit where they were addressed.) Thanks again!

2022-12-15 17:12 UTC, jerelmiller commented on src/react/hooks/__tests__/useMutation.test.tsx
> +    it('update function', async () => {
Haha no problem! appreciate you updating it 😄

2022-12-15 17:14 UTC, jerelmiller commented on src/core/QueryManager.ts
> +              (isExecutionPatchIncrementalResult(result) && !result.hasNext)
Agreed, I don't think blindly adhering to DRY is always a good thing. Thanks for making this update! This makes the intent of the code super clear.

2022-12-15 17:16 UTC, jerelmiller commented on src/react/hooks/__tests__/useMutation.test.tsx
> +        await createTodo({ variables });
Awesome. Love it! Thanks so much for updating!

2022-12-15 17:19 UTC, jerelmiller commented on src/core/QueryManager.ts
> +      if (isExecutionPatchResult(result) && isNonEmptyArray(result.incremental)) {
Ah that makes sense. I wasn't seeing that connection when reviewing. Your solution works great. Thanks!

2022-12-15 17:23 UTC, jerelmiller commented on src/core/QueryManager.ts
>            // resolve only later, in an observer.complete function.
Oops, forgot to add this to my initial review. Can we remove part of/all of this comment? Since you are now implementing the ability this comment refers to, it might be confusing to leave it since it still reads as something unimplemented. If need be, perhaps replace with a comment explaining the functionality below?

2022-12-15 17:24 UTC, jerelmiller commented on src/core/QueryManager.ts
> +              (isExecutionPatchIncrementalResult(result) && !result.hasNext)
```suggestion
              isFinalResult
```

Now that you've extracted the variable, could you use it here?

2022-12-15 17:26 UTC, jerelmiller approved these changes
Thanks so much for your diligent work addressing all my comments (even the super nitpicky ones 😆 ). Will be great to get this in for those working with `@defer`! 🎉 🎉

2022-12-15 18:17 UTC, alessbell commented on src/core/QueryManager.ts
> +              (isExecutionPatchIncrementalResult(result) && !result.hasNext)
Oops! Updated :)

2022-12-15 18:17 UTC, alessbell commented on src/core/QueryManager.ts
>            // resolve only later, in an observer.complete function.
Yes, I was meaning to do that! Thanks for catching this!!

2022-12-15 18:22 UTC, merged