Upgrades to TypeScript 4.9.4
apollographql/apollo-client pull request #10470
Opened 2023-01-23 19:34 UTC by alessbell

Branched off of https://github.com/apollographql/apollo-client/pull/10305 which itself branched off of https://github.com/apollographql/apollo-client/pull/9919.

Upgrades from TS `4.7.4` to `4.9.4` and makes relevant fixes (see #9199).

### Checklist:

- [ ] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](../CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2023-01-23 20:13 UTC, alessbell commented on src/react/hoc/__tests__/queries/reducer.test.tsx
> +    const ContainerWithData = graphql<{}, Data, {}, Record<string, any>>(query, {
There were about a dozen similar errors inside these HOC tests mostly relating to the way we're using `ChildProps`, and the error messages are pretty inscrutable. I opted to lose a little bit of type granularity/sophistication instead of digging into how to properly extend the inferred type that the final generic should now extend.

2023-01-23 22:56 UTC, jerelmiller requested changes
This is fantastic! Thanks for helping shepard this along.

I had a few comments in regards to the `{}` type that I'd like to check on, but otherwise this looks great!

2023-01-23 22:56 UTC, jerelmiller commented on src/core/ApolloClient.ts
> +    TContext extends {} = DefaultContext,
Is this `{}` type meant to represent a type that is an object? The `{}` type actually means "any non-nullish value", not an object, so we probably want to be a bit more specific here.

You can read more about it in [this comment](https://github.com/typescript-eslint/typescript-eslint/issues/2063#issuecomment-675156492) posted to ESLint, which has an [ESLint rule](https://typescript-eslint.io/rules/ban-types) around this particular behavior.

Instead, we should opt to check against `Record<string, any>` to ensure this is scoped to object types.

```suggestion
    TContext extends Record<string, any> = DefaultContext,
```

2023-01-23 22:56 UTC, jerelmiller commented on src/core/QueryManager.ts
> +    TContext extends {},
```suggestion
    TContext extends Record<string, any>,
```

See comment above on the reasoning.

2023-01-23 22:56 UTC, jerelmiller commented on src/react/hoc/__tests__/queries/reducer.test.tsx
> +    const ContainerWithData = graphql<{}, Data, {}, Record<string, any>>(query, {
Does this have implications for people that might be using this function if they were to upgrade? If its difficult for us, I'm curious if it will have the same effect on others.

2023-01-23 22:56 UTC, jerelmiller commented on src/react/hoc/graphql.tsx
> +type ChildProps<TData extends {}, TGraphQLVariables extends OperationVariables> =
```suggestion
type ChildProps<TData extends Record<string, any>, TGraphQLVariables extends OperationVariables> =
```

See comment above on reasoning.

2023-01-23 22:56 UTC, jerelmiller commented on src/react/hoc/graphql.tsx
> +  TData extends {} = {},
```suggestion
  TData extends Record<string, any> = Record<string, any>,
```

2023-01-23 22:56 UTC, jerelmiller commented on src/react/hoc/mutation-hoc.tsx
> +  TGraphQLVariables extends OperationVariables = {},
```suggestion
  TGraphQLVariables extends OperationVariables = OperationVariables,
```

2023-01-23 22:56 UTC, jerelmiller commented on src/react/hoc/mutation-hoc.tsx
> +  TContext extends DefaultContext = DefaultContext,
```suggestion
  TContext extends Record<string, any> = DefaultContext,
```

While these are technically the same types and this has no issue from the TypeScript compiler's perspective, I prefer to use a separate type assertion here. The reason is that `DefaultContext` is really meant to be a _default_, not necessarily the "type of this thing". `DefaultContext`. I like to think of `extends` as "a type that behaves as X". To me, its a bit funky to think of this as "a type that behaves like DefaultContext", really because of the "Default" in the name.

Thoughts?

2023-01-23 22:56 UTC, jerelmiller commented on src/react/hoc/query-hoc.tsx
> +  TGraphQLVariables extends {} = {},
```suggestion
  TData extends Record<string, any> = Record<string, any>,
  TGraphQLVariables extends Record<string, any> = Record<string, any>,
```

2023-01-23 22:56 UTC, jerelmiller commented on src/react/hoc/subscription-hoc.tsx
> +  TGraphQLVariables extends {} = {},
```suggestion
  TGraphQLVariables extends Record<string, any> = Record<string, any>,
```

2023-01-23 22:56 UTC, jerelmiller commented on src/react/hoc/subscription-hoc.tsx
> +  TChildProps extends { [x: string]: any; } = DataProps<TData, TGraphQLVariables>
[nit] You can use `Record` here if you prefer the stylistic cleanliness instead of the indexed type:

```suggestion
  TChildProps extends Record<string, any> = DataProps<TData, TGraphQLVariables>
```

2023-01-23 22:56 UTC, jerelmiller commented on src/utilities/common/cloneDeep.ts
> +    Object.keys(val as T & {}).forEach(key => {
Could you talk me through what this is doing? I've not seen an intersection with plain `{}` before, so I'd love to learn something new 😄

2023-01-23 22:56 UTC, jerelmiller commented on src/utilities/common/incrementalResult.ts
> +    isExecutionPatchInitialResult<T>(value)
[nit] Do you need to pass this type to `isExecutionPatchInitialResult`? Since `value` is a `FetchResult<T>`, `isExecutionPatchInitialResult` should be able to infer `T`.

2023-01-23 22:59 UTC, jerelmiller commented on src/core/ApolloClient.ts
> +    TContext extends {} = DefaultContext,
Here is a great playground that demonstrates this oddity: https://www.typescriptlang.org/play?#code/GYVwdgxgLglg9mABMOcA8AVRBTAHlbMAEwGdEBvAXwD4AKABwEMAnRgWwC5EMBKCygFACUcWlGYhsPANzDUtAIwy5oqspG0wIADbaZiAPQGcuetmjYiOZszjMBQA

2023-01-25 16:42 UTC, alessbell commented on src/core/ApolloClient.ts
> +    TContext extends {} = DefaultContext,
Thanks for the review, @jerelmiller! I'm just getting up to speed on the changes in TS >= `4.8` and I think this reference thread adds context around some of your comments/questions: https://github.com/microsoft/TypeScript/issues/49489

There are definitely opportunities to make some generic params narrower/more specific; the initial goal here was to address unconstrained parameters where the previous behavior would have allowed `null`/`undefined` to be passed ([docs](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-4-8.html#unconstrained-generics-no-longer-assignable-to-)) when `strictNullChecks` is `true`. For that reason, the docs suggest `{}` as an initial step to narrowing unconstrained parameters given that it's `undefined`/`null` that should be disallowed, but we can definitely use `T extends object` (or e.g. `Record<string, unknown>`) where strings, numbers, and booleans are also not expected.

2023-01-25 16:45 UTC, alessbell commented
Right now, all of these changes are backward-compatible, _except the changes to the HOC interfaces_, hence having to update significant test code in that part of the codebase.

I'd like to take a closer look at those, but won't be able to prioritize it for a week or so (we can also target this for `4.0` if that eventually seems to make more sense, but I'd like to avoid that if possible). Leaving this PR open in the meantime.

2023-01-25 17:09 UTC, alessbell commented on src/react/hoc/graphql.tsx
> +type ChildProps<TData extends {}, TGraphQLVariables extends OperationVariables> =
As far as I can tell `extends object` and `extends Record<string, any>` are functionally equivalent. The docs recommend `object`, but I've opted for `Record<string, any>` across the board for consistency.

2023-01-25 17:16 UTC, alessbell commented on src/react/hoc/mutation-hoc.tsx
> +  TContext extends DefaultContext = DefaultContext,
Sounds good to me 👍

2023-01-25 17:18 UTC, alessbell commented on src/react/hoc/__tests__/queries/reducer.test.tsx
> +    const ContainerWithData = graphql<{}, Data, {}, Record<string, any>>(query, {
Yep, definitely -- this was something I was going to circle back to, and it's proving to be more difficult to resolve in a backward-compatible way than anticipated. I imagine it's doable, but the HOC types are fairly complex; I should have more time to dive into this next week, but this seems to be the main/only blocker of this PR (see https://github.com/apollographql/apollo-client/pull/10470#issuecomment-1403911533 for thoughts on targeting a major release.)

2023-01-25 17:25 UTC, alessbell commented on src/utilities/common/cloneDeep.ts
> +    Object.keys(val as T & {}).forEach(key => {
Since `cloneDeepHelper` takes an unconstrained param `T` and is designed to handle arguments of all types including `null`/`undefined` (see tests), instead of narrowing the unconstrained param, in the `"[object Object]"` case we're casting to the intersection of `T & {}`. I've since updated this to be the intersection of `T & Record<string, any>` to make this more explicit.

2023-01-25 17:27 UTC, alessbell commented on src/utilities/common/incrementalResult.ts
> +    isExecutionPatchInitialResult<T>(value)
Good catch! Updated.

2023-01-25 19:01 UTC, jerelmiller commented on src/core/ApolloClient.ts
> +    TContext extends {} = DefaultContext,
That makes sense. Thanks for the reference! I trust you made the right call in the right places.

2023-01-25 19:02 UTC, jerelmiller approved these changes
This looks great to me. Thanks for handling this!

2023-01-26 02:22 UTC, merged

2023-02-08 04:58 UTC, PowerKiKi commented on src/cache/inmemory/inMemoryCache.ts
> +  public diff<TData, TVariables extends OperationVariables = any>(
This is a breaking change for TypeScript users and should probably have been released in a major version, or at least mentioned in the changelog.

2023-02-08 09:03 UTC, phryneas commented on src/cache/inmemory/inMemoryCache.ts
> +  public diff<TData, TVariables extends OperationVariables = any>(
`OperationVariables` is defined as `Record<string, any>`, so this only makes sure what you pass in as `variables` is an object, and not a primitive value like `string`, which would (afaik) always have caused a runtime error in the past. So I would not see it as a breaking change, but more the types getting closer to existing runtime behaviour.  
To make sure I'm not missing something: Can you think of anything that could have been used here in the past that would not have caused a runtime error?

2023-02-08 11:45 UTC, PowerKiKi commented on src/cache/inmemory/inMemoryCache.ts
> +  public diff<TData, TVariables extends OperationVariables = any>(
I get what you are saying, and I agree that there is no _runtime_ breaking change. But for TypeScript users a change of type might mean a _compile time_ breaking change. And turns out it did break compilation for a bunch of users: https://github.com/kamilkisiela/apollo-angular/issues/1907

But I get it, it's not a huge change, and not such as terrible thing to deal with for us. But still, it creates a bit of friction. I thought you might want to hear about it, so maybe you could handle it differently for future cases (or not, that's up to you :sweat_smile: )

2023-02-08 12:44 UTC, phryneas commented on src/cache/inmemory/inMemoryCache.ts
> +  public diff<TData, TVariables extends OperationVariables = any>(
Yeah, I was explicitly asking for situations where this could break at all - and you are right, non-restricted, yet-unresolved generic arguments that are forwarded are impacted by this - essentially, this can occur if you wrap the type or a usage of the type with your own generalized implementation. I didn't think of that use case.  
As this is out right now, I don't think we should go "back" on it in this specific use case - especially since it might block users from upgrading their TypeScript version (this was changed for a reason, after all).

But yes, generally, we are trying to keep TypeScript changes that could break things in user code out of patch releases and at least target minor versions with them. Targeting major versions is not feasible, since we have long iterations here and TypeScript itself is just advancing *very* fast. But we will try to communicate it better in the future.

As for the problem at hand: fixing this requires that you add the same constraint on your end, so this change will be required: 
```diff
-export class QueryRef<T, V = EmptyObject> {
+export class QueryRef<T, V extends OperationVariables = EmptyObject> {
```

I will see that I file a PR on your side to reduce friction.

2023-02-08 13:11 UTC, phryneas commented on src/cache/inmemory/inMemoryCache.ts
> +  public diff<TData, TVariables extends OperationVariables = any>(
@PowerKiKi there you go :) https://github.com/kamilkisiela/apollo-angular/pull/1910