Update hooks-experimental.mdx
apollographql/apollo-client pull request #10638
Opened 2023-03-09 19:12 UTC by chaunceyau

Think there's a misconception that the only use of fragments is to re-use and not have to redefine fields. This doesn't seem to be the primary benefit of fragments, i.e. if it were, it'd just push us in the direction of rest implementations where we're over-fetching data.

### Checklist:

- [x] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

2023-03-09 19:14 UTC, jerelmiller approved these changes
This is a great change. Thanks for helping us make our docs better!

2023-03-09 19:18 UTC, jerelmiller commented
@chaunceyau fair warning, this might take a little bit before we can merge. We've had some issues with our CLA bot that is currently in the process of getting fixed. Once that is back up and running, we'll be able to get this merged.

2023-03-09 19:51 UTC, alessbell requested changes
Left one small comment but once that's updated this will be a nice improvement. Thanks!

2023-03-09 19:51 UTC, alessbell commented on docs/source/api/react/hooks-experimental.mdx
> +> A [GraphQL fragment](http://graphql.org/learn/queries/#fragments) defines a subselection of fields on a GraphQL type, that can help define component-level data dependencies or allow re-use between
Small tweak: our [fragment docs](https://www.apollographql.com/docs/react/data/fragments/) use the term "subset":

```suggestion
> A [GraphQL fragment](http://graphql.org/learn/queries/#fragments) defines a subset of fields on a GraphQL type that can be used to specify component-level data dependencies or allow re-use between multiple queries and mutations. [See the API reference.](../../data/fragments)
```

2023-03-09 21:48 UTC, chaunceyau commented on docs/source/api/react/hooks-experimental.mdx
> +> A [GraphQL fragment](http://graphql.org/learn/queries/#fragments) defines a subselection of fields on a GraphQL type, that can help define component-level data dependencies or allow re-use between
I love that, ty! Updated 👍

2023-03-09 21:48 UTC, chaunceyau commented
> @chaunceyau fair warning, this might take a little bit before we can merge. We've had some issues with our CLA bot that is currently in the process of getting fixed. Once that is back up and running, we'll be able to get this merged.

No worries at all, completely understand! 🤞

2023-03-15 17:51 UTC, alessbell approved these changes
CLA bot is fixed now so I can get this merged, thanks!

2023-03-15 18:08 UTC, merged