change `waitFor` brace style, switch `interval` default
apollographql/apollo-client pull request #10662
Opened 2023-03-17 09:20 UTC by phryneas

# do not merge before #10661 has been merged

This PR changes from
```js
waitFor(() => {
  expect(...)
}, {interval: 1}
)
```
to

```js
waitFor(() => expect(...))
```
in a *ton* of places,
and in return replaced
```js
waitFor(() => {
  expect(...)
})
```
with 

```js
waitFor(
  () => expect(...),
  {interval: 50}
)
```

We used `interval: 1` a lot more often than skipping the parameter, and like this, it makes it much more obvious where we still had the slower default. We might want to revisit those places.

I've also highlighted some `waitFor` instances that just seem wrong, but I didn't change any runtime behaviour of the tests - that's for another PR.

I've also dropped the method body braces where there was only one statement in `waitFor`, as that compacts the tests a bit.

# do not merge before #10661 has been merged

2023-03-21 03:32 UTC, lhmzhou approved these changes
LGTM

2023-03-31 11:16 UTC, benjamn approved these changes
Yay for reducing test boilerplate!

Were you able to automate this with a codemod or editor tricks? If it was all by hand, we should try to get these changes merged sooner, so you don't have to keep rebasing.

2023-03-31 20:00 UTC, alessbell approved these changes
🎉🎉

2023-07-06 04:33 UTC, jerelmiller requested changes
I'm gonna be the bad guy here 😜. Check out my comments and let me know what you think.

I'd also like to float the question: is this PR still relevant? We've had it open for some time now unmerged and wasn't sure if thats because it was forgotten or not.

2023-07-06 04:33 UTC, jerelmiller commented on src/react/hooks/__tests__/useSuspenseQuery.test.tsx
> +    await waitFor(() =>
Any reason these needed to change? Perhaps I'm picky/selfish, but this seems like a change for the sake of change. I'd prefer to leave these alone for now.

2023-07-06 04:33 UTC, jerelmiller commented on src/react/hooks/__tests__/useSuspenseQuery.test.tsx
I'll be the bad guy and say I'm not sure I see much meaningful change in this file. It feels like change for the sake of change. Any chance we could revert this?

2023-07-06 04:33 UTC, jerelmiller commented on src/react/hooks/__tests__/useQuery.test.tsx
> +const waitFor: typeof _waitFor = (callback, options) =>
I see enough `interval: 50` overrides in here to think that this change doesn't make as big of an impact as normal. Could you perhaps rename this to `waitForOne` and use that in places where `interval: 1` is set? That way we can leave anything with `interval: 50` to use the default `waitFor` function without needing the override.

2023-07-06 04:33 UTC, jerelmiller commented on src/react/hooks/__tests__/useLazyQuery.test.tsx
> +const waitFor: typeof _waitFor = (callback, options) =>
Could we consider naming this `waitForOne` and use that everywhere we use `waitFor` with `interval: 1`? That way its easier to use the built-in `waitFor` without needing the override where necessary. Thoughts?

2023-07-06 09:18 UTC, phryneas commented
This was a follow-up PR to the prettier PR, so I guess some of the style changes you are seeing might be prettier-related - the extra braces mean more newlines and blow up our already very big test files, hindering readability.

I'm fine with either `waitFor` or `waitForOne`, I'd just like to reduce the 100-times-over-repeated `{interval: 1}`.

So yeah, still relevant, but something I'll probably have to redo after the prettier PR :)

2023-09-14 14:55 UTC, phryneas commented
At this point, I guess this has lost relevance as the new testing style mostly works without `waitFor`. I'm closing this.

2023-09-14 14:55 UTC, closed without merging