docs: adds `useBackgroundQuery` and `useReadQuery` docs
apollographql/apollo-client pull request #10880
Opened 2023-05-15 20:28 UTC by alessbell

Closes https://github.com/apollographql/apollo-client/issues/10874.

### Checklist:

- [ ] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2023-05-15 20:29 UTC, alessbell commented on docs/source/api/react/hooks-experimental.mdx
> +Beginning with version `3.8.0-alpha.0`, Apollo Client Web has alpha support for the `useSuspenseQuery_experimental` hook, which works with React's [Suspense](https://react.dev/reference/react/Suspens
Docs are out of beta 🎉

2023-05-15 20:40 UTC, alessbell commented on docs/source/api/react/hooks-experimental.mdx
> +## `useBackgroundQuery_experimental` and `useReadQuery_experimental`
NB: we haven't had a hook graduate from experimental to the big leagues yet - at least since adding this page to the docs! When that happens, we should:

- remove `experimental` from named export and docs
- cut + paste into `docs/source/api/react/hooks.mdx`
- add a redirect in `docs/source/_redirects`, e.g. `/docs/react/api/react/hooks-experimental/#usefragment_experimental /docs/react/api/react/hooks/#usefragment`

2023-05-15 20:40 UTC, alessbell commented on docs/shared/useSuspenseQuery-result.mdx
> +Calling this function will cause the component to re-suspend, , unless the call site is wrapped in [`startTransition`](https://react.dev/reference/react/startTransition).
`suspensePolicy` has been deprecated

2023-05-15 20:40 UTC, alessbell commented on docs/shared/useSuspenseQuery-result.mdx
> +###### `networkStatus`
If this was intentionally omitted, just lmk and I'll remove

2023-05-15 20:42 UTC, alessbell commented on docs/shared/useSuspenseQuery-options.mdx
> +###### `context`
The diff here presents these changes in a bit of a confusing way, so to summarize:

- removed deprecated options `suspensePolicy` and `nextFetchPolicy`
- added `canonizeResults` and `refetchWritePolicy`

2023-05-15 20:45 UTC, alessbell commented on docs/shared/useSuspenseQuery-result.mdx
> +**Client**
The section header above a section containing only `client` was `Network info` which seemed off - `client` didn't fit in any of the other existing groupings so I renamed this to avoid confusion

2023-05-17 17:16 UTC, jerelmiller requested changes
Spotted a few typos and had some small suggestions for some areas. Thanks for putting this together!

2023-05-17 17:16 UTC, jerelmiller commented on docs/shared/useSuspenseQuery-options.mdx
> +The default value is `""overwrite`.
```suggestion
The default value is `overwrite`.
```

```suggestion
The default value is `"overwrite"`.
```

Spotted a typo. Not sure whether to drop the quotes completely or not, so pick the suggestion that makes the most sense.

2023-05-17 17:16 UTC, jerelmiller commented on docs/shared/useSuspenseQuery-result.mdx
> +###### `networkStatus`
Not intentionally omitted. This field was added after the initial write-up of these docs and I just forgot to come back and update this.

2023-05-17 17:16 UTC, jerelmiller commented on docs/shared/useSuspenseQuery-result.mdx
> +Calling this function will cause the component to re-suspend, , unless the call site is wrapped in [`startTransition`](https://react.dev/reference/react/startTransition).
Thanks!

2023-05-17 17:16 UTC, jerelmiller commented on docs/source/api/react/hooks-experimental.mdx
> +## `useBackgroundQuery_experimental` and `useReadQuery_experimental`
Good call! I think our PR to shift from `alpha` -> `beta` will be dropping the `_experimental` suffix, so let's make this part of that planned work.

2023-05-17 17:16 UTC, jerelmiller commented on docs/source/api/react/hooks-experimental.mdx
> +Beginning with version `3.8.0-alpha.14`, Apollo Client Web has alpha support for the `useBackgroundQuery_experimental` and `useReadQuery_experimental` hooks, which work with React's [Suspense](https:
```suggestion
Beginning with version `3.8.0-alpha.14`, Apollo Client has alpha support for the `useBackgroundQuery_experimental` and `useReadQuery_experimental` hooks, which work with React's [Suspense](https://react.dev/reference/react/Suspense) feature. You can install it via `npm install @apollo/client@alpha`.
```

Based on the conversation in #10885, let's drop "Web" here.

2023-05-17 17:16 UTC, jerelmiller commented on docs/source/api/react/hooks-experimental.mdx
> +`useBackgroundQuery_experimental` allows a user to initiate a query outside of the component that will read and render the data with `useReadQuery_experimental`, which triggers the nearest Suspense b
```suggestion
`useBackgroundQuery_experimental` allows a user to initiate a query outside of the component that will read and render the data with `useReadQuery_experimental`, which triggers the nearest Suspense boundary while the query is pending. This means a query can be initiated higher up in the React render tree and your application can begin requesting data before the component that has a dependency on that data begins rendering.
```

Treat `data` as singular?

2023-05-17 17:16 UTC, jerelmiller commented on docs/source/api/react/hooks-experimental.mdx
> +Ensure the component tree is wrapped with React's [`Suspense`](https://react.dev/reference/react/Suspense) component. Note that the `useReadQuery_experimental` hook returns only `data` and `error` (a
```suggestion
Ensure the component tree that uses is wrapped with React's [`Suspense`](https://react.dev/reference/react/Suspense) component. Note that the `useReadQuery_experimental` hook returns only `data`, `error`, and `networkStatus` (though it should rarely be needed). Since Suspense provides the tools to manage our application's loading states, `useReadQuery_experimental` does not return a `loading` boolean.
```

2023-05-17 17:16 UTC, jerelmiller commented on docs/source/api/react/hooks-experimental.mdx
> +        <Suspense fallback={<SuspenseFallback />}>
I think we should move this suspense boundary to wrap `Child` instead. This will be the dominant pattern here and the one we'd recommend. Check out how [`Relay`](https://relay.dev/docs/api-reference/use-preloaded-query/) structures this with their hooks.

2023-05-17 17:16 UTC, jerelmiller commented on docs/source/api/react/hooks-experimental.mdx
> +  return <Child queryRef={queryRef} />;
```suggestion
  return (
    <Suspense fallback={<SuspenseFallback />}>
      <Child queryRef={queryRef} />
    </Suspense>
  );
```

As mentioned in the other comment, let's move the suspense boundary here.

2023-05-17 17:16 UTC, jerelmiller commented on docs/source/api/react/hooks-experimental.mdx
> +  query: query: DocumentNode | TypedDocumentNode<TData, TVariables>,,
```suggestion
  query: query: DocumentNode | TypedDocumentNode<TData, TVariables>,
```

2023-05-17 17:16 UTC, jerelmiller commented on docs/source/api/react/hooks-experimental.mdx
> +| `queryRef` | QueryReference | An instance of the `QueryReference` class that was generated via `useBackgroundQuery`. |
```suggestion
| `queryRef` | QueryReference | The [`queryRef`](#queryref) that was generated via `useBackgroundQuery`. |
```

While `QueryReference` is technically a class, a user shouldn't need to care what its construct is, just that its of type `QueryReference` and that you get it from `useBackgroundQuery`. In that case, I think we can drop the "instance of class" part from this description. I think it would also be nice to link back to the value returned from higher in the docs.

2023-05-17 17:31 UTC, alessbell commented on docs/source/api/react/hooks-experimental.mdx
> +| `queryRef` | QueryReference | An instance of the `QueryReference` class that was generated via `useBackgroundQuery`. |
🙌

2023-05-17 17:42 UTC, alessbell commented on docs/shared/useBackgroundQuery-result.mdx
> +In order to link a query initiated by a specific `useBackgroundQuery` call to the place its data are consumed—which can be uniquely identified not only by the query and variables passed, but also the
> I typically see "data is" (treating data like a singular noun) rather than "data are"

Haha, you're not wrong! I hear both ("data" being the plural of "datum" is why some say "are"), but I'm good with "is" :)

2023-05-17 17:45 UTC, jerelmiller commented on docs/shared/useBackgroundQuery-result.mdx
> +In order to link a query initiated by a specific `useBackgroundQuery` call to the place its data are consumed—which can be uniquely identified not only by the query and variables passed, but also the
FWIW ChatGPT says:

> The phrase "data is" is more commonly used in contemporary English. While "data" is technically a plural noun, it has become widely accepted to treat it as a singular noun in everyday usage. However, in more formal or technical contexts, you may still encounter "data are" being used to emphasize its plural nature.

2023-05-17 17:50 UTC, alessbell commented on docs/shared/useBackgroundQuery-result.mdx
> +In order to link a query initiated by a specific `useBackgroundQuery` call to the place its data are consumed—which can be uniquely identified not only by the query and variables passed, but also the
https://digitalblog.ons.gov.uk/2016/12/08/data-is-versus-data-are/#:~:text=The%20grammatically%20correct%20approach%20is,the%20latin%20word%20'datum'.

2023-05-17 19:07 UTC, alessbell commented on docs/source/api/react/hooks-experimental.mdx
> +  return <Child queryRef={queryRef} />;
[ace3bbc](https://github.com/apollographql/apollo-client/pull/10880/commits/ace3bbc74b09183578e46262d0c35752f8da3041)

2023-05-17 19:07 UTC, alessbell commented on docs/source/api/react/hooks-experimental.mdx
> +        <Suspense fallback={<SuspenseFallback />}>
[ace3bbc](https://github.com/apollographql/apollo-client/pull/10880/commits/ace3bbc74b09183578e46262d0c35752f8da3041)

2023-05-17 19:08 UTC, alessbell commented on docs/source/api/react/hooks-experimental.mdx
> +Ensure the component tree is wrapped with React's [`Suspense`](https://react.dev/reference/react/Suspense) component. Note that the `useReadQuery_experimental` hook returns only `data` and `error` (a
Seems like that's what was intended, updated: [ace3bbc](https://github.com/apollographql/apollo-client/pull/10880/commits/ace3bbc74b09183578e46262d0c35752f8da3041)

2023-05-17 19:09 UTC, jerelmiller commented on docs/source/api/react/hooks-experimental.mdx
> +Ensure the component tree is wrapped with React's [`Suspense`](https://react.dev/reference/react/Suspense) component. Note that the `useReadQuery_experimental` hook returns only `data` and `error` (a
I like the update you made here. Looks great!

2023-05-17 19:10 UTC, alessbell commented
Back-to-back docs PRs, thanks for another review here @jerelmiller! This one should be good to go 🙌

2023-05-17 19:14 UTC, jerelmiller commented on docs/source/api/react/hooks-experimental.mdx
> +      </ErrorBoundary>
```suggestion
      <ErrorBoundary fallback={<div>Error</div>}>
        <Parent />
      </ErrorBoundary>
```

Looks like this was nudged over a tad far

2023-05-17 19:16 UTC, jerelmiller approved these changes
Looks 💯 🔥 🔥 🔥 . Thanks for putting this together!

2023-05-17 19:18 UTC, alessbell commented on docs/source/api/react/hooks-experimental.mdx
> +      </ErrorBoundary>
Good catch, added one other formatting fix in [6ea0990](https://github.com/apollographql/apollo-client/pull/10880/commits/6ea099042bd71b3ebef98f0f97838707ef517bcd)

2023-05-17 19:25 UTC, merged