Added 'Customizing Type Policies' Segment in cache-configuration.mdx #10933
apollographql/apollo-client pull request #10967
Opened 2023-06-12 08:01 UTC by sahilmanchanda1999

Changes are implemented in the following doc.
https://github.com/apollographql/apollo-client/blob/main/docs/source/caching/cache-configuration.mdx

### Checklist:

- [ ] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2023-06-12 16:02 UTC, jerelmiller requested changes
Hey @sahilmanchanda1999 👋 

Thanks so much for the PR! I've included some suggestions for you. Would you mind taking a look? We'd love to get this merged. Thanks so much!!!

2023-06-12 16:02 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +});
A few things about this code snippet:

1) `addTypePolicy` doesn't exist on `client` directly. You'll need to add it through the `policies` field on the `cache`. This method is also plural: `cache.policies.addTypePolicies(...)`
2) Defining new type policies uses the same format you do when initially defining them in the `InMemoryCache` constructor. In other words, the keys of the object should be the `__typename` and the value is where you define `fields`. There is no `type` field in the configuration. This allows you to define multiple type policies at the same time together.
3) For TypeScript users, I'd recommend an example where you call this on the `cache` variable directly, rather than going through `client`. The `cache` property on `client` is a generic `ApolloCache` type, but `policies` is specific to `InMemoryCache`. If you try and access `client.cache.policies`, you'll get a TypeScript error.

If you'd like a good high-level look at this API, I'd recommend checking out the [tests](https://github.com/apollographql/apollo-client/blob/772cfa3cb563dccee878177e58c8250c4e5b5013/src/cache/inmemory/__tests__/policies.ts#L463-L471).

Here are those suggestions altogether:

```suggestion
cache.policies.addTypePolicies({
  Query: {
    fields: {
      hello: {
        resolver: () => "Hello, world!",
      },
    },
  },
});
```

2023-06-20 17:01 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +Overall, the code sets up caching behaviors for the `Person` type, ensuring that default values are provided for the `name` and `email` fields if they are not present in the cache.
@StephenBarlow would you mind taking a look at this section and provide any suggestions you may have?

2023-09-14 13:49 UTC, phryneas commented
Since we got another question for this in #11218, I'm going to merge this now - thanks a lot for the PR!

@Meschreiber It would be great if you could take a look at this anyways - if you have wording suggestions, we can still do another PR to get those in :)

2023-09-14 13:50 UTC, phryneas approved these changes

2023-09-14 13:50 UTC, merged