Update warning message when discarding unmergeable cache
apollographql/apollo-client pull request #10998
Opened 2023-06-21 02:08 UTC by forresty

@phryneas 

as discussed in https://github.com/apollographql/apollo-client/issues/10992,

updating the warning message to mention the possibility of infinite loops

As this only updates the warning message, probably no changeset is required?

### Checklist:

- [ ] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2023-06-21 02:08 UTC, apollo-cla commented
@forresty: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2023-06-29 03:06 UTC, bignimbus commented
Thanks @forresty! We'll try to get this reviewed as soon as we can.  Thanks for asking RE: Changesets, I think since this is library code we should include one

2023-06-29 17:05 UTC, jerelmiller requested changes
This addition is great! Take a look at my comment and let me know what you think!

2023-06-29 17:05 UTC, jerelmiller commented on src/cache/inmemory/writeToStore.ts
> +https://github.com/apollographql/apollo-client/issues/10992
```suggestion
This could cause additional (usually avoidable) network requests to fetch data that were otherwise cached.
```

Couple things here:

* Reading this a few times, the 2nd paragraph makes this problem seem very scary. I actually think your first sentence here is good enough, so lets just remove the 2nd paragraph, especially since there is more than just React that uses the underlying core client.
* Since this is in a template string, newlines are honored, so I pushed this sentence to a single line.

2023-06-29 21:35 UTC, forresty commented on src/cache/inmemory/writeToStore.ts
> +https://github.com/apollographql/apollo-client/issues/10992
> the 2nd paragraph makes this problem seem very scary

Hi @jerelmiller , thanks for the suggestion! I think the previous warning message was not "scary" enough to encourage action ;-)

> especially since there is more than just React that uses the underlying core client

This is a good point. But I believe this is potentially a big problem for (especially new) users to `useQuery`. Should we dynamically detect if the environment is React and conditionally show the line?

Additionally, there are some wonderful comments in the original thread https://github.com/apollographql/apollo-client/issues/10992 by @phryneas , for example

> This is something we should probably highlight more in the docs: that id field is by far not unneccessary - it is one of the core features of Apollo Client, and you should add it always, and everywhere, if the entity has one.

And I think my [reproduction on codesandbox ](https://codesandbox.io/s/festive-carlos-m7v5jd) would be helpful for users to better understand the problem as well. Should we keep the link to the GitHub issue?

2023-06-30 09:35 UTC, phryneas commented on src/cache/inmemory/writeToStore.ts
> +https://github.com/apollographql/apollo-client/issues/10992
>  Hi @jerelmiller , thanks for the suggestion! I think the previous warning message was not "scary" enough to encourage action ;-)

Tbh., I'd say that *any* 5-line-long very-in-depth error message should encourage enough action. 
We could make it scary, we could add a screen shake and red flashing CSS to the website it comes from, at some point it is the responsibility of the end developer to care and read the linked sources.  
No matter what we do, some people will ignore it. 
I'm a bit afraid of making this message too scary, since there is a balance after which people will get too afraid to touch anything - or start ignoring all other error messages that are similarly important, but less scary.

So in terms of balance, I think "additional network requests" is probably enough, and a developer that would actually see an infinite render loop (and a network request for each render) should be able to connect the dots here, especially as this message gets logged for each of these rerenders, so their console will be full of it.

> Additionally, there are some wonderful comments in the original thread https://github.com/apollographql/apollo-client/issues/10992 by @phryneas , for example

These would probably make more sense in the linked docs pages than in the error message itself.

I am also thinking of adding a test along the lines of "did we already see this __typename in the past, but with an `id` field" and adding a separate error message for that. We cannot detect that an entity type has an `id` field, because we don't know the Schema - but we can remember that in the past an entity had an `id` field and infer that it should always have one.

2023-06-30 10:16 UTC, forresty commented on src/cache/inmemory/writeToStore.ts
> +https://github.com/apollographql/apollo-client/issues/10992
> So in terms of balance, I think "additional network requests" is probably enough, and a developer that would actually see an infinite render loop (and a network request for each render) should be able to connect the dots here

Thanks @phryneas, This makes perfect sense. I think the problem with the original message is, for new users who don't yet fully understand the importance of cache and its role (essentially a messaging backbone, not just a cache), it is not obvious what's the potential consequences of cache lost. By adding "additional network requests", it should be enough to hint the possibility of infinite loop of requests.

> These would probably make more sense in the linked docs pages than in the error message itself.

agree.

> We cannot detect that an entity type has an id field, because we don't know the Schema - but we can remember that in the past an entity had an id field and infer that it should always have one.

this would be great, love to see this happen! I remember @adamesque mentioned cycle detection could help, but it seems your solution would achieve similar result, and probably is a simpler and more elegant way to mitigate the issue.

2023-06-30 10:19 UTC, forresty commented on src/cache/inmemory/writeToStore.ts
> +https://github.com/apollographql/apollo-client/issues/10992
committed the suggestion, let me know if any other changes are prefered before we merge this, thanks!

2023-06-30 11:59 UTC, phryneas approved these changes
Let's get this merged :)

2023-06-30 12:22 UTC, merged