`QueryReference`: check for `resolve`/`reject`
apollographql/apollo-client pull request #10999
Opened 2023-06-21 08:34 UTC by phryneas

This came up in [this Discord message](https://discord.com/channels/1022972389463687228/1120746279849443439/1120746279849443439)

![image](https://github.com/apollographql/apollo-client/assets/4282439/8f8cf959-e66e-4aa9-ad24-2f38a7814cd1)

### Checklist:

- [x] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2023-06-21 15:40 UTC, jerelmiller requested changes
The change looks great, but would love to see a test to ensure we don't introduce regressions later. Thanks!

2023-06-22 08:30 UTC, phryneas commented on src/react/cache/QueryReference.ts
I can try. I have to admit I didn't have enough context on how to potentially trigger this.

2023-06-22 08:30 UTC, phryneas commented
/release:pr

2023-06-23 16:21 UTC, jerelmiller approved these changes
🎉

2023-06-23 16:21 UTC, merged