[In progress] Add Suspense page to docs
apollographql/apollo-client pull request #11098
Opened 2023-07-25 21:17 UTC by alessbell

Closes https://github.com/apollographql/apollo-client/issues/10995.

In progress:
- [ ] error handling/`errorPolicy` example
- [ ] `queryKey` example
- [ ] `useDeferredValue` example
- [ ] `refetch`/`fetchMore` example

### Checklist:

- [x] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

2023-07-26 11:26 UTC, phryneas reviewed
This already reads very cool! :)

2023-07-26 11:26 UTC, phryneas commented on docs/source/api/react/suspense.mdx
> +The `Dog` component **does not suspend** while this request is being made. This is because we've opted to render partial data _instead_ of suspending by setting `returnPartialData: true`. Once the ne
Question from reading this: is "no data at all" "partial data" too? Might need to be more specific here.

2023-07-26 13:51 UTC, Meschreiber commented on docs/source/api/react/suspense.mdx
> +description: Using React 18 concurrent features with Apollo Client
Alas, I have not read all the client docs (yet), so am not the most informed on this question.

That said, I would keep the "Fetching" name for that section because: 1)  It (and its sibling sections, "Caching," "Networking," are logical and familiar categories devs will look for, and 2) to keep consistent with other client docs.

In terms of placement of this doc, API Ref > React makes sense to me. I think it's ok that this has a little more explanation text than the usual reference doc.

2023-07-26 13:52 UTC, Meschreiber commented on docs/source/api/react/suspense.mdx
> +      <Dog name="Mozzarella" />
What a great name for a dog! (Then again, I do have a cat named Nacho. 😆)

2023-07-28 08:18 UTC, phryneas commented on docs/source/api/react/suspense.mdx
> +description: Using React 18 concurrent features with Apollo Client
I want to really challenge the placement in "API Ref" here.

As a developer, I will look at the API Ref if I want to know details about a specific option, or explanation of a call signature, but not for an explanation what something does. If we want to add more info there, we would have to reconsider the naming "API Ref" to make things discoverable.

This page is a wonderful tutorial, but if we stick it into the "API Reference" section it does not get the visibility it deserves - going forward, these hooks are more important than `useQuery` and could probably at some point even remove the "Fetching" heading.

Suggestion: Maybe rename this page to "Fetching with Suspense" and put it directly under "Fetching"?

2023-07-28 13:53 UTC, alessbell commented on docs/source/api/react/suspense.mdx
> +description: Using React 18 concurrent features with Apollo Client
Yes, totally agree @phryneas.

This was updated in https://github.com/apollographql/apollo-client/pull/11098/commits/6471431b5f174296503955e184e7d6d8a78d17c8: the page now appears between Queries and Mutations under Fetching. I also chatted with @jerelmiller about this and we realized this order makes sense in the progression of these pages which go from querying to updating data. Thanks all!

![CleanShot 2023-07-28 at 09 51 32](https://github.com/apollographql/apollo-client/assets/5139846/06112290-11e1-4980-a42b-799e79c52164)

2023-08-03 22:11 UTC, jerelmiller requested changes
This is a REALLY great start to this doc. As I said in person, don't let my review intimidate. It has no reflection on the quality of this doc or the content you've put in here. I'm a bit of a perfectionist at times so I provided lots of suggestions and things to think about. As always, take/leave whatever makes sense here.

I'd be happy to approve once you've had a chance to read through my suggestions, make changes/comments, etc.

2023-08-03 22:11 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +## Using Apollo Client's Suspense Hooks with Next.js's App Router
To leave room for the future, should we consider making this section a bit more generic and having `Next.js` be a subsection of this one?

---

```suggestion
## React Server Components (RSC)

### Usage with Next.js 13 App Router
```

Thoughts? totally cool if we wait to make this change as well since we don't have another entry at the moment.

2023-08-03 22:12 UTC, jerelmiller requested changes
This is a REALLY great start to this doc. As I said in person, don't let my review intimidate. It has no reflection on the quality of this doc or the content you've put in here. I'm a bit of a perfectionist at times so I provided lots of suggestions and things to think about. As always, take/leave whatever makes sense here.

I'd be happy to approve once you've had a chance to read through my suggestions, make changes/comments, etc.

2023-08-04 12:21 UTC, alessbell commented on docs/source/data/queries.mdx
> +> **Note:** in Apollo Client >= v3.8, data fetching hooks `useSuspenseQuery` and `useBackgroundQuery` are available for querying data within `<Suspense />` boundaries using React 18's new concurrent
Sure, standardizing makes sense. Updated.

2023-08-04 12:24 UTC, alessbell commented on docs/source/data/suspense.mdx
> +In this guide, we'll look at Apollo Client's new data fetching hooks introduced in v3.8—specifically `useSuspenseQuery`, `useBackgroundQuery` and `useReadQuery`—which leverage React's powerful concur
👍 made a slightly different edit that also captures this

2023-08-04 12:27 UTC, alessbell commented on docs/source/data/suspense.mdx
> +}
Yeah fair point, this was based off of an existing example and I wanted to show the dog's name up front while there also aren't that many fields on `Dog`, I'll search by `id` instead.

2023-08-04 12:29 UTC, alessbell commented on docs/source/data/suspense.mdx
> +In this example, our `App` component renders a `Dog` component which fetches the record for a single dog via `useSuspenseQuery`. When React attempts to render `Dog` for the first time, Apollo's `InMe
Hmm, I think I'll leave this one as is: with the default fetch policy, this data is cached so I think it's useful to indicate that.

2023-08-04 12:29 UTC, phryneas commented on docs/source/data/suspense.mdx
> +`useSuspenseQuery` initiates a network request and causes the component calling it to suspend while the request is in flight. It can be thought of as a drop-in replacement for `useQuery` that allows
"suspenseful replacement" or "suspense-ready replacement" instead of "drop-in-replacement"?

2023-08-04 12:31 UTC, alessbell commented on docs/source/data/suspense.mdx
> +In the previous example, we fetched the record for a single dog by passing a hard-coded `name` variable, Mozzarella, to `useSuspenseQuery`. Now, let's say we want to fetch the record for a different
I'll admit my personal preference is definitely for the way I wrote it - `a single dog record` reads strange to me - but maybe @Meschreiber has suggestions here :)

2023-08-04 12:34 UTC, alessbell commented on docs/source/data/suspense.mdx
> +`useSuspenseQuery` initiates a network request and causes the component calling it to suspend while the request is in flight. It can be thought of as a drop-in replacement for `useQuery` that allows
I really like that @phryneas - updated

2023-08-04 12:36 UTC, phryneas commented on docs/source/data/suspense.mdx
> +}
Maybe an easier change: query for `age` or `nickname`.

2023-08-04 12:40 UTC, alessbell commented on docs/source/data/suspense.mdx
> +function Dog({ name }: { name: string }) {
👍 Updated

2023-08-04 12:52 UTC, alessbell commented on docs/source/data/suspense.mdx
> +interface Data {
Updated

2023-08-04 12:59 UTC, alessbell commented
Oh man... I appreciate the comments, but TIL GitHub becomes unusable with this many 🤣

If there are any checks running while I'm on the page, once one completes it auto-focuses the comment box on the last conversation thread so the page jumps around and I lose my place constantly (just happened again 😅), and if I ever refresh it means I have to click "show more comments" about ten times before I can get back to where I was.

Doing my best to read these inline using an IDE plugin but unfortunately the formatting isn't great. Doing my absolute best to have this re-reviewable shortly!

2023-08-04 13:07 UTC, alessbell commented on docs/source/data/suspense.mdx
Updated description

2023-08-04 13:09 UTC, alessbell commented on docs/source/data/suspense.mdx
> +  return (
Updated everywhere

2023-08-04 13:12 UTC, alessbell commented on docs/source/data/suspense.mdx
> +function App() {
Updated

2023-08-04 13:17 UTC, alessbell commented on docs/source/data/suspense.mdx
> +`useBackgroundQuery` initiates a request for data in a parent component and returns a `QueryReference` which is used to read the data in a child component via `useReadQuery`. If the child component a
👍 made some updates here

2023-08-04 13:22 UTC, alessbell commented on docs/source/data/suspense.mdx
> +Changing the dog via the `select` will cause the component to suspend each time we select a dog whose record **does not yet exist in the cache**. Once we've loaded a given dog's record into Apollo Cl
Good point - believe we also do this in the fragment docs (use InMemoryCache as the shorthand reference for the cache since it's the most common case)

2023-08-04 13:47 UTC, alessbell commented on docs/source/data/suspense.mdx
> +In the concurrent React paradigm, errors thrown in React components are caught and displayed by the closest [error boundary](https://react.dev/reference/react/Component#static-getderivedstatefromerro
Slightly tweaked this to make it clear that it's only when using streaming server rendering APIs, not just SSR in general.

2023-08-04 14:24 UTC, alessbell commented
Think this is ready for a final look @jerelmiller - I've done my best using my VSCode integration which is also quite difficult to work with unfortunately.

Spent the last couple of hours trying to read/edit between the comments, and once I make changes the plugin has trouble moving the comments around with all the outdated line references as the length of the document changes... sometimes it pins the comment to a past commit, but then it takes me to an old version of the document to even read those comments and I can see I've already fixed them (the mark as resolved button doesn't always work)... There may be some that are not addressed but hopefully I've gotten all the big ones!

![CleanShot 2023-08-04 at 10 16 35](https://github.com/apollographql/apollo-client/assets/5139846/c1bbc1e1-fdfe-428e-af59-d46adec35a08)

2023-08-04 20:53 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +`useSuspenseQuery` initiates a network request and causes the component calling it to suspend while the request is in flight. It can be thought of as a drop-in replacement for `useQuery` that allows
Ya I like that a lot!

2023-08-04 20:55 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +`useSuspenseQuery` initiates a network request and causes the component calling it to suspend while the request is being made. It can be thought of as a Suspense-ready replacement for `useQuery` that
```suggestion
`useSuspenseQuery` initiates a network request and causes the component calling it to suspend while the request is made. It can be thought of as a Suspense-ready replacement for `useQuery` that allows you to take advantage of React's Suspense features while fetching during render.
```

2023-08-04 20:57 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +      # properly cached.
Super weird. This shows up aligned in this doc, but looking at the preview, the comments are outdented too far.

<img width="640" alt="Screenshot 2023-08-04 at 2 56 48 PM" src="https://github.com/apollographql/apollo-client/assets/565661/8379de43-0f4d-497c-ac3d-75eb30757531">

Maybe there is a tab vs space or something in here?

2023-08-04 21:00 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +> **Note:** a component using `useSuspenseQuery` to fetch data will **suspend on first render** unless it can access all of the data for the fields it is querying via the cache (or is configured with
Love the updates you made here. Thanks!

2023-08-04 21:03 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +In this example, our `App` component renders a `Dog` component which fetches the record for a single dog via `useSuspenseQuery`. When React attempts to render `Dog` for the first time, the cache is e
```suggestion
In this example, our `App` component renders a `Dog` component which fetches the record for a single dog via `useSuspenseQuery`. When React attempts to render `Dog` for the first time, the cache is empty so `useSuspenseQuery` initiates a network request. `Dog` suspends while the network request is pending, triggering the nearest Suspense boundary _above_ the suspended component in `App` which renders our "Loading..." fallback. Once the network request is complete, `Dog` renders with the newly cached `name` for Mozzarella the Corgi.
```

2023-08-04 21:09 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +> **Note for TypeScript users**: since `GET_DOG_QUERY` is a `TypedDocumentNode` in which we have specified the result type via `Data` generic, the TypeScript type for `data` returned by `useSuspenseQ
```suggestion
> **Note for TypeScript users**: since `GET_DOG_QUERY` is a `TypedDocumentNode` in which we have specified the result type via `Data` generic argument, the TypeScript type for `data` returned by `useSuspenseQuery` reflects that! This means that `data` is guaranteed to be defined when `Dog` renders, and that `data.dog` will have the shape `{ id: string; name: string; breed: string; }`.
```

Saw this thread the other day and this made me think of this 🤣 https://twitter.com/mattpocockuk/status/1682030938790985736?s=20

2023-08-04 21:13 UTC, alessbell commented on docs/source/data/suspense.mdx
> +      # properly cached.
much better :)

![CleanShot 2023-08-04 at 17 12 47](https://github.com/apollographql/apollo-client/assets/5139846/c4ccc694-3816-48a1-9a7c-f35b3eebecc4)

2023-08-04 21:37 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +In this example, our `App` component renders a `Dog` component which fetches the record for a single dog via `useSuspenseQuery`. When React attempts to render `Dog` for the first time, the cache is e
```suggestion
In this example, our `App` component renders a `Dog` component which fetches the record for a single dog via `useSuspenseQuery`. When React attempts to render `Dog` for the first time, the cache is unable to fulfill the request for the `GetDog` query, so `useSuspenseQuery` initiates a network request. `Dog` suspends while the network request is pending, triggering the nearest `Suspense` boundary _above_ the suspended component in `App` which renders our "Loading..." fallback. Once the network request is complete, `Dog` renders with the newly cached `name` for Mozzarella the Corgi.
```

I would avoid saying that the cache is "empty" here and gear it more towards the fact the cache can't fulfill the data required for the query. In this way, it alludes to the fact that the cache can have other data in it, it just doesn't have enough to fulfill the request, so it suspends. Saying its "empty" might confuse someone who thinks that this is a precondition for suspense to work.

2023-08-04 21:42 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +You may have noticed that `useSuspenseQuery` does not return a `loading` boolean: this is because the component calling `useSuspenseQuery` will always suspend when fetching data. A corollary is that
Looking over this again, it sticks out too much so ignore this suggestion.

2023-08-04 21:42 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +You may have noticed that `useSuspenseQuery` does not return a `loading` boolean: this is because the component calling `useSuspenseQuery` will always suspend when fetching data. A corollary is that
Meh, reading this again a day later doesn't seem like it adds much value. Ignore this one.

2023-08-04 21:43 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +You may have noticed that `useSuspenseQuery` does not return a `loading` boolean: this is because the component calling `useSuspenseQuery` will always suspend when fetching data. A corollary is that
I like the edits that were made to this section, so I don't feel like this suggestion applies anymore. Ignore.

2023-08-04 21:43 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +You may have noticed that `useSuspenseQuery` does not return a `loading` boolean: this is because the component calling `useSuspenseQuery` will always suspend when fetching data. A corollary is that
Looks like this was addressed. Thanks!

2023-08-04 21:44 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +> **Note for TypeScript users**: since `GET_DOG_QUERY` is a `TypedDocumentNode` in which we have specified the result type via `Data` generic, the TypeScript type for `data` returned by `useSuspenseQ
Everything reads pretty nicely and after coming back to this suggestion with the codegen mention in place, I'm happy with where this ended up.

2023-08-04 21:46 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +In the previous example, we fetched the record for a single dog by passing a hard-coded `name` variable, Mozzarella, to `useSuspenseQuery`. Now, let's say we want to fetch the record for a different
Ya you're right. Reading my suggestion a day later, I could take or leave the part about "Let's update our example". I'll leave this for now.

2023-08-04 21:46 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +In the previous example, we fetched the record for a single dog by passing a hard-coded `id` variable, Mozzarella, to `useSuspenseQuery`. Now, let's say we want to fetch the record for a different do
```suggestion
In the previous example, we fetched the record for a single dog by passing a hard-coded `id` variable, Mozzarella, to `useSuspenseQuery`. Now, let's say we want to fetch the record for a different dog using a dynamic value. We'll fetch the list of dogs with just their `name` and `id`, and once the user selects an individual dog we can fetch more details, including their `breed`.
```

I think making this a touch more concise makes this read a little bit nicer.

2023-08-04 21:49 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +Let's take a look at some code:
```suggestion
Let's update our example:
```

I like to think of us as guiding the user in their own editor through these examples. Rather than merely "looking" at code, I like telling the user to update the example. This is especially useful since you provided the codesandbox link above to follow along.

2023-08-04 21:51 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +Changing the dog via the `select` will cause the component to suspend each time we select a dog whose record **does not yet exist in the cache**. Once we've loaded a given dog's record into Apollo Cl
Coming back to this, I'll leave this for now and we can edit if @Meschreiber prefers something different 🙂

2023-08-04 21:52 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +Changing the dog via the `select` will cause the component to suspend each time we select a dog whose record **does not yet exist in the cache**. Once we've loaded a given dog's record into Apollo Cl
I like the edits made here. Thanks!

2023-08-04 21:56 UTC, alessbell commented on docs/source/data/suspense.mdx
> +Let's take a look at some code:
Nice, I really like the impact of this subtle change 👍

2023-08-04 21:57 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +While we may sometimes want to suspend while we update some state that results in a pending network request, there are many cases when we would prefer to keep displaying the previous render while Rea
```suggestion
There are times that we want to avoid showing the loading UI in response to a pending network request and instead prefer to maintain the already rendered content. We can use a _transition_ to mark our update as non-urgent, which tells React to keep the existing UI in place until the new data has finished loading.
```

I went spelunking in the suspense docs and I actually didn't find mention of the word "background". This suggestion updates this to more align with the [suspense docs](https://react.dev/reference/react/Suspense) and the language used there. See if you like this edit.

2023-08-04 21:59 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +In these cases, we can use a pair of React APIs that allow us to update state without suspending: [`startTransition`](https://react.dev/reference/react/startTransition)/[`useTransition`](https://reac
```suggestion
To mark a state update as a transition, we use the [`startTransition`](https://react.dev/reference/react/startTransition) function from React.

> For a deep-dive into these APIs, see the linked React documentation for a full set of usage examples and caveats.
```

To more align with the verbiage in the suspense docs, I think simplifying it to this makes sense and moving the mention of React documentation to a block quote. Let me know if you like this change.

2023-08-04 21:59 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +Let's modify our code so that the previously displayed dog remains on the screen while the next one is fetched in the background:
```suggestion
Let's modify our example so that the previously displayed dog remains on the screen while the next one is fetched in the background:
```

Update to keep with the theme of "the example"

2023-08-04 22:04 UTC, alessbell commented on docs/source/data/suspense.mdx
> +While we may sometimes want to suspend while we update some state that results in a pending network request, there are many cases when we would prefer to keep displaying the previous render while Rea
Yeah good call, just made some tiny adjustments and added a link to the blog post about transitions since that gives the best high level overview if anyone wants to read more.

2023-08-04 22:04 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +  const [isPending, startTransition] = useTransition();
I love that you updated this to include this bit about `useTranstion`. Re-reading this, I think this would flow a bit better by moving this example right under the "[Updating state without suspending](https://deploy-preview-11098--apollo-client-docs.netlify.app/data/suspense/#updating-state-without-suspending)" section.

Here was my previous suggestion on moving this section up a touch:

---

### Showing pending UI during a transition

In the previous example, there is no visual indication that a fetch is happening when a new dog is selected. To provide nice visual feedback, let's update our example to use React's [`useTransition`](https://react.dev/reference/react/useTransition) hook which gives you an `isPending` boolean value to determine when a transition is happening. We'll dim the select dropdown while the transition is happening.

```tsx
import { useState, Suspense, useTransition } from "react";

function App() {
  const [isPending, startTransition] = useTransition();
  const { data } = useSuspenseQuery(GET_DOGS_QUERY);
  const [selectedDog, setSelectedDog] = useState(data.dogs[0].name);

  return (
    <>
      <select
        style={{ opacity: isPending ? 0.5 : 1 }}
        onChange={(e) => {
          startTransition(() => {
            setSelectedDog(e.target.value);
          });
        }}
      >
        {data.dogs.map((dog) => (
          <option value={dog.name}>{dog.name}</option>
        ))}
      </select>
      <Suspense fallback={<div>Loading...</div>}>
        <Dog name={selectedDog} />
      </Suspense>
    </>
  );
}
```

2023-08-04 22:05 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +
Moved this suggestion to a single comment.

2023-08-04 22:06 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +While we may sometimes want to suspend while we update some state that results in a pending network request, there are many cases when we would prefer to keep displaying the previous render while Rea
Good call. Love it.

2023-08-04 22:11 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +You may want to render your component immediately if partial data is available in the cache without suspending first. To do this, you can use the `returnPartialData` option **combined with one of two
```suggestion
When the cache contains partial data, you may prefer to render that partial data immediately without suspending. To do this, you can use the `returnPartialData` option.

> **Note:** this option only works when combined with either the `cache-first` (default) or `cache-and-network` fetch policy. `cache-only` is not currently supported by `useSuspenseQuery`. For details on these fetch policies, see [Setting a fetch policy](/react/data/queries/#setting-a-fetch-policy).
```

You might consider moving the information about the fetch policy part of a block quote since its secondary information. I'd also combine information from the next block quote into here.

Here is a suggestion as well to re-arrange the sentence slightly which makes the "render immediate" a consequence of having partial data in the cache rather than the other way around. Doing so eliminates the "if" part of this statement.

2023-08-04 22:13 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +Consider how we can adjust our example `App` and `Dog` components to render partial data on first render:
```suggestion
Here's how we adjust our example to render partial data:
```

Since the user is following along, I'd prefer talking about making code modifications rather than just "considering" it.

2023-08-04 22:13 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +> **A note on the `fetchPolicy` option:** when fetching data with Apollo Client's Suspense hooks, the four supported fetch policies are `cache-first` (default), `network-only`, `no-cache` and `cache-
See https://github.com/apollographql/apollo-client/pull/11098/files#r1284880618. If you like that suggestion, you can remove this.

```suggestion
```

2023-08-04 22:15 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +const GET_DOG_QUERY_PARTIAL: TypedDocumentNode = gql`
```suggestion
const GET_PARTIAL_DOG_QUERY: TypedDocumentNode = gql`
```

I tend to prefer this style because "partial" feels more like an adjective to me than a noun. Switching this around makes the dog query the noun instead.

Then again, its a code sample, so not the end of the world if you prefer the way it is 😄

2023-08-04 23:02 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +> **Note:** An error boundary is a **class component** that implements `static getDerivedStateFromError`. If you don't want to write an error boundary class component yourself, you can use a library
After reading this again, I like the way it is.

2023-08-05 00:25 UTC, alessbell commented on docs/source/data/suspense.mdx
> +For more information, see the [`useSuspenseQuery`](../api/react/hooks/#usesuspensequery) or [`useBackgroundQuery`](../api/react/hooks/#usebackgroundquery-and-usereadquery) API docs.
The useBackgroundQuery link is broken here

2023-08-05 00:26 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +For more information, see the [`useSuspenseQuery`](../api/react/hooks/#usesuspensequery) or [`useBackgroundQuery`](../api/react/hooks/#usebackgroundquery-and-usereadquery) API docs.
I can get this fixed :)

2023-08-05 00:29 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +For more information, see the [`useSuspenseQuery`](../api/react/hooks/#usesuspensequery) or [`useBackgroundQuery`](../api/react/hooks/#usebackgroundquery-and-usereadquery) API docs.
[971a802](https://github.com/apollographql/apollo-client/pull/11098/commits/971a802a84ca2e79e94c84786a6a3076a19332d4)

2023-08-05 00:36 UTC, jerelmiller approved these changes
🎉 Looking forward to getting this in the public!

2023-08-05 00:52 UTC, merged