Adds support for `skipToken` in options for `useSuspenseQuery` and `useBackgroundQuery` and soft deprecates `skip` option
apollographql/apollo-client pull request #11112
Opened 2023-07-29 04:52 UTC by jerelmiller

Closes #11093

Adds support for a new `skipToken` sentinel that can be passed as options to `useSuspenseQuery` and `useBackgroundQuery`. This works in place of `skip` for both of these hooks. As such, the `skip` option is now labeled as `deprecated` to nudge people to use this feature, which is generally more type-safe than the `skip` option.

**Breaking change**

This PR also changes the way `queryRef` is returned when `skip` is `true` or `skipToken` is used with `useBackgroundQuery`. Previously, a `queryRef` would always be returned, regardless of whether query execution was skipped. This has been updated to conditionally return a `queryRef` only when query execution is enabled. `undefined` is returned when initializing the hook skipped.

**Before**
```ts
function Parent() {
  const [queryRef] = useBackgroundQuery(query, skip ? skipToken : undefined);
  //      ^? QueryReference<TData | undefined>

  return <Child queryRef={queryRef} />
}

function Child({ queryRef }: { queryRef: QueryReference<TData | undefined> }) {
  const { data } = useReadQuery(queryRef);
}
```

**After**
```ts
function Parent() {
  const [queryRef] = useBackgroundQuery(query, skip ? skipToken : undefined);
  //      ^? QueryReference<TData> | undefined

  return queryRef ? <Child queryRef={queryRef} /> : null;
}

function Child({ queryRef }: { queryRef: QueryReference<TData> }) {
  const { data } = useReadQuery(queryRef);
}
```

### Checklist:

- [x] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

2023-07-29 05:05 UTC, jerelmiller commented on src/react/hooks/index.ts
> -  SubscribeToMoreFunction,
These were accidentally publicly exported. It didn't make much sense to do so as these are just type shortcuts shared between `useSuspenseQuery` and `useBackgroundQuery`. I removed them for now to avoid causing confusion on what they are.

2023-07-29 05:07 UTC, jerelmiller commented on src/react/hooks/useReadQuery.ts
> +import { invariant } from '../../utilities/globals/index.js';
I happened to notice we were importing this function from the wrong place. This has been updated to ensure its using the wrapped version.

2023-07-29 05:09 UTC, jerelmiller commented on src/react/hooks/useBackgroundQuery.ts
> +  return [
There was no reason to `memo` this return tuple since the tuple itself didn't need to be referentially stable, just the items in the tuple itself. Typical usage of this hook will destructure this tuple, so no need to memoize it.

2023-07-31 10:51 UTC, phryneas requested changes

2023-07-31 10:51 UTC, phryneas commented on src/react/hooks/useReadQuery.ts
> +    internalQueryRef.promiseCache.set(key, internalQueryRef.promise);
```suggestion
  if (!promiseCache.has(key)) {
    promiseCache.set(key, internalQueryRef.promise);
```

Is there a real need for this logic?

I think it could make more sense to have a `readQuery` function:

```suggestion
const readQuery = () => promiseCache.get(key) || internalQueryRef.promise
```
and use that instead of `() => promiseCache.get(key)!` down in the `uSES` call.

2023-07-31 10:51 UTC, phryneas commented on src/react/hooks/useSuspenseQuery.ts
> +  const client = useApolloClient(
Same as `useBackgroundQuery` - with a small tweak in the type above we can keep the old code here.

2023-07-31 10:51 UTC, phryneas commented on src/react/types/types.ts
> +   */
```suggestion
   * @deprecated We recommend using `skipToken` in place of the skip option. This
   * is more type-safe in most cases.
   * @example recommended usage of `skipToken`:
   * ```js
   * import { skipToken, useSuspenseQuery } from '@apollo/client';
   *
   * const { data } = useSuspenseQuery(query, id ? { variables: { id } } : skipToken)
   * ```
   */
```

We have a teaching moment here and should use it :)

![image](https://github.com/apollographql/apollo-client/assets/4282439/9da2a1a3-7d28-41c9-8752-1faf44501023)
![image](https://github.com/apollographql/apollo-client/assets/4282439/d539855f-ff46-4ef8-886a-74f7ff02ae4d)

2023-07-31 10:51 UTC, phryneas commented on src/react/types/types.ts
> +   * is more type-safe in most cases.
```suggestion
```suggestion
   * @deprecated We recommend using `skipToken` in place of the skip option. This
   * is more type-safe in most cases.
   * @example recommended usage of `skipToken`:
   * ```js
   * import { skipToken, useBackgroundQuery } from '@apollo/client';
   *
   * const { data } = useBackgroundQuery(query, id ? { variables: { id } } : skipToken)
   * ```
   */
```
```

2023-07-31 10:51 UTC, phryneas commented on src/react/types/types.ts
> +   */
PS: I'm not really happy with the "This is more type-safe in most cases." sentence - could we either skip that or change it to "This is more type-safe."?

2023-07-31 12:59 UTC, phryneas commented on src/react/hooks/index.ts
> +export { skipToken, SkipToken } from './constants.js';
See #11115

2023-07-31 15:23 UTC, jerelmiller commented on src/react/hooks/useBackgroundQuery.ts
> +  QueryReference<TData | undefined>,
See https://github.com/apollographql/apollo-client/pull/11112#discussion_r1279477438 which is intentional because of `errorPolicy`

2023-07-31 15:26 UTC, jerelmiller commented on src/react/hooks/useBackgroundQuery.ts
> +];
I guess it depends on whether we support a case where the user skips unconditionally:

```
useBackgroundQuery(query, skipToken)
```

The return type of this should be `QueryReference<TData> | undefind`, but without this overload, it gets caught up with the `returnPartialData` case and returns `QueryReference<DeepPartial<TData>> | undefined`.

There's a solid case to be made that you should never unconditionally skip your query, but for completeness, I added this.

Thoughts?

2023-07-31 15:29 UTC, alessbell commented on src/react/hooks/index.ts
> -  SubscribeToMoreFunction,
Oops pls disregard, I'm on my phone and thought this was a different file :)

2023-07-31 15:39 UTC, jerelmiller commented on .changeset/early-days-stare.md
> +Adds support for a `skipToken` sentinel that can be used as `options` in `useSuspenseQuery` and `useBackgroundQuery` to skip execution of a query. This works identically to the `skip` option but is m
I like this change with the exception of the last sentence because it sounds too much like a promise that I don't know we would keep. I think the "we are considering" part makes a lot of sense and says plenty. 

Did a small bit of workshopping with this and ended with: [ed10a80](https://github.com/apollographql/apollo-client/pull/11112/commits/ed10a80307d1e38cc7fdcbc749dbd37f08ad54cb)

2023-07-31 15:39 UTC, jerelmiller commented on src/react/hooks/constants.ts
> +export const skipToken = Symbol('skipToken');
Good call

2023-07-31 15:46 UTC, jerelmiller commented on src/react/hooks/useBackgroundQuery.ts
> +    ];
I always forget about the union with `never`. Updated in https://github.com/apollographql/apollo-client/pull/11112/commits/a6529c6c2f3b694ac1ce1eecb933f0c4cf70bc12. Thanks!

2023-07-31 15:56 UTC, jerelmiller commented on src/react/hooks/useReadQuery.ts
> +    internalQueryRef.promiseCache.set(key, internalQueryRef.promise);
I'm a little leery to make this change until we get a few more tests written for `useBackgroundQuery`/`useReadQuery`. Setting the value here is meant to be reflected back to `useBackgroundQuery` where `promiseCache` state actually lives. When calling `refetch` or `fetchMore`, the `promiseCache` is copied to allow React to fork the state for `startTransition` and `useDeferredValue`. This particular `promiseCache.set` is handle when `variables` change and allows us to write the value to the promise cache without the need for an additional `set`. Hopefully that makes sense.

This is tracked in #10879

2023-07-31 16:02 UTC, jerelmiller commented on src/react/hooks/useBackgroundQuery.ts
> +  );
Ah thank you, this is much appreciated. I forget this is _internal_. Fixed in [761f6bd](https://github.com/apollographql/apollo-client/pull/11112/commits/761f6bd27163c23321e8a8bf427f2381f596b4e8)

2023-07-31 16:02 UTC, jerelmiller commented on src/react/hooks/useSuspenseQuery.ts
> +  const client = useApolloClient(
Fixed in [761f6bd](https://github.com/apollographql/apollo-client/pull/11112/commits/761f6bd27163c23321e8a8bf427f2381f596b4e8)

2023-08-01 08:12 UTC, phryneas commented on src/react/hooks/useBackgroundQuery.ts
> +  QueryReference<DeepPartial<TData> | undefined>,
Ah, fair point!

2023-08-01 08:15 UTC, phryneas commented on src/react/hooks/useReadQuery.ts
> +    internalQueryRef.promiseCache.set(key, internalQueryRef.promise);
Okay, then I was just missing a lot of context here :)

What about this suggestion though?

```suggestion
  if (!promiseCache.has(key)) {
   promiseCache.set(key, internalQueryRef.promise);
```

2023-08-01 09:35 UTC, phryneas commented on src/react/hooks/useBackgroundQuery.ts
> +];
Gotcha! It makes sense in that context.

I'm slightly debating if it shouldn't be
```diff
- QueryReference<TData> | undefined,
+ undefined,
```
then.

That would help people discover cases where they have "dead code" following up, like
```ts
if (queryRef) {
  return <Foo />
}
```
but at the same point it could be annoying if ppl wanted to just disable something for a moment, keeping the rest of the code.

Arguments could be made either side. Opinions?

2023-08-01 12:18 UTC, phryneas approved these changes
I'd love some minor changes in tests, but generally this is good to go!

2023-08-01 12:18 UTC, phryneas commented on src/react/hooks/__tests__/useBackgroundQuery.test.tsx
> +    await act(() => user.click(screen.getByText('Toggle skip')));
Independently of `skip` - why would another network request happen here in the first place? Do we need to change variables to provoke that without `skip` a request would be provoked here?

2023-08-01 12:18 UTC, phryneas commented on src/react/hooks/__tests__/useSuspenseQuery.test.tsx
> +  it('suspends when options are set after using `skipToken`', async () => {
```suggestion
  it('suspends when options change away from `skipToken`', async () => {
```
The test is not really setting any options.

2023-08-01 12:18 UTC, phryneas commented on src/react/hooks/__tests__/useSuspenseQuery.test.tsx
> +    rerender({ skip: true });
Again - with or without `skip`, I wouldn't expect another result here - there's no reason to make another request in the first place.

2023-08-01 16:52 UTC, jerelmiller commented on src/react/hooks/useBackgroundQuery.ts
> +];
Right, thats not a bad idea. I'm not opposed to it being a bit louder if you unconditionally skip because that query becomes useless anyways. I like your suggestion of returning `undefined` in this case. I will make this change!

2023-08-01 16:53 UTC, jerelmiller commented on src/react/hooks/useReadQuery.ts
> +    internalQueryRef.promiseCache.set(key, internalQueryRef.promise);
Oops, yes. No idea why I didn't use the destructured value 😅

2023-08-01 16:56 UTC, jerelmiller commented on src/react/hooks/useReadQuery.ts
> +    internalQueryRef.promiseCache.set(key, internalQueryRef.promise);
[99c2881](https://github.com/apollographql/apollo-client/pull/11112/commits/99c288119d44c66f9b874d5307c5e6607708a070)

2023-08-01 17:00 UTC, jerelmiller commented on src/react/hooks/useBackgroundQuery.ts
> +];
Updated in [c64b15f](https://github.com/apollographql/apollo-client/pull/11112/commits/c64b15f1880db3c6bff62f45b54a0118755c50bf)

2023-08-01 20:10 UTC, jerelmiller commented on src/react/hooks/__tests__/useBackgroundQuery.test.tsx
> +    expect(screen.queryByTestId('greeting')).not.toBeInTheDocument();
Good point. I think I implicitly relied too much on the other tests here that prove that it suspends correctly, hence why I didn't add it, but tests should be viewed in isolation. I'll get these tests updated to check for the `Loading` UI as well.

2023-08-01 21:32 UTC, jerelmiller commented on src/react/hooks/__tests__/useBackgroundQuery.test.tsx
> +    expect(screen.queryByTestId('greeting')).not.toBeInTheDocument();
Fixed in [1e5a844](https://github.com/apollographql/apollo-client/pull/11112/commits/1e5a844da461246c2410575e9ea64a1e86e9543a)

2023-08-01 21:32 UTC, jerelmiller commented on src/react/hooks/__tests__/useBackgroundQuery.test.tsx
> +    expect(screen.queryByTestId('greeting')).not.toBeInTheDocument();
Fixed in [1e5a844](https://github.com/apollographql/apollo-client/pull/11112/commits/1e5a844da461246c2410575e9ea64a1e86e9543a)

2023-08-01 21:33 UTC, jerelmiller commented on src/react/hooks/__tests__/useBackgroundQuery.test.tsx
> +    expect(screen.queryByTestId('greeting')).not.toBeInTheDocument();
No need to apologize! Fixed in [1e5a844](https://github.com/apollographql/apollo-client/pull/11112/commits/1e5a844da461246c2410575e9ea64a1e86e9543a)

2023-08-01 21:41 UTC, jerelmiller commented on src/react/hooks/__tests__/useBackgroundQuery.test.tsx
> +    expect(screen.queryByTestId('greeting')).not.toBeInTheDocument();
Addressed in [1e5a844](https://github.com/apollographql/apollo-client/pull/11112/commits/1e5a844da461246c2410575e9ea64a1e86e9543a)

2023-08-01 21:45 UTC, jerelmiller commented on src/react/hooks/__tests__/useBackgroundQuery.test.tsx
> +    await act(() => user.click(screen.getByText('Toggle skip')));
It's more that I wanted to prove that switching back to `skip: true` didn't _itself_ have any adverse effects such as tangling it up with some other value, or that it wasn't just a "skips the first time it's true" type of thing.

You're right though, switching variables is probably a more solid way to show off that it does indeed skip. Let me see if I can make this change to make it more obvious what this test is trying to accomplish.

2023-08-01 21:49 UTC, jerelmiller commented on src/react/hooks/__tests__/useSuspenseQuery.test.tsx
> +  it('suspends when options are set after using `skipToken`', async () => {
Ha you're right, good catch. The equivalent test in `useBackgroundQuery` was even more egregious, so I updated both: [6c861b2](https://github.com/apollographql/apollo-client/pull/11112/commits/6c861b2632fcb86ebfa57559498cf101b2057f60)

2023-08-01 21:51 UTC, jerelmiller commented on src/react/hooks/__tests__/useSuspenseQuery.test.tsx
> +    rerender({ skip: true });
tl;dr; from above, since `skip` is suspenseful, I mainly just wanted to make sure I didn't tangle this value up in some weird way that caused it to only skip the first time, but not after that. There's certainly a case to be made that this test is pointless and we are better off without it. 

I'll leave it in for now, but we can find ways to make it more useful.

2023-08-01 21:59 UTC, jerelmiller commented on src/react/hooks/__tests__/useSuspenseQuery.test.tsx
> +    rerender({ skip: true });
Updated this test to switch variables with `skip: true` as well to better illustrate that `skip` is working correctly: [2f6cc8b](https://github.com/apollographql/apollo-client/pull/11112/commits/2f6cc8b306557d640598ae4a3c3880f9fb64dadc)

2023-08-01 22:22 UTC, merged