Testing suggestion: use `React.Profiler` for counting renders and snapshotting rendered DOM
apollographql/apollo-client pull request #11116
Opened 2023-08-01 12:30 UTC by phryneas

This is less a PR than me trying to illustrate a suggestion I want to make:
We have about a dozen different ways of "counting renders" in place, and they all fall short as soon as a test has more than one component that could rerender.  
Maybe we could start using the [`React.Profiler` api](https://react.dev/reference/react/Profiler) for this kind of test?

2023-08-03 12:15 UTC, phryneas commented on src/react/hooks/__tests__/useFragment.test.tsx
> +    }
This could be fixed for React 17 only by a significantly longer delay before even the ref is updated:
```diff
  return useSyncExternalStore(
     (forceUpdate) => {
      let lastTimeout = 0;
       const unsubcribe = cache.watch({
         ...diffOptions,
         immediate: true,
         callback(diff) {
-          if (!equal(diff, latestDiff)) {
-            resultRef.current = diffToResult((latestDiff = diff));
-            lastTimeout = setTimeout(forceUpdate) as any;
-          }
+          lastTimeout = setTimeout(async () => {
+            if (!equal(diff, latestDiff)) {
+              resultRef.current = diffToResult((latestDiff = diff));
+              forceUpdate();
+            }
+          }, 32);
         },
       });
```

The question is if that is a route we actually want to go  (moving the ref update, even without the 32ms timeout could make sense though).

2023-08-04 12:19 UTC, phryneas commented on src/react/hooks/__tests__/useSuspenseQuery.test.tsx
> +    }
@jerelmiller I hope you'll love this one :)

2023-08-04 12:20 UTC, phryneas commented on src/react/hooks/__tests__/useSuspenseQuery.test.tsx
> +    await act(() => user.click(screen.getByText("Refresh")));
Interaction has to happen with the real DOM, not the snapshotted DOM, so this uses `screen` instead of `withinDOM()` which is only a snapshot of the DOM at the time the render has finished.

2023-08-04 12:44 UTC, phryneas commented
Sidenote: I have no idea why this is failing in CI, it works locally. I'll have to investigate that further.

Independently: please try this out, @alessbell and @jerelmiller and give me feedback if anything here could be improved or if there are tools missing for you here!
(If you convert additional tests, just push them on top here, so we get a bit of a collection of migration patterns :) )

2023-08-04 13:02 UTC, phryneas commented on src/react/hoc/__tests__/queries/lifecycle.test.tsx
> +    }
This was one of our flaky tests!

2023-09-01 14:13 UTC, phryneas commented
I'm already marking this as "Ready for review" and would really appreciate another pair of eyes or two, but I'll also do another round of self-review later.

2023-09-06 05:56 UTC, jerelmiller requested changes
I know you tagged me to look closer at a test, but for now I wanted to submit my initial review to get you some feedback. I'll take a bit closer look at that test on my 2nd review through. Let me know what you think!

2023-09-06 05:56 UTC, jerelmiller commented on src/react/components/__tests__/client/Query.test.tsx
> +        return cloneDeep(result!);
Out of curiosity, why the `cloneDeep` here? Is this something we'll need to do in all our snapshots, or only under certain circumstances?

2023-09-06 05:56 UTC, jerelmiller commented on src/react/hoc/__tests__/queries/loading.test.tsx
> +      <ApolloProvider client={client}>{<ProfiledContainer />}</ApolloProvider>
```suggestion
      <ApolloProvider client={client}>
        <ProfiledContainer />
      </ApolloProvider>
```

No need for the curlys `{ }` 🙂

2023-09-06 05:56 UTC, jerelmiller commented on src/testing/internal/profile/profile.tsx
First off, I want to say I REALLY REALLY like this pattern. It solves one of the things thats been bothering me lately with `waitFor`, which is that its difficult to capture the (possibly) intermediate render states as renders occur.

I want to suggest a possible improvement to the API.

Currently the tests are setup as such:

```tsx
// Define a global variable that is assigned during render that can be used
// to snapshot
let capturedState;

function App() {
  // assign the variable during render to be available for snapshotting
  capturedState = useHook()
}

const ProfiledApp = profile({
  Component: App,
  // finally use the assigned variable so the profile function can capture the value
  // Usually this is paired with `!` to make TypeScript happy
  takeSnapshot: () => capturedState!;
});
```

This pattern feels a bit indirect as it uses global variables as the communication channel between the render values and the snapshot.

Instead, what about an injecting a prop that can be used to snapshot a value inside the component itself? This would eliminate the need for global variables and makes the connection much more direct.

```tsx
function App({ __profile }) {
  const state = useHook();

  __profile.takeSnapshot(state);
}

const ProfiledApp = profile({
  Component: App
});
```

Some additional considerations would need to be made here, such as what happens when `takeSnapshot` is called more than once in a single render, but I think we can find some reasonable behavior here.

Where this pattern might fall down is when perhaps you want to capture a snapshot from multiple components, such as a child or grandchild component. Not sure how best to solve this, or if you would allow for use of both APIs. TypeScript types for the snapshot also get a bit trickier since there is no `takeSnapshot` function that can infer the `Snapshot` type.

Totally down to iterate on this idea as well. The thing I'm getting at here is that if possible, it would be nice to make the snapshot API more direct to avoid the need for global variables as the communication channel. 

Thoughts?

2023-09-06 05:56 UTC, jerelmiller commented on src/testing/internal/profile/profile.tsx
> +global.TextDecoder ??= TextDecoder;
I'm curious, why are these needed here? Should this be moved to the jest setup module so that its available to all tests?

2023-09-06 05:56 UTC, jerelmiller commented on src/react/hooks/__tests__/useLazyQuery.test.tsx
> +    const ProfiledHook = profileHook(() => useLazyQuery(helloQuery));
Looking at this, I think `profileHook` can be a bit more ergonomic by returning the `snapshot` directly. I view `profileHook` much the same as `renderHook` from React Testing Library in that that testing utility is much less about testing DOM and more about working with the raw values from the hooks themselves. Because of this, `withinDOM` becomes less useful for these tests. What about returning the snapshot directly from `ProfiledHook.takeRender` (as well as the other functions that return the current render)? I think this would be a more intuitive API. 

```ts
{
  // the value is the result of the snapshot direclty
  const [, result] = await ProfiledHook.takeRender();
  expect(result.loading).toBe(false);
  expect(result.data).toBe(undefined)
}
```

The rule then would be that when we need to test again DOM, use `profile` instead. I think this is a reasonable restriction.

Thoughts?

2023-09-06 05:58 UTC, jerelmiller commented on src/react/hooks/__tests__/useFragment.test.tsx
> +    }
I'm ok with leaving it for now. I know it makes the test a little bit weird, but I think the test very well documents the behavior between the 2 React versions. `32` feels like a magic number and not sure the change is worth it. If we get too many complaints from users with the existing behavior in React 17, we can revisit.

2023-09-06 08:21 UTC, phryneas commented on src/react/components/__tests__/client/Query.test.tsx
> +        return cloneDeep(result!);
I think I just wasn't sure if this external object we are getting might stay the same object instance, but get modified, or if it's a new one every time.

I've encountered a few times where it was needed because it would capture some modifying, internal stuff, but it depends on what you're testing, so not always.

2023-09-06 08:22 UTC, phryneas commented on src/react/hoc/__tests__/queries/loading.test.tsx
> +      <ApolloProvider client={client}>{<ProfiledContainer />}</ApolloProvider>
Good point :)

2023-09-06 08:23 UTC, phryneas commented on src/react/hooks/__tests__/useFragment.test.tsx
> +        );
Yeah, this was one of the first tests I converted, and `snapshot` or `withinDOM` didn't exist yet at that point in time. I'll convert it over.

2023-09-06 08:29 UTC, phryneas commented on src/react/hooks/__tests__/useFragment.test.tsx
> +        );
On the other hand, looking at this again - the idea was that this should be a baseline check that should be true on *every* render.
Moving it outside would either add a loop, or replicate this code multiple times (in this test only twice, in others more).

I get that `takeSnapshot` is not the best place for it by name - what do you think about adding another `afterRender` or `onRender` callback (that is essentially called in the same place as `takeSnapshot`) and just moving this logic over?

2023-09-06 08:32 UTC, phryneas commented on src/react/hooks/__tests__/useLazyQuery.test.tsx
> +    const ProfiledHook = profileHook(() => useLazyQuery(helloQuery));
Hmm, I like it, but I wouldn't call it `takeRender` to prevent confusion between two methods with the same name and different signature.
I'll look into having `profileHook` return `*Snapshot` instead of `*Render` functions that return the snapshot only.

2023-09-06 08:51 UTC, phryneas commented on src/testing/internal/profile/profile.tsx
> +  hook: (props: Props) => ReturnValue
I'm a bit torn, because you can totally pass a hook in there (as long as it only takes one argument) - but yeah, not opposed to `renderCallback`, so I'll switch it out :)

2023-09-06 09:18 UTC, phryneas commented on src/react/hooks/__tests__/useLazyQuery.test.tsx
> +    const ProfiledHook = profileHook(() => useLazyQuery(helloQuery));
I like the idea, but wouldn't want to have those methods be called `takeRender` etc to avoid confusion.
I've named them `takeSnapshot` instead.
See [`8ee5ff4` (#11116)](https://github.com/apollographql/apollo-client/pull/11116/commits/8ee5ff402dc606b1989b225e5a87476b066b4387)

2023-09-06 09:25 UTC, phryneas commented on src/testing/internal/profile/profile.tsx
I like the idea, but it won't work as a prop with nested components. I'm thinking about a hook instead, like
```ts
function App() {
  const state = useHook();

  ProfiledApp.useSetSnapshot({
    foo: "bar"
  })

  // alternative to incrementally update a snapshot when it is split over multiple components
  // can only be used it the `initialSnapshot` was set in `profile` options, throws an error otherwise
  ProfiledApp.useUpdateSnapshot(lastSnapshot => {
    ...lastSnapshot, 
    foo: "bar"
  })
}

const ProfiledApp = profile({
  Component: App,
  initialSnapshot: { foo: "" }
});
```

2023-09-06 10:09 UTC, phryneas commented on src/testing/internal/profile/profile.tsx
> +    }
Yeah that should so the trick. Adding it.

2023-09-06 11:46 UTC, phryneas commented on src/react/hooks/__tests__/useFragment.test.tsx
> +        );
Renamed to `onRender` for now, as `takeSnapshot` was getting obsolete anyways with the new snapshotting logic.

2023-09-06 12:12 UTC, phryneas commented on src/testing/internal/profile/profile.tsx
Added in [`44bcbbe` (#11116)](https://github.com/apollographql/apollo-client/pull/11116/commits/44bcbbeb9ae71efd382af9249dfec74c20c2a8db)

I simplified it further - no need for that to be a hook or component, it's just a function (that can also be called in callbacks etc.) - it will change around the current snapshot (also in multiple components bit by bit), and after every render the current snapshot is saved to the side.

You can see that "bit by bit" pattern in [this test](https://github.com/apollographql/apollo-client/pull/11116/commits/44bcbbeb9ae71efd382af9249dfec74c20c2a8db#diff-8920e84a79bdb5287df13f30ca99feaa5dfdb36f24c66944ef508a0a61f7cadcL435-L525).

Only downside is that `snapshot` theoretically be `undefined`, and I don't want to add that to the types as it would pollute the types - but since we are working with testing tools I don't feel bad about this - in the worst case, it's a runtime error in the test.

2023-09-06 12:13 UTC, phryneas commented on src/react/components/__tests__/client/Query.test.tsx
> +        return cloneDeep(result!);
Here it actually wasn't needed - I removed it.

2023-09-06 12:17 UTC, phryneas commented on src/testing/internal/profile/Render.tsx
> +  get withinDOM() {
It's a getter so that `this.domSnapshot`, which in turn creates a whole new `JSDOM` instance, is only accessed if it's really necessary - same for creating the wrapped `withinDOM` function set itself.

It returns a callback instead of a plain object because the ESLint rules we have active would warn you on using `withinDOM.getByText(...)`, telling you to use `screen` instead.  
Granted, we could disable the lint rule, but in many other places that lint rule is very useful, so this seemed like a good compromise.

2023-09-06 12:18 UTC, phryneas commented on src/testing/internal/profile/Render.tsx
> +  withinDOM: () => SyncScreen;
Could be a bit long, which is why I didn't do that in the first place, but I don't really care either way.

@alessbell do you have feelings on this?

2023-09-06 12:28 UTC, phryneas commented on src/testing/internal/profile/Render.tsx
> +  private _domSnapshot: HTMLElement | undefined;
Uh, it's because I'm stupid I guess :)

[`b81367c` (#11116)](https://github.com/apollographql/apollo-client/pull/11116/commits/b81367cc74001fc7ccd47d7d67eb9858fc8a682b)

2023-09-06 12:29 UTC, phryneas commented on src/testing/internal/profile/Render.tsx
> +  }
Yup, good point.
[`b81367c` (#11116)](https://github.com/apollographql/apollo-client/pull/11116/commits/b81367cc74001fc7ccd47d7d67eb9858fc8a682b)

2023-09-06 12:42 UTC, phryneas commented on src/react/hooks/__tests__/useFragment.test.tsx
> -      expect(() => screen.getByText(/Item #2/)).toThrow();
Good point! bf9d119317dae79cb0a17b8dd2e3408ea4a7f4cd

2023-09-06 12:42 UTC, phryneas commented on src/react/hooks/__tests__/useFragment.test.tsx
> -      expect(() => screen.getByText(/Item #2/)).toThrow();
Good point! bf9d119317dae79cb0a17b8dd2e3408ea4a7f4cd

2023-09-06 12:44 UTC, phryneas commented on src/testing/internal/profile/profile.tsx
> +      snapshot: undefined,
It was, at some point :)
Good catch, removing it!

2023-09-06 12:48 UTC, phryneas commented on src/testing/internal/profile/profile.tsx
> +      interactions,
Good catch. See 84d1df2f6d23bccb2c2d1c2e74b5ddd2d712517a

2023-09-06 12:48 UTC, phryneas commented on src/testing/internal/profile/Render.tsx
> +  phase: "mount" | "update";
Good catch. See 84d1df2f6d23bccb2c2d1c2e74b5ddd2d712517a

2023-09-06 12:48 UTC, phryneas commented on src/testing/internal/profile/profile.tsx
> +      snapshot: undefined,
See 84d1df2f6d23bccb2c2d1c2e74b5ddd2d712517a

2023-09-06 12:49 UTC, phryneas commented on src/testing/internal/profile/index.ts
> +export * from "./profile.js";
👍  08512a299cbf5727af09bed72ec5be69f1632621

2023-09-06 12:50 UTC, phryneas commented on src/testing/internal/profile/profile.tsx
> +  stackTrace?: string;
I'll move it onto a symbol-indexed property, so it cannot be user-specified but we don't need the split into multiple functions.

2023-09-06 13:17 UTC, phryneas commented
@jerelmiller I think I've addressed all comments. Thanks a ton for the amazing review so far, incredibly constructive!

2023-09-06 18:49 UTC, jerelmiller commented on src/testing/internal/profile/profile.tsx
Love the change here and seems much more straightforward to me. Thanks so much for iterating on this!

> Only downside is that...

Since its an internal tool, I'm sure we can iterate and refine it over time as we see the need to. No need for it to be perfect right now.

2023-09-06 18:50 UTC, jerelmiller commented on src/react/hooks/__tests__/useLazyQuery.test.tsx
> +    const ProfiledHook = profileHook(() => useLazyQuery(helloQuery));
Love it. Thanks for updating!

2023-09-06 19:13 UTC, jerelmiller commented on src/testing/internal/profile/profile.tsx
> +global.TextDecoder ??= TextDecoder;
Ok cool, appreciate the explanation!

2023-09-06 19:16 UTC, jerelmiller approved these changes
Absolutely LOVE this. I can't wait to start using this for the new hooks we are creating for 3.9. 🎉 🔥 

I'll await @alessbell's review before merging, but thanks so much for the creative work here to make our tests more resilient!

2023-09-06 20:07 UTC, alessbell commented on src/testing/internal/profile/Render.tsx
> +  withinDOM: () => SyncScreen;
I was also thinking about what's considered a "render" vs. a "snapshot". If we were to use `withinDOMSnapshot`, we'd sometimes have:

```tsx
const { withinDOMSnapshot, snapshot } = await ProfiledApp.takeRender();
```

To me, that's a bit awkward, though I see why we'd want to make it clear that `withinDOM` is returning a snapshot of the DOM frozen in time, one that can't be interacted with 🙂 

Thoughts on:

```tsx
const { withinDOM, result } = await ProfiledApp.snapshot();
```

@jerelmiller @phryneas? or `takeSnapshot`?

2023-09-06 20:11 UTC, alessbell commented on src/testing/internal/profile/Render.tsx
> +  get withinDOM() {
> Ah I didn't realize there was an ESLint rule at play here. Perhaps that gives a bit more leverage for renaming this withinDOMSnapshot 😉

Just noting that it's the fact of calling a `getBy*` method directly on a render result (and not the specific name `withinDOM`) that would have triggered the lint rule :)

2023-09-06 20:20 UTC, alessbell commented on src/testing/internal/profile/Render.tsx
> +        /** @deprecated A snapshot is static, so avoid async queries! */
Really nice way to leverage TS here instead of a lint rule 🙌

2023-09-06 20:27 UTC, alessbell approved these changes
A lot of great utilities here that will be really nice to use when refactoring/adding tests going forward!! 🎉🎉

2023-09-06 21:47 UTC, jerelmiller commented on src/testing/internal/profile/Render.tsx
> +  withinDOM: () => SyncScreen;
Hmmm, I'm starting to see that I think each of us might end up having different interpretations and preferences with what we like. I tend to prefer the _render_ naming since we think of apps in terms of renders.

I'm cool with the way it is now and prefer to avoid the bikeshedding 😆, so let's keep it as `withinDOM` and `snapshot` 🙂

2023-09-06 22:35 UTC, merged

2023-09-07 08:19 UTC, phryneas commented on src/testing/internal/profile/Render.tsx
> +  get withinDOM() {
>  Wouldn't the same be true anyways if this were just a plain ole function though? The JSDOM instance wouldn't be created until the function is called ya? My understanding of the get computed property is that the getter function is run each time the property is accessed.

It only makes sense in the wake of the pattern this PR encourages:

```
{
  // the getter is invoked exactly once per taken render
  const { withinDOM } = Profiled.takeRender()

  // the callback can be called a lot of times
  withinDOM().getByText(...)

  withinDOM().getByText(...)
}
```
So I moved all the work into the getter and made the callback super cheap.

Makes sense from that perspective? :)