document skipToken
apollographql/apollo-client pull request #11121
Opened 2023-08-02 11:50 UTC by phryneas

I hope that does it justice - we have no real story behind `skip` itself, the option is kinda hidden - so I had no real pattern to follow here.

### Checklist:

- [ ] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2023-08-02 14:56 UTC, alessbell approved these changes
This is great!! 🙌🎉

2023-08-02 21:37 UTC, jerelmiller requested changes
This is a really great start! I'd like to see if we can go into just a little more detail on why someone should use `skipToken` over `skip` as well as showing that `useBackgroundQuery` returns `undefined` when skipped until its executed the first time.

2023-08-02 21:37 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +Instead, you should use [`skipToken`](/react/api/react/hooks#skiptoken`):
I think it would be worthwhile to explain _why_ we prefer you use `skipToken` over `skip`. The main benefit is type-safety since using it in the way its commonly seen gets really funky. Perhaps adding this example would help:

```ts
const { data } = useSuspenseQuery(query, {
  variables: { id },
  skip: !id
});
```

where your query is (the key being that `id` is non-nullable):

```graphql
query MyQuery($id: ID!) {
  # ...
}
```

Here you end up with a TypeScript error because `id` is required, but you don't have it yet and can't conditionally render `useSuspenseQuery` due to the rules of hooks. Instead, `skipToken` allows you to skip the query in a type-safe way.

I know you know all this, but figured I'd provide the suggestion to ensure we can answer the question of "why would I want this" in our docs.

2023-08-02 21:37 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +const [ queryRef ] = useBackgroundQuery(
```suggestion
const [queryRef] = useBackgroundQuery(
```

2023-08-02 21:37 UTC, jerelmiller commented on docs/source/api/react/hooks.mdx
> +const [ queryRef ] = useBackgroundQuery(
```suggestion
const [queryRef] = useBackgroundQuery(
```

2023-08-02 21:37 UTC, jerelmiller commented on docs/source/data/suspense.mdx
> +const [ queryRef ] = useBackgroundQuery(
It might be worth mentioning here or somewhere in our docs that `queryRef` is `undefined` until the query is executed for the first time.

2023-08-03 22:48 UTC, jerelmiller commented on docs/source/api/react/hooks.mdx
> +<blockquote>
💯 💯 🔥 🔥

2023-08-03 22:49 UTC, jerelmiller approved these changes
🙌 thanks so much for making those updates! That section about the _why_ on `skipToken` is 🔥

2023-08-04 08:12 UTC, phryneas commented
Great :)

I'm going to leave this unmerged, as that would complicate reviewing @alessbell's Suspense docs. 
Feel free to just hit the merge button once those are in!

2023-08-05 05:15 UTC, merged