Update doc replace to vite
apollographql/apollo-client pull request #11352
Opened 2023-11-09 10:14 UTC by gento-ogane

#11305 

In [Vite](https://vitejs.dev/), default file name is `main.jsx` instead of `index.js`, so I replaced `index.js` to `main.jsx`.

### Checklist:
- [ ] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2023-11-09 10:14 UTC, apollo-cla commented
@gento-ogane: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2023-11-14 14:43 UTC, jerelmiller commented
Thanks for the contribution @gento-ogane! We'll do our best to get to this PR as soon as we can. A couple of our team is at conferences this week so we may be a bit slow to get to this. Apologies in advance!

2023-12-25 08:38 UTC, illyakurochkin commented on docs/shared/link-chain.mdx
> +```jsx title="main.jsx""
Why did you change it to `jsx`?

2024-01-18 23:55 UTC, jerelmiller requested changes
Hey @gento-ogane 👋 

I am so sorry it took me so long to get back to you on this PR! I had some time to sit down and run through the getting started to make sure everything still worked/made sense and all looks good!

The only change I'd request you make is reverting the changes in type/filenmae to all docs except the "Getting started" page. Once you're done there, I'd be happy to approve this PR and get this merged. Thanks so much for your patience 🙏

2024-01-18 23:55 UTC, jerelmiller commented on docs/shared/link-chain.mdx
> +```jsx title="main.jsx""
I'd prefer to revert the changes to all the non-introductory docs back to `index.js`. I think it makes sense in the context of the vite-specific documentation, but for the rest of it, `index.js` is a fairly common, tool agnostic name.

On a separate note, it looks like you have an extra `"` at the end here 🙂

2024-01-18 23:55 UTC, jerelmiller commented on docs/source/get-started.mdx
> +```jsx title="main.jsx"
I think these changes in the context of this doc are totally fine! Your justification that its a Vite default makes sense 🙂

2024-01-29 20:57 UTC, jerelmiller approved these changes
Thanks a bunch for your contribution @gento-ogane! I'm sure new newcomers will really appreciate this change 🙂

2024-01-29 21:06 UTC, merged

2024-02-08 00:48 UTC, gento-ogane commented
@jerelmiller 
Sorry I did not notice your reply...
Thanks for your review and commit  and merge!!

2024-02-08 00:49 UTC, jerelmiller commented
You're very welcome!