feat: extract watchFragment into separate method on ApolloCache
apollographql/apollo-client pull request #11465
Opened 2024-01-05 18:02 UTC by alessbell

Closes #11348.

Initial refactor of call to `cache.watch` into separate `watchFragment` method on the cache. All `useFragment` tests are passing.

To do:
- confirm we can start with a more limited set of options, see `WatchFragmentOptions`
- refactor duplicated type, see `UseFragmentResult`
- figure out if `immediate: true` is still needed, existing tests pass without it before and after
- add tests
- would also like to spin up a demo with e.g. Apollo Angular

### Checklist:

- [ ] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2024-01-05 20:22 UTC, jerelmiller reviewed
I am so stoked about this one! I think this will lay some great groundwork for the fragment features we want to release in 3.10 as well as providing this API to non-React devs. Thanks for starting this!

Left some initial feedback based on its current state 🙂

2024-01-05 20:22 UTC, jerelmiller commented on src/cache/core/cache.ts
> +        immediate: true, // is this necessary? tests pass without it
I think the question here would be whether we want to immediately emit a value when subscribing to the observable. We do this with [`ObservableQuery`](https://github.com/apollographql/apollo-client/blob/eb2cfee1846b6271e438d1a268e187151e691db4/src/core/ObservableQuery.ts#L135), so there is some precedent here. I think its perfectly reasonable to emit a value right away here.

The reason I think this passes with or without this `immediate` option is because `useFragment` calls `cache.diff` on every render, so there is already a result to work with in `getSnapshot` on that first render without the need for the `callback` to fire. I'd prefer if we think about this particular API in isolation since `useFragment` can adapt to whatever makes sense from the core library perspective.

That being said, I _could_ see a case where one might want to decide whether they'd prefer to wait for the observable to emit until the next cache update. Perhaps you could make this part of `options` and default it to `true` if not provided?

2024-01-05 20:22 UTC, jerelmiller commented on src/cache/core/cache.ts
> +export interface WatchFragmentOptions<TData, TVars> {
I think the only others that are available to `useFragment` that aren't here are `variables` and `canonizeResults`. We absolutely should include `variables` as an option since that will be needed for some fragments. I think there is a case to include `canonizeResults` as well to round out the API everywhere, though if we include it, I'd introduce it as `@deprecated` like we have for some of the new hooks available in 3.9.

2024-01-05 20:22 UTC, jerelmiller commented on src/cache/core/cache.ts
> +      missing?: MissingTree | undefined;
Is there ever a case where the result isn't complete and we have an `undefined` missing? If not, I'd make this a required property and remove the `| undefined` part of the union.

```suggestion
      missing: MissingTree;
```

2024-01-05 20:22 UTC, jerelmiller commented on src/cache/core/cache.ts
> +      missing?: undefined;
Since we don't include the `missing` key when the result isn't complete, does it even make sense to include this property? I'd prefer just removing it completely so TS complains if you try and access it.

```suggestion
```

2024-01-05 20:22 UTC, jerelmiller commented on src/cache/core/cache.ts
> +        },
[nit] You might consider moving this `if` to the top of the `callback` function and returning early if these values are equal. No need to create a `result` object if we aren't going to emit it.

```suggestion
        callback(diff) {
          if (equal(diff, latestDiff)) {
            return;
          }
          
          const result = {
            data: diff.result as DeepPartial<TData>,
            complete: !!diff.complete,
          } as WatchFragmentResult<TData>;

          if (diff.missing) {
            result.missing = mergeDeepArray(
              diff.missing.map((error) => error.missing)
            );
          }
          
          latestDiff = diff;
          observer.next(result);
        },
```

2024-01-05 20:22 UTC, jerelmiller commented on src/core/ApolloClient.ts
> +   * observer when the cache store changes.
```suggestion
   * Watches the cache store of the fragment according to the options specified
   * and returns an {@link Observable}. We can subscribe to this
   * {@link Observable} and receive updated results through a GraphQL
   * observer when the cache store changes.
```

2024-01-05 20:22 UTC, jerelmiller commented on src/cache/core/cache.ts
> +  public watchFragment<TData = any, TVars = OperationVariables>(
```suggestion
  public watchFragment<TData = unknown, TVars = OperationVariables>(
```

For new APIs, I think we should default to `unknown` on the data type for a bit better type safety.

2024-01-05 20:22 UTC, jerelmiller commented on src/core/ApolloClient.ts
> +  public watchFragment<T = any, TVariables = OperationVariables>(
```suggestion
  public watchFragment<T = unknown, TVariables = OperationVariables>(
```

We should also default to `unknown` here for better type safety.

```suggestion
  public watchFragment<TFragmentData = any, TVariables = OperationVariables>(
```

[nit] What do you think about calling this `TFragmentData` to be a bit more explicit?

2024-01-05 20:22 UTC, jerelmiller commented on src/react/hooks/useFragment.ts
> +      const watchedFragment = cache.watchFragment(options).subscribe({
[nit] We tend to call this variable `subscription` (e.g. in [`useQuery`](https://github.com/apollographql/apollo-client/blob/eb2cfee1846b6271e438d1a268e187151e691db4/src/react/hooks/useQuery.ts#L235)). How do you feel about naming this the same?

```suggestion
      const subscription = cache.watchFragment(options).subscribe({
```

2024-01-09 15:47 UTC, alessbell commented
Thanks for the speedy review, @jerelmiller! Will make these changes and push up some more tests shortly :)

2024-01-12 21:46 UTC, alessbell commented on src/react/hooks/useFragment.ts
> +      const watchedFragment = cache.watchFragment(options).subscribe({
Updated in https://github.com/apollographql/apollo-client/pull/11465/commits/67c1e1cb18b242644a36b832607b2abaea4a6714

2024-01-12 21:46 UTC, alessbell commented on src/core/ApolloClient.ts
> +  public watchFragment<T = any, TVariables = OperationVariables>(
Updated in https://github.com/apollographql/apollo-client/pull/11465/commits/67c1e1cb18b242644a36b832607b2abaea4a6714

2024-01-12 21:46 UTC, alessbell commented on src/cache/core/cache.ts
> +  public watchFragment<TData = any, TVars = OperationVariables>(
Updated in https://github.com/apollographql/apollo-client/pull/11465/commits/67c1e1cb18b242644a36b832607b2abaea4a6714

2024-01-12 21:46 UTC, alessbell commented on src/core/ApolloClient.ts
> +   * observer when the cache store changes.
Updated in https://github.com/apollographql/apollo-client/pull/11465/commits/67c1e1cb18b242644a36b832607b2abaea4a6714

2024-01-12 21:47 UTC, alessbell commented on src/cache/core/cache.ts
> +      missing?: undefined;
Since this is part of a union and TS later complains if we try to conditionally assign to `missing`, I've changed this to `missing?: never`.

2024-01-12 21:48 UTC, alessbell commented on src/cache/core/cache.ts
> +      missing?: MissingTree | undefined;
Updated in https://github.com/apollographql/apollo-client/pull/11465/commits/67c1e1cb18b242644a36b832607b2abaea4a6714

2024-01-12 21:48 UTC, alessbell commented on src/cache/core/cache.ts
> +export interface WatchFragmentOptions<TData, TVars> {
Updated in https://github.com/apollographql/apollo-client/pull/11465/commits/67c1e1cb18b242644a36b832607b2abaea4a6714

2024-01-25 17:21 UTC, alessbell commented on src/cache/core/cache.ts
> +        immediate: true, // is this necessary? tests pass without it
Closing the loop here: we discussed offline and will move forward without exposing `immediate` in `watchFragment`'s options to start. We can always decide to expose it in the future.

2024-01-25 17:29 UTC, alessbell commented
/release:pr

2024-01-25 17:33 UTC, alessbell commented
/release:pr

2024-03-12 21:01 UTC, alessbell commented on src/cache/core/cache.ts
> +        },
Updated in https://github.com/apollographql/apollo-client/pull/11465/commits/ea48ea3c6dea5dfce34d50e0e8505c0e8badfa09

2024-03-14 20:09 UTC, alessbell commented on docs/source/api/core/ObservableQuery.mdx
> +api_reference: true
I'm not sure what this does tbh, but it was the only API reference page missing this in the front matter :) @phryneas any ideas here?

2024-03-14 20:10 UTC, alessbell commented on src/core/ApolloClient.ts
> +   * You can provide an `ApolloLink` instance to serve as Apollo Client's network layer. For more information, see [Advanced HTTP networking](https://www.apollographql.com/docs/react/networking/advan
I noticed these `{@link ...}` annotations were showing up as broken in the docs - @phryneas confirmed they should be removed in favor of backticks.

2024-03-14 20:14 UTC, alessbell commented
### Docs page previews

#### `ApolloClient` API Reference
![ApolloClientAPIReference](https://github.com/apollographql/apollo-client/assets/5139846/25a099dd-3af9-4c8b-b410-7221594d3361)

#### `InMemoryCache` API Reference
![InMemoryCacheAPIReference](https://github.com/apollographql/apollo-client/assets/5139846/42af3491-5a67-4b70-bd97-3b08a7341d29)

#### Caching > Reading and writing

I've added a section here, although it doesn't have an example like the other sections. I also noticed that there is no `watchQuery` section on this page, so I'd be happy to remove it for now.

![CleanShot 2024-03-14 at 15 34 08](https://github.com/apollographql/apollo-client/assets/5139846/c058e8d9-0c2c-47fd-9a6b-ddab95cc6cee)

2024-03-14 20:16 UTC, alessbell commented on .api-reports/api-report-core.md
> +    // Warning: (ae-forgotten-export) The symbol "WatchFragmentOptions" needs to be exported by the entry point index.d.ts
Does this warning, among others in the `.api-reports/*` diffs, need to be addressed?

2024-03-14 20:17 UTC, alessbell commented on docs/README.md
> +For general local installation and development instructions, see the [docs site README](https://github.com/apollographql/docs).
Added local dev steps here for future reference

2024-03-14 20:18 UTC, alessbell commented on src/__tests__/ApolloClient.ts
> +      const stream = new ObservableStream(observable);
Refactored using `ObservableStream` :) Thanks for your help @jerelmiller!

2024-03-14 20:20 UTC, alessbell commented on src/cache/core/cache.ts
> +export type WatchFragmentResult<TData> =
`WatchFragmentResult` is identical to `UseFragmentResult` - noting this because I'm not sure whether refactoring is worth it if it causes complications for docs generation. Thoughts @jerelmiller @phryneas?

2024-03-14 20:33 UTC, alessbell commented on src/react/hooks/useFragment.ts
> +            if (equal(result, resultRef.current)) return;
Re: our offline conversation @jerelmiller, setting `latestDiff` inside `watchFragment` only _after_ initial subscription fixed the issue where an existing result wasn't immediately delivered, but that fix was causing a bunch of `useFragment` tests to fail. I'm still trying to wrap my brain around why I need this defensive check in the `next` handler in `useFragment` now.

2024-03-14 23:03 UTC, jerelmiller commented on src/react/hooks/useFragment.ts
> +            if (equal(result, resultRef.current)) return;
tl;dr; this is needed to prevent an unnecessary rerender for the first result emitted from `watchFragment`.

---

Zen Observable delivers the first result asynchronously, regardless of whether the `observer.next` call was done synchronously. This presents problems for the initial result returned from `useFragment` because we can't just get the initial value from the observable subscription.

Since `useFragment` needs a synchronous result on the first render, we need to get it by other means. This value is retrieved by this line:

```ts
resultRef.current = diffToResult(cache.diff<TData>(diffOptions));
```

This is great except `watchFragment` will also deliver an initial result that is equal to this one. This check is there to prevent us from re-rendering the component unnecessarily for that initial value.

Note: this _should_ be the only time this check is ever expected to return `true` since we don't emit values from the subscription unless the data has changed.

2024-03-15 11:41 UTC, phryneas commented on docs/source/api/core/ObservableQuery.mdx
> +api_reference: true
I have no idea what it does. It doesn't turn up in the sources of the docs repo either, so 🤷

2024-03-15 11:42 UTC, phryneas commented on .api-reports/api-report-core.md
> +    // Warning: (ae-forgotten-export) The symbol "WatchFragmentOptions" needs to be exported by the entry point index.d.ts
Not until someone comes up and asks for us to actually export it - these warnings are mostly fine :)

2024-03-15 11:55 UTC, phryneas commented on src/cache/core/cache.ts
> +export type WatchFragmentResult<TData> =
That seems fine from my perspective.

2024-03-15 12:19 UTC, alessbell commented
Not sure why Netlify build is failing with "Error: error:0308010C:digital envelope routines::unsupported", will take a look in a bit.

2024-03-15 13:03 UTC, phryneas commented on .api-reports/api-report-cache.md
> +
I'd be happy if we could avoid it to get more `(undocumented)` comments here - could you add some docblocks to those types? :)

2024-03-15 13:14 UTC, phryneas commented on src/__tests__/ApolloClient.ts
> +      expect(handleNext).toHaveBeenCalledTimes(0);
I'd try not to create a new subscription here, since new subscriptions can sometimes "kick off" new behaviour and we don't want to test that.

How about something like this?
```suggestion
  await expect(stream.takeNext({timeout: 1000})).rejects.toEqual(expect.any(Error));
```

2024-03-15 13:37 UTC, phryneas commented on src/cache/core/cache.ts
> +        ...diffOptions,
Do we expect a second subscriber to the observable to create it's own `this.watch` watcher, or should this maybe be created in the lines above and a second observer would just attach to a pre-existing observable?

( I do know that this would probably complicate things, but wanted to put the option in the room)

2024-03-15 16:21 UTC, alessbell commented on src/__tests__/ApolloClient.ts
> +      expect(handleNext).toHaveBeenCalledTimes(0);
Resolved in [4a8dac0](https://github.com/apollographql/apollo-client/pull/11465/commits/4a8dac064f2254cfe94cf74633d1130cfb52f9a4)

2024-03-15 16:34 UTC, alessbell commented on .api-reports/api-report-cache.md
> +
Resolved in https://github.com/apollographql/apollo-client/pull/11465/commits/dabe2cda3852aa1e9f830f086f14552f77cdff57

2024-03-15 16:41 UTC, alessbell commented on src/cache/core/cache.ts
> +        ...diffOptions,
That's a good question, thanks for raising it. My initial thought is that with the work Jerel has sketched out around data masking, this optimization might be better suited for a future PR, though I'm open to tackling it here. What do you think, @jerelmiller?

2024-03-15 18:35 UTC, alessbell commented
/release:pr

2024-03-18 03:25 UTC, jerelmiller commented on src/react/hooks/useFragment.ts
> +  React.useMemo(() => {
Turns out your found a bug when testing this PR. FYI I [borrowed this](https://github.com/apollographql/apollo-client/pull/11689/files#diff-df70656746a3d5a084fae96c5197f0fbdbfcb6c001cc1e086e3f7d5f419f27d5R91-R95) in #11689 to fix an issue where there was an unnecessary rererender when changing options.

2024-03-18 04:01 UTC, jerelmiller requested changes
So excited to get this in! Thanks for pushing this along 🙂.

2024-03-18 04:01 UTC, jerelmiller commented on src/__tests__/ApolloClient.ts
> +      }
I think this test might be missing the actual assertion on the thing you're trying to test here, which is that `@nonreactive` won't emit new values. This test only checks that the initial value is emitted, but it would be great to demonstrate that another cache write to `text` won't emit anything else.

2024-03-18 14:02 UTC, alessbell commented on src/react/hooks/useFragment.ts
> +  const resultRef = React.useRef<UseFragmentResult<TData>>(
Hmmm, I had this as part of the changes that came out of our last pairing session on this PR. Happy to sync offline.

2024-03-18 17:14 UTC, jerelmiller commented on src/cache/core/cache.ts
> +        ...diffOptions,
I think its fine to add this to the data masking work. I wouldn't expect a 2nd subscriber right away, but I could definitely see that happening as more adopt this API. I would expect most people to just call `watchFragment` multiple times, so they would be separate observables.

I don't think it hurts too much to have multiple watchers on the same fragment for now, but I do like the idea of reducing this to one watcher as an optimization.

2024-03-18 17:26 UTC, alessbell commented on src/cache/core/cache.ts
> +   * **Required.** A GraphQL fragment document parsed into an AST with the `gql`
Updated in [88cc319](https://github.com/apollographql/apollo-client/pull/11465/commits/88cc319a7da2f0aad7cdc4e7e9ac9e56b1a35e07) - added a "required" docgroup.
![CleanShot 2024-03-18 at 10 58 30](https://github.com/apollographql/apollo-client/assets/5139846/1d7a0301-fa1f-4989-b0e8-0e260e124384)

2024-03-18 17:26 UTC, alessbell commented on src/cache/core/cache.ts
> +   * **Required.** An object containing a `__typename` and primary key fields
Updated in [88cc319](https://github.com/apollographql/apollo-client/pull/11465/commits/88cc319a7da2f0aad7cdc4e7e9ac9e56b1a35e07)

2024-03-18 17:40 UTC, alessbell commented on src/core/ApolloClient.ts
> +   * Observable and receive updated results through a GraphQL
Sgtm 👍 This is (at least) 6 year old language, I also changed it in the `watchQuery` doc block for consistency: https://github.com/apollographql/apollo-client/pull/11465/commits/3efd80d07ff595d0b57f86da04d6e4dccbbb3c17

2024-03-18 17:41 UTC, alessbell commented on src/core/ApolloClient.ts
> +   * Observable and receive updated results through a GraphQL
Updated in https://github.com/apollographql/apollo-client/pull/11465/commits/3efd80d07ff595d0b57f86da04d6e4dccbbb3c17

2024-03-18 17:42 UTC, alessbell commented on src/react/hooks/useFragment.ts
> +        const subscription = cache.watchFragment(options).subscribe({
Ah yes, thanks for catching that! Updated in https://github.com/apollographql/apollo-client/pull/11465/commits/641382092f51114a349f4111140fb2aa8509876a

2024-03-18 17:44 UTC, alessbell commented on src/react/hooks/useFragment.ts
> +  const resultRef = React.useRef<UseFragmentResult<TData>>(
Synced offline, updated in https://github.com/apollographql/apollo-client/pull/11465/commits/641382092f51114a349f4111140fb2aa8509876a

2024-03-18 18:06 UTC, alessbell commented on src/__tests__/ApolloClient.ts
> +      }
Ah shoot, I meant to come back to this one. I've confirmed `@nonreactive` is not (yet) supported in fragments alone, since the mechanism by which we compare and opt out of reacting to updates in a `@nonreactive` subtree happens at the query level in `ObservableQuery` via `equalByQuery`: https://github.com/apollographql/apollo-client/blob/4fedd26a0e8b3bd1bb5e30953f6fdca1958b3932/src/core/ObservableQuery.ts#L328-L331

I've updated the test accordingly in https://github.com/apollographql/apollo-client/pull/11465/commits/4fedd26a0e8b3bd1bb5e30953f6fdca1958b3932

2024-03-18 18:10 UTC, alessbell commented on src/__tests__/ApolloClient.ts
> +  });
Updated in https://github.com/apollographql/apollo-client/pull/11465/commits/ccb3a1a87569b896c2c9130dc16f16342e4a3140

2024-03-18 18:15 UTC, jerelmiller commented on src/__tests__/ApolloClient.ts
> +      }
Ok thanks for the background! Thats useful. You saying "yet" makes me think we will want to eventually support it.

What do you think about making this an `it.failing` test instead to communicate this? I LOVE this test as documentation for expected behavior, but with `it.failing`, it helps more clearly communicate our intentions in the future. Plus, when we do get around to the implementation, it means we can just remove `.failing` without having to rewrite the test. Thoughts?

2024-03-18 18:20 UTC, alessbell commented on src/__tests__/ApolloClient.ts
> +      }
Sure, sounds good! Updated in https://github.com/apollographql/apollo-client/pull/11465/commits/46c8eb70de93ab4eaa6d33a22402007908520c5b. And I don't have a specific use case in mind, but it does seem like something we can support in the future :)

2024-03-18 19:01 UTC, jerelmiller approved these changes
🎉 This looks great! Really looking forward to getting this out there 🙂

2024-03-18 19:02 UTC, merged