fix: avoid redundant refetchQueries call for mutation with no-cache policy
apollographql/apollo-client pull request #11515
Opened 2024-01-23 16:12 UTC by vladar

This is a quick small fix for the bug outlined in #10238

In the nutshell, `mutation.refetchQueries` below is an empty array, not boolean or undefined. So this check errorneously evaluates to true even when the `refetchQueries` option is not set for the mutation.

The fix in this PR is a bit defensive - in case if it could be actually something other than array.

https://github.com/apollographql/apollo-client/blob/31fc8dfa22ca3074e95e521d28eba0544373ed8c/src/core/QueryManager.ts#L400-L406

Fixes #10238

2024-01-24 11:11 UTC, phryneas requested changes
Hi, this is a *very* good catch, thank you for that!

I've made some suggestions that would keep the change in bundle size down a bit - what do you think?

2024-01-24 11:11 UTC, phryneas commented on src/core/QueryManager.ts
> +      shouldRefetchQueries ||
```suggestion
      (mutation.refetchQueries || "").length > 0 ||
```

2024-01-24 11:11 UTC, phryneas commented on src/core/QueryManager.ts
> +      : Boolean(mutation.refetchQueries);
```suggestion
```

2024-01-24 13:02 UTC, vladar commented
> Hi, this is a _very_ good catch, thank you for that!
> 
> I've made some suggestions that would keep the change in bundle size down a bit - what do you think?

Updated, thanks. But looks like it doesn't help with `size` check.

2024-01-24 14:21 UTC, phryneas commented
Don't worry about the size check - I'll fix that up before merging :)

This looks good to me. We're currently in a code freeze, so this will probably be released in a 3.9.1 after we've released our 3.9 minor.

2024-01-24 14:22 UTC, phryneas approved these changes

2024-01-31 16:06 UTC, jerelmiller approved these changes
🎉 Now with 3.9 out, we'll get this into 3.9.1 🙂

2024-01-31 16:18 UTC, merged