Add support for passing in client into useFragment
apollographql/apollo-client pull request #11525
Opened 2024-01-25 22:01 UTC by vezaynk

2024-01-25 22:01 UTC, apollo-cla commented
@vezaynk: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2024-01-25 22:32 UTC, jerelmiller commented
Hey @vezaynk 👋 

Appreciate the PR! Before we move forward with this, would you mind writing a couple tests for this? We want to be sure that future changes to our hooks don't break existing functionality. 

You can find the useFragment tests here: https://github.com/apollographql/apollo-client/blob/main/src/react/hooks/__tests__/useFragment.test.tsx

If you'd like an example of how we test some of our other hooks that allow a `client` override, here's an example from `useSuspenseQuery`: https://github.com/apollographql/apollo-client/blob/038629c62bf0d4665b52d9fade3fb88861ae1194/src/react/hooks/__tests__/useSuspenseQuery.test.tsx#L992-L1025

Assuming we move forward with this, we will likely slate this for our 3.10 release as its new functionality and we are in a code freeze for 3.9. 3.9 will be released as soon as we finish documentation, which should be early next week.

Thank you!

2024-01-25 23:02 UTC, vezaynk commented
@jerelmiller Can this be shipped as a patch after the release? It's a very minor API extension that mirrors what every other hook does. It's not really "new functionality".

2024-01-25 23:05 UTC, jerelmiller commented
@vezaynk I'll discuss with the team and let you know. We have a team meeting first thing Monday morning.

In the meantime, if you need this functionality, I'd recommend using [`patch-package`](https://www.npmjs.com/package/patch-package) in your setup to provide this functionality.

2024-01-31 17:02 UTC, jerelmiller requested changes
Hey @vezaynk 👋 

I'm still waiting on confirmation about when we'd like to release this. One of our maintainers has been out recently, so as soon as we get a consensus, I'll let you know.

In the mean time, I wanted to get you a proper review. Aside from adding tests, the only thing that I'd like to see is a docblock for the `client` option.

Appreciate the contribution!

2024-02-01 01:46 UTC, vezaynk commented
@jerelmiller Thanks for the review. I have added the suggestions and wrote 2 tests.

2024-02-01 15:02 UTC, alessbell requested changes
Thanks for adding those tests, @vezaynk! This is super close to merging - the team synced now that we're all back online and we'll get it out in the next patch 🚀

Added a few minor comments, one question for @phryneas to make sure the docblock is good to go and the tests are failing on CI because they're missing one thing: `client?: ApolloClient<any>;` needs to be added to the type test "UseFragmentOptions interface shape" at the bottom of `useFragment.test.tsx`.

2024-02-01 15:08 UTC, phryneas commented on src/react/hooks/useFragment.ts
> +  client?: ApolloClient<any>;
We should probably create a separate `FragmentOptionsDocumentation` interface in the future and leave it as it is right now - otherwise the wording here would change to

```diff
-  * The instance of {@link ApolloClient} to use to look up the fragment.
+   * The instance of {@link ApolloClient} to use to execute the query.
   *
   * By default, the instance that's passed down via context is used, but you
   * can provide a different instance here.
   *
   * @docGroup 1. Operation options
```

2024-02-01 15:14 UTC, alessbell commented on src/react/hooks/useFragment.ts
> +  client?: ApolloClient<any>;
Ah got it, thanks 👍

2024-02-01 16:48 UTC, alessbell commented
Hi @vezaynk 👋 there's still one test failing ("UseFragmentOptions interface shape" at the bottom of useFragment.test.tsx). Let me know if you were going to circle back to that, otherwise it's no problem for me to push up the one line fix and merge, thanks!

2024-02-01 16:50 UTC, jerelmiller commented on src/react/hooks/useFragment.ts
> +   * The instance of {@link ApolloClient} to use to lookup the fragment.
Oops, this one was my fault 😆

2024-02-01 16:53 UTC, vezaynk commented on src/react/hooks/__tests__/useFragment.test.tsx
> +    screen.getByText(/Item #1/);
I can change it to your suggestion, sure.

My reasoning was that I was thinking that it would be good to test that the behavior is exact with an overridden client, not just that it doesnt throw an error.

2024-02-01 16:57 UTC, alessbell commented on src/react/hooks/__tests__/useFragment.test.tsx
> +    screen.getByText(/Item #1/);
Yeah good point, added back the check for Item #1 rendering 👍

2024-02-01 22:12 UTC, vezaynk commented
@alessbell @jerelmiller I think I addressed everything

2024-02-01 22:14 UTC, alessbell approved these changes

2024-02-01 22:15 UTC, jerelmiller commented
Thanks so much @vezaynk! As soon as we see the tests pass, we'd be happy to merge this. Don't worry about the failed security scan checks or api extractor checks. We'll handle those 🙂 

Thanks so much again for the contribution!

2024-02-01 22:15 UTC, jerelmiller approved these changes

2024-02-01 22:19 UTC, merged

2024-02-06 19:34 UTC, alessbell commented
This has been released in v3.9.3 🎉