feat(mocking): make response error and result not required when delay is infinite
apollographql/apollo-client pull request #11562
Opened 2024-02-01 23:08 UTC by mspiess

2024-02-01 23:09 UTC, apollo-cla commented
@mspiess: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2024-02-01 23:11 UTC, jerelmiller commented
Hey @mspiess 👋 

Appreciate the contribution! Would you be willing to provide some more information on the use case you're solving for and provide some more information about this change? Thanks!

2024-02-01 23:27 UTC, mspiess commented
Hey @jerelmiller 👋 

I updated the PR description.

2024-02-02 00:23 UTC, jerelmiller requested changes
Hey @mspiess 👋 

I think this change makes sense and provides a nice improvement in your tests. Appreciate the additional context on why this change makes sense!

I've got a few minor things for you to look at. I'd love to get this in the next patch or two. Thanks again!

2024-02-02 00:23 UTC, jerelmiller commented on src/testing/core/mocking/__tests__/mockLink.ts
> +    const observable = mockLink.request(createOperation(null, { query }));
```suggestion
    const observable = execute(mockLink, { query });
```

Can you use the `execute` function from [`link/core/execute`](https://github.com/apollographql/apollo-client/blob/main/src/link/core/execute.ts) here instead? It does some of this setup for you and ensures the link is called like it would be in production 🙂.

Normally I wouldn't care too much, but since this is a new file, patterns from other tests tend to multiply, and I'd like to ensure we use `execute` where possible.

2024-02-02 00:23 UTC, jerelmiller commented on src/testing/core/mocking/__tests__/mockLink.ts
> +    await new Promise((resolve) => setTimeout(resolve, 10));
We have a [`wait` helper](https://github.com/apollographql/apollo-client/blob/7555b2e2139049b3ce21198cb896ccc105dfadb8/src/testing/core/wait.ts#L1-L3) that you can use here for this delay which you can get from the [`testing` entry point](https://github.com/apollographql/apollo-client/blob/main/src/testing/index.ts). Would you mind switching to this?

```suggestion
    await wait(10);
```

2024-02-02 00:23 UTC, jerelmiller commented on src/testing/core/mocking/mockLink.ts
> +          `Mocked response should contain either result, error or infinite delay: ${key}`
I'd love if we could be a bit more explicit here. I think this is a great opportunity to show exactly what is expected to make this work. Could we provide a bit more detailed instruction for the infinite delay case?

I'd love to take this opportunity to spruce it up a bit anyways 🙂. Adding backticks around the code parts makes it a bit more obvious this is related to the configuration on the code itself.

```suggestion
          `Mocked response should contain either `result`, `error`, or set the `delay` to `Infinity`: ${key}`
```

2024-02-02 00:23 UTC, jerelmiller commented on src/testing/core/mocking/__tests__/mockLink.ts
> +  });
Could you provide one more test case that proves that a really high number _does_ trigger the error? I'd love to make it obvious that `Infinity` is the only valid value that is allowed to omit result/error since its never expected to resolve.

You can use `Number.MAX_SAFE_INTEGER` instead of trying to come up with a big number yourself to get as "close" to infinity as possible.

2024-02-02 00:29 UTC, jerelmiller commented
One more thing! Looks like we've got a couple snapshot tests that check the output of that error in `MockedProvider.test.tsx`. After we get the error output settled, can you update those snapshot tests to the new error message? That should get your tests passing in this PR. Thanks!

2024-02-05 20:41 UTC, alessbell requested changes
Thanks for working on this and pushing those updates! Just took one more look - this is almost ready to merge 👍

2024-02-05 20:41 UTC, alessbell commented on src/testing/core/mocking/mockLink.ts
> +          `Mocked response should contain either \`result\`, \`error\`, or set the \`delay\` to \`Infinity\`: ${key}`
Nit: wording

```suggestion
          `Mocked response should contain either \`result\`, \`error\` or a \`delay\` of \`Infinity\`: ${key}`
```

2024-02-05 20:41 UTC, alessbell commented on src/testing/core/mocking/__tests__/mockLink.ts
> +        delay: Number.MAX_VALUE,
As it turns out, both `Number.MAX_VALUE` and `Number.MAX_SAFE_INTEGER` will cause the timeout to fire immediately because neither [fit into a 32-bit signed integer](https://developer.mozilla.org/en-US/docs/Web/API/setTimeout#maximum_delay_value). (We can tell that it's not doing anything here since the test finishes in less than the default Testing Library 5000ms timeout without timer mocks.)

The timing itself isn't material to the behavior of this test, but it would be nice to make it accurate to the behavior we'd see in a real test.

With that in mind, would you mind adding a comment about this here and using a random very high number? We can use Jest's [timer mock](https://jestjs.io/docs/timer-mocks) feature and e.g. `jest.advanceTimersByTime(2_000_000_000)` here to get the test passing again.

2024-02-05 20:49 UTC, jerelmiller commented on src/testing/core/mocking/__tests__/mockLink.ts
> +        delay: Number.MAX_VALUE,
Ah shoot, I forgot about that. Thanks for the reminder @alessbell!

2024-02-05 21:54 UTC, mspiess commented on src/testing/core/mocking/__tests__/mockLink.ts
> +        delay: Number.MAX_VALUE,
I used a constant named `MAXIMUM_DELAY`. Does that provide enough context, or would you prefer a comment?

2024-02-06 18:38 UTC, alessbell commented on src/testing/core/mocking/__tests__/mockLink.ts
> +jest.useFakeTimers();
```suggestion
beforeAll(() => jest.useFakeTimers());
afterAll(() => jest.useRealTimers());
```

2024-02-06 18:40 UTC, alessbell commented on src/testing/core/mocking/__tests__/mockLink.ts
> +        delay: Number.MAX_VALUE,
A short comment above `MAXIMUM_DELAY` would be helpful, something like "We've chosen this value as the `MAXIMUM_DELAY` since values that don't fit into a 32-bit signed int cause setTimeout to fire immediately"

2024-02-06 18:44 UTC, alessbell approved these changes
Left two more minor comments, after those changes are pushed up this is good to go 🚀 Appreciate the contribution @mspiess!

2024-02-09 15:47 UTC, jerelmiller approved these changes
Thanks a bunch @mspiess! We'll get this in the next patch which should release sometime next week.

2024-02-09 15:48 UTC, merged

2024-02-09 15:54 UTC, mspiess commented
Great! 🎉 Thanks for the reviews and detailed comments @jerelmiller and @alessbell!