Failing test for #11400
apollographql/apollo-client pull request #11579
Opened 2024-02-08 22:47 UTC by jerelmiller

I've been able to successfully reproduce the bug described in #11400 in a failing test. I'll use this as my baseline.

From what I can tell, this appears to have broken sometime between [3.4.7 and 3.4.8](https://github.com/apollographql/apollo-client/compare/v3.4.7...v3.4.8).

2024-02-09 15:16 UTC, phryneas requested changes

2024-02-09 15:16 UTC, phryneas commented on src/core/ObservableQuery.ts
> +
I'd love it if this were the solution, but this will reset deferred results in the second call to `getCurrentResult`.

Here is a failing test:

```ts
    it.only("should handle multiple calls to getCurrentResult without losing data", async () => {
      const query = gql`
        {
          greeting {
            message
            ... on Greeting @defer {
              recipient {
                name
              }
            }
          }
        }
      `;

      const link = new MockSubscriptionLink();

      const client = new ApolloClient({
        link,
        cache: new InMemoryCache(),
      });

      const obs = client.watchQuery({ query });
      const stream = new ObservableStream(obs);

      setTimeout(() => {
        link.simulateResult({
          result: {
            data: {
              greeting: {
                message: "Hello world",
                __typename: "Greeting",
              },
            },
            hasNext: true,
          },
        });
      });

      {
        const result = await stream.takeNext();
        expect(result.data).toEqual({
          greeting: {
            message: "Hello world",
            __typename: "Greeting",
          },
        });
        expect(obs.getCurrentResult().data).toEqual({
          greeting: {
            message: "Hello world",
            __typename: "Greeting",
          },
        });
        // second call to `getCurrentResult`
        expect(obs.getCurrentResult().data).toEqual({
          greeting: {
            message: "Hello world",
            __typename: "Greeting",
          },
        });
      }
    });
```

2024-02-09 15:32 UTC, jerelmiller commented on src/core/ObservableQuery.ts
> +
Thank you. I was going to dig more into possible fail scenarios today since `@defer` uses `partial`. Thanks for accelerating my findings 🙂

2024-02-09 19:01 UTC, rchasman commented on src/core/ObservableQuery.ts
> +
We ran into this issue after updating the package, and releasing it yesterday. Thank you for working on this fix!

2024-02-13 17:07 UTC, phryneas commented on src/core/__tests__/ObservableQuery.ts
> +      setTimeout(() => {
Do you need the `setTimeout` - and if yes: I think that's already a functionality of `simulateResult` if you give it a `delay`.

2024-02-13 17:13 UTC, jerelmiller commented on src/react/hooks/__tests__/useQuery.test.tsx
> +    await expect(Profiler).not.toRerender();
One minor difference with this fix vs prior behavior is that previously the errored `useQuery` would be refetched when the partial data result was written. Now if the query has errored but we get a partial cache update, the network request does not happen.

I _think_ that's ok as the network request felt a bit surprising, but its also difficult to tell if anyone relies on this "auto refetch" behavior right now.

You can see this particular change in behavior for this test in https://github.com/apollographql/apollo-client/pull/11579/commits/1d7629dd397fb3de90f8f9f4aaeda2bf3f4d0ec6

2024-02-13 20:14 UTC, jerelmiller commented on src/core/__tests__/ObservableQuery.ts
> +      setTimeout(() => {
Good catch! I blindly copied this from `useQuery` tests 🙈. Done in [b497ebd](https://github.com/apollographql/apollo-client/pull/11579/commits/b497ebd6a808d5e5da4b9214681e6b6cceb09484)

2024-02-13 20:17 UTC, jerelmiller commented
/release:pr

2024-02-13 21:30 UTC, jerelmiller commented
The more I work with this, the more I think this fix is impossible without introducing some way to determine when a result is partial due to a deferred query. I wanted to write down my notes on where I'm at right now, partially for my own reminder, and for others interested in why this bug is actually trickier to solve than meets the eye.

---

There are 3 areas of the code that are candidates for change to fix this (likely more, but these seem like the right "hot spots" to look at when addressing this bug):
* `ObservableQuery.getCurrentResult` - This function returns the latest reported value by the query.
* `ObservableQuery.reportResult` - This function is called when a new query result is emitted, either by a cache update, or by an update from the network request (i.e. its the callback used for `concast.subscribe`). It takes the result, sets it as the latest result on `ObservableQuery`, and reports that value to all the subscribers of that query.
* `QueryInfo.setDiff` - This function is called each time a cache update triggers a broadcast. We take the reported value, set it as the last value, then verify it differs from the previous result before reporting that value to its connected `ObservableQuery` (the `oqListener` in the code).

I've attempted patching in all 3 locations, each that present regressions in some form. 

**`QueryInfo.setDiff`**

The PR at the time of this writing patches `QueryInfo.setDiff` to avoid reporting the result if its partial and it doesn't tolerate partial data results. This works well for the most part, but falls down if the errored query attempts to refetch after the error. We see the initial bug pop up where a partial data result is reported to `useQuery`, due to the fact that we store any changes to the cache `diff` on the `QueryInfo` instance unconditionally. In my testing so far, conditionally setting the latest diff results in some new bugs.

**`ObservableQuery.getCurrentResult`**

This seems like a natural replace to avoid returning results that are partial when `returnPartialData` is false. The problem becomes when we try and get results for deferred queries. We "reuse" the `partial` property when reporting incremental results until the entire query is loaded. Unfortunately we have no way to differentiate between the result being a partial result reported by the cache vs a partial result reported by a deferred query. This results in bugs where multiple calls to `getCurrentResult` do not properly hold onto the previous result.

**`ObservableQuery.reportResult`**

This is the "in between" of the two approaches. Similar to `QueryInfo.setDiff`, we could avoid reporting on a partial result if this function detects one. Unfortunately like `getCurrentResult`, we have no way to differentiate between the reported result being a part of a cache update or an incremental result on a deferred query, so there is risk that we aren't able to set partial results when necessary.

2024-02-13 22:21 UTC, jerelmiller commented
/release:pr

2024-02-13 22:42 UTC, jerelmiller commented on src/react/hooks/__tests__/useQuery.test.tsx
> +    await expect(Profiler).not.toRerender();
Should this be mentioned in the changelog?

2024-02-14 11:11 UTC, phryneas reviewed
This looks viable to me. Let's talk in our 1:1 later about any problems that you see with the approach.

2024-02-14 11:11 UTC, phryneas commented on src/react/hooks/__tests__/useQuery.test.tsx
> +    await expect(Profiler).not.toRerender();
Yes, I think it should be mentioned in the changelog. 
Maybe add a second changeset to the PR and also classify it as a bug-fix/patch. It's probably better to have as a separate point.

2024-02-14 15:56 UTC, jerelmiller commented on src/core/QueryInfo.ts
> +        this.scheduleNotify();
> Shouldn't this logic be here, too, to be consistent?

Yes! Thats a good callout, though we should be able to omit the `equal(...)` check since it already has a `!diff.complete` check in the outer `if` and `oldDiff.complete` in the inner `if`. Done in [c9b9317](https://github.com/apollographql/apollo-client/pull/11579/commits/c9b93176c52b68c1b9cabb7258c4c0caaa9094d5)

2024-02-14 17:21 UTC, jerelmiller commented on src/react/hooks/__tests__/useQuery.test.tsx
> +    await expect(Profiler).not.toRerender();
Added! https://github.com/apollographql/apollo-client/pull/11579/files#diff-f06f024af37daf816e4ad94d2d4fcc3ca538945d42bfe30be87cec32bbe0b101

2024-02-14 17:22 UTC, jerelmiller commented
@phryneas this should be good to go. I've addressed all the comments and am happy with the diff in this PR. Appreciate the suggestions!

2024-02-15 07:44 UTC, phryneas approved these changes
Then let's get this in :)

2024-02-15 16:23 UTC, merged

2024-03-14 16:08 UTC, av-k commented
If during handling a response is found an error (for example a missed field described inside "typePolicies" for cache), when "useQuery" won't be triggered after the mutation gets the update.

The same code that works in 3.9.4 after the update to 3.9.5 won't work.

FYI @jerelmiller

2024-03-14 16:11 UTC, jerelmiller commented
@av-k do you have a code sample on what you mean? To be honest, I'm having a bit of a difficult time visualizing what you're saying.

Are you perhaps experiencing the thing mentioned at the bottom of the PR description?

> Previously queries with errors would auto refetch when a partial cache update was written that overlapped with the query. This is no longer the case since partial cache updates are ignored and not reported.

2024-03-15 10:09 UTC, av-k commented
@jerelmiller PR description? - it's not about the mentioned problem.

In order to provide a code sample, I will require a demo GraphQL server with a schema containing nested objects within an entity.

So, to be able to reproduce this issue just get an error during handling the response, [so here](https://github.com/apollographql/apollo-client/pull/11579/files#diff-b3b38c672f1360e70ea6146526aad929366d00ce9189334cf70384f4114b8b4bR222):
should be:
```
{
  "diff": {
    "complete": false,
    "missing": [Error: Can't find field 'blablabla' on ENTITY_ID_1 object at new MissingFieldError....],
    "result": {"root": {...}}
  },
  "olddiff": {
    "complete": false,
    "missing": [Error: Can't find field 'blablabla' on ENTITY_ID_1 object at new MissingFieldError....],
    "result": {"root": {...}}
  }
}
```

So if there is an error (for example the incorrect configuration of "typePolicies") - "diff.complete" will be always "false".

2024-03-15 11:02 UTC, phryneas commented
@av-k 
Ich glaube wir verstehen hier einfach das Problem nicht, weil die Fehlerbeschreibung sehr kurz ist.

Koennten Sie das Problem vielleicht noch einmal etwas ausfuehrlicher auf Deutsch beschreiben? 
Vielleicht klappt das besser :)

2024-03-15 19:32 UTC, av-k commented
@phryneas Thank you for the suggestion, but I will still try :)

Unfortunately, I was unable to achieve an error regarding the missing field using the codesandbox example, so I reproduced a simpler case with a field merge error in "typePolicies" (index.js:22).

I'm attaching two identical codesandboxes, the only difference being the versions of @apollo/client.

**@apollo/client v.3.9.5**
https://codesandbox.io/p/sandbox/issue-apollo-client-v-3-9-5-notes-app-vk8jlf

**@apollo/client v.3.9.4**
https://codesandbox.io/p/sandbox/issue-apollo-client-v-3-9-5-notes-app-forked-d3923z

**Steps to reproduce:**
1) Visit the sandbox.
2) Add a Todo.
3) Update the added Todo.

**Actual behavior (in version 3.9.5 - broken):**
After updating the Todo, the label of the Todo is NOT updated.

**Expected behavior (in version 3.9.4 - works):**
After updating the Todo, the label of the Todo is updated.

2024-04-05 07:36 UTC, av-k commented
@jerelmiller is there any updates?
It was possible to reproduce the problem on the provided codesandboxes?

2024-04-05 15:00 UTC, jerelmiller commented
Hey @av-k apologies I lost track of this. I've moved this to https://github.com/apollographql/apollo-client/issues/11759 which will be easier to track.