fix: strengthen MockedResponse.newData type (#11584)
apollographql/apollo-client pull request #11592
Opened 2024-02-13 17:18 UTC by Stephen2

### Checklist:
- [x] If this PR contains changes to the library itself (not necessary for e.g. docs updates), please include a changeset (see [CONTRIBUTING.md](https://github.com/apollographql/apollo-client/blob/main/CONTRIBUTING.md#changesets))
- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

Closes #11584

2024-02-13 17:18 UTC, apollo-cla commented
@Stephen2: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2024-02-13 17:34 UTC, jerelmiller requested changes
Hey @Stephen2 👋 

Thanks so much for this contribution! This is super helpful and I'm honestly surprised we didn't do this sooner. I just had a few comments for you in regards to structuring the tests that I'd like to see changed, but otherwise I'd love to get this in the next patch. Thanks a bunch!

2024-02-13 17:34 UTC, jerelmiller commented on src/testing/core/mocking/__tests__/mockLink.ts
> +
Rather than putting this in the global scope, could you put this into a `describe`/`it` block? Its helpful to see these are in the test runner output. I know it doesn't make a ton of difference in terms of how it succeeds/fails the tests, but its easy to miss these are meant to be type tests otherwise. Doing this also means you can provide a description of the intended behavior which is helpful documentation 🙂 

You can see some examples of how we do this already in a test such as [`useLoadableQuery`](https://github.com/apollographql/apollo-client/blob/ac4ae8498cf8bf63b21dc5886d942976c7dc0eaa/src/react/hooks/__tests__/useLoadableQuery.test.tsx#L4648-L4649).

We are evaluating [`attest`](https://github.com/arktypeio/arktype/tree/beta/ark/attest#readme) at the moment for these types of type tests which will need the `it`/`test` syntax eventually anyways 🙂 (I know its impossible for you to know that, just pointing out why its beneficial to move it into its own test block).

2024-02-13 17:34 UTC, jerelmiller commented on src/testing/core/mocking/__tests__/mockLink.ts
> +// Strongly typed MockedResponse is much more developer friendly
This is technically true of any type, so I'm not sure this comment is super helpful. I like how your other cases describe the intended behavior, so how about something like:

```suggestion
// Requires output type to match query type
```

Besides, I think this would make a better `test(...)` description anyways. See my other comment on converting these to use the `test`/`it` syntax.

2024-02-13 17:34 UTC, jerelmiller commented on src/testing/core/mocking/__tests__/mockLink.ts
> +// @ts-expect-error returning output that doesn't match TData should fail
```suggestion
// @ts-expect-error returns output that doesn't match TData
```

I think the `@ts-expect-error` is a good indicator we expect this to fail, so the "should fail" feels a bit redundant here 🙂

2024-02-13 17:34 UTC, jerelmiller commented on src/testing/core/mocking/__tests__/mockLink.ts
> +// @ts-expect-error destructing input variables that don't exist in TVariables should fail
```suggestion
// @ts-expect-error using input variables that don't exist in TVariables
```

2024-02-13 17:34 UTC, jerelmiller commented on .changeset/dirty-insects-return.md
> +Strengthen MockedResponse.newData type
```suggestion
Strengthen `MockedResponse.newData` type
```

This is so minor I almost didn't add this, but its nice to see at a glance the parts that refer to code 🙈

2024-02-13 17:35 UTC, jerelmiller commented
@Stephen2 for the CircleCI Pipeline, I _think_ you have to login there for those checks to run. Would you mind trying that?

2024-02-13 17:45 UTC, Stephen2 commented
> @Stephen2 for the CircleCI Pipeline, I _think_ you have to login there for those checks to run. Would you mind trying that?

Just did this, created new account, signed in, but still wouldn't let me rerun this pipeline

2024-02-13 17:45 UTC, Stephen2 commented on src/testing/core/mocking/__tests__/mockLink.ts
> +// @ts-expect-error destructing input variables that don't exist in TVariables should fail
done

2024-02-13 17:46 UTC, Stephen2 commented on .changeset/dirty-insects-return.md
> +Strengthen MockedResponse.newData type
done

2024-02-13 17:53 UTC, Stephen2 commented on src/testing/core/mocking/__tests__/mockLink.ts
> +// @ts-expect-error returning output that doesn't match TData should fail
done

2024-02-13 17:54 UTC, Stephen2 commented on src/testing/core/mocking/__tests__/mockLink.ts
> +// Strongly typed MockedResponse is much more developer friendly
done

2024-02-13 17:55 UTC, Stephen2 commented on src/testing/core/mocking/__tests__/mockLink.ts
> +
done

2024-02-13 17:55 UTC, Stephen2 commented
Took some liberties with your comments, but I think I captured the intention. Check it out again, ready for re-review

2024-02-14 20:59 UTC, Stephen2 commented on src/testing/core/mocking/__tests__/mockLink.ts
> +    });
I love that article, and have read it & referenced it to others many times 👍 

I've taken 1 more attempt at formatting this how your repo would like, except using a `setup` function, like the article suggests.

Let me know if it's still off base, and I'll remove it, and place the initialization inside each individual test case, as you'd like.

2024-02-14 21:01 UTC, Stephen2 commented
> Just to double check, is the email address you're using here on GitHub the same as CircleCI?
Yeah, it definitely is.

2024-02-15 16:16 UTC, jerelmiller commented
I'll try pushing a tiny edit to this branch and see if perhaps that will kick it off? So sorry for the inconvenience here!

2024-02-15 16:20 UTC, jerelmiller approved these changes
The `setup` function still feels a tad overabstracted, but I can live with it. Thanks for making these updates! Don't worry about the extract API task failing. I'll get a commit pushed up to make this pass 🙂

2024-02-15 16:21 UTC, jerelmiller commented
@Stephen2 would you mind running `npm run format` and pushing that change? I'd be happy to do it if need be, but I'd prefer you get credit for those lines of code written 🙂

2024-02-15 17:00 UTC, Stephen2 commented
> The `setup` function still feels a tad overabstracted, but I can live with it. Thanks for making these updates! Don't worry about the extract API task failing. I'll get a commit pushed up to make this pass 🙂

Nah it's great, it'll grow on you. xD

You're a good maintainer, I appreciate you.

Hopefully we're ready to squash & merge now, except I think CircleCI needs to be kicked again :(

2024-02-15 17:02 UTC, jerelmiller commented
Argh, that darn circle job. I'll get that kicked off again. As soon as thats green, I'm happy to merge this! We'll get this in the next patch release.

And thanks so much for the kind comments 🙂. Means a lot!

2024-02-15 17:17 UTC, merged