potential fix for #10802
apollographql/apollo-client pull request #11633
Opened 2024-03-01 14:24 UTC by phryneas

This is a potential fix for #10802. I'm not exactly happy with this change yet, but it does solve the problem, so I already wanted to create a PR release.

2024-03-01 14:24 UTC, phryneas commented
/release:pr

2024-03-01 14:47 UTC, phryneas commented
Not sure what's up with GitHub right now, but [the tests are green on this](https://app.circleci.com/pipelines/github/apollographql/apollo-client/23261/workflows/575e96ef-be44-4a8e-b178-31f95f1c98be/jobs/139397?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link&utm_content=summary).

2024-03-12 04:55 UTC, jerelmiller requested changes
I honestly don't have a better idea on how to fix this. Take a look at my refactoring though and I think you'll see we end up with a bit more readable solution.

Would it also be possible to write a test for this? I _think_ my refactoring is equivalent to the change you made here, but I'm not able to check my work against this.

2024-03-12 04:55 UTC, jerelmiller commented on src/core/ObservableQuery.ts
> +        !(fetchPolicy === "network-only" && !this.waitForOwnResult)) ||
I always find the `!(...)` harder to reason about since you have to understand the stuff inside the parens, then negate it. Instead, we can apply [De Morgan's Law](https://en.wikipedia.org/wiki/De_Morgan%27s_laws) which states that "not (A and B)" is equaivalent of "(not A) or (not B)" (essentially distributing the `!` to each clause and changing the `&&` to an `||`.

I find that a bit easier to reason about:

```suggestion
        (fetchPolicy !== "network-only" || this.waitForOwnResult)) ||
```

2024-03-12 04:55 UTC, jerelmiller commented on src/core/ObservableQuery.ts
> +        !(fetchPolicy === "network-only" && !this.waitForOwnResult)) ||
Ok now to dissect this further. For me to understand this better, it helps for me to do a bit of refactoring to remove the function calls and inline the checks here. Let's first start with [inline method](https://refactoring.guru/inline-method) to pull in the body of `skipCacheData` in place of its check.

```ts
((fetchPolicy === "no-cache" ||
  fetchPolicy === "network-only" ||
  fetchPolicy === "standby") &&
  (fetchPolicy !== "network-only" || this.waitForOwnResult))
```

This now makes it possible to see the combinations of `fetchPolicy` checks here.

Digging further, we know that the 2nd clause won't be executed unless the first is truthy. Using this, we can deduce that `fetchPolicy !== 'network-only'` is the same as `fetchPolicy === 'no-cache' || fetchPolicy === 'standby'` since these are the only two fetch policies left over from the first check.

```ts
((fetchPolicy === "no-cache" ||
  fetchPolicy === "network-only" ||
  fetchPolicy === "standby") &&
  (fetchPolicy === "no-cache" || fetchPolicy === 'standby' || this.waitForOwnResult))
```

We now begin to really see some repetition here, notably that when `fetchPolicy === 'no-cache' || fetchPolicy === 'standby'` is true, the whole thing will always be true. 

Let's temporarily refactor out this check to its own variable to make the conditional a bit more obvious.

```ts
const absoluteNoCache =
  fetchPolicy === "no-cache" || fetchPolicy === "standby";

// ...

((absoluteNoCache || fetchPolicy === "network-only") &&
  (absoluteNoCache || this.waitForOwnResult))
```

This makes it obvious that the condition will pass whenever `absoluteNoCache` is `true`. We should be able to pull `absoluteNoCache` out into its own clause and "or" it with the rest of the logic.

```ts
(absoluteNoCache || ((fetchPolicy === "network-only") && (this.waitForOwnResult)))
```

which is the same as the following when removing unnecessary parens

```ts
(absoluteNoCache || (fetchPolicy === "network-only" && this.waitForOwnResult))
```

Now that we've got the common bits together, let's inline the variable back into the conditional

```ts
(fetchPolicy === "no-cache" || fetchPolicy === "standby" || (fetchPolicy === "network-only" && this.waitForOwnResult))
```

Here is the total of the `if` altogether:

```ts
    if (
      // These fetch policies should never deliver data from the cache, unless
      // redelivering a previously delivered result.
      fetchPolicy === "no-cache" ||
      fetchPolicy === "standby" ||
      (fetchPolicy === "network-only" && this.waitForOwnResult) ||
      // If this.options.query has @client(always: true) fields, we cannot
      // trust diff.result, since it was read from the cache without running
      // local resolvers (and it's too late to run resolvers now, since we must
      // return a result synchronously).
      this.queryManager.getDocumentInfo(this.query).hasForcedResolvers
    ) {
```

Unfortunately I have no tests to check my work, but hopefully stepping through this makes sense.

I don't have a great recommendation other than the fix you have here. I'd just suggest doing the above refactoring and if possible, add a test, and I'll be happy with this change.

2024-03-26 09:56 UTC, phryneas commented on src/core/__tests__/ObservableQuery.ts
> -            // network request.
It seems that back in the times of 3.0.0 betas, this was the assumption, which doesn't hold true anymore today (and probably caused this issue).
See https://github.com/apollographql/apollo-client/pull/6353

I'll dig on that a bit more.

2024-03-26 11:22 UTC, phryneas commented on src/core/__tests__/ObservableQuery.ts
> -            // network request.
This was later moved around in 1e5d4f85de55af61b4eb706123591f507d4cce60

2024-03-26 12:09 UTC, phryneas commented on src/core/__tests__/ObservableQuery.ts
> -            // network request.
Hm.. the comment had at that moment in time already been disconnected from code.

2024-03-26 12:16 UTC, phryneas commented on src/core/__tests__/ObservableQuery.ts
> -            // network request.
Yup, this has been removed in 1cd1df9b6aa3c70eed6ddc378451c7f9cc79514a - but the comment survived until today.

2024-03-26 12:23 UTC, phryneas commented
This leaves us with a decision to make:

From what I have unearthed, the current behavior of `network-only` seems to be quite intentional.

It also matches our documentation for `network-only`:

> Apollo Client executes the full query against your GraphQL server, without first checking the cache. The query's result is stored in the cache.
>
> Prioritizes consistency with server data, but can't provide a near-instantaneous response when cached data is available.

Note how this says that it will update the cache, but it doesn't say that the cache updates it.

=> The originally intended way here was that the user has to specify a `nextFetchPolicy` of `cache-first` together with a `fetchPolicy` of `network-only`, and that should also be a solution in the original issue.

We'll have to discuss if we want to keep it that way of introduce what is essentially **yet another** kinda-breaking change to this functionality.

2024-07-05 22:09 UTC, jerelmiller commented
Shoot, it looks like we didn't add notes for the discussion on this PR. Do you remember if we decided this PR should be closed because the current behavior is intentional?

2024-07-08 16:21 UTC, jerelmiller commented
Closing as we decided that the original behavior is intentional, but we see no great path forward without a breaking change.

2024-07-08 16:21 UTC, closed without merging