[docs] Update cache-configuration keyFields docs
apollographql/apollo-client pull request #11778
Opened 2024-04-10 23:32 UTC by smyrick

The docs were missing an explanation of how the keyFields can use false or a function

I would also appreciate a review from the team as I wrote this up from TS types

2024-04-11 16:39 UTC, jerelmiller requested changes
Really appreciate the contribution here! Having the `keyFields` function example is super helpful and not sure why we didn't have it before.

There are a few inaccuracies though that I'd love to correct before merging. Mind making those changes? I'd be happy to get this in afterwards.

2024-04-11 16:39 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +      keyFields: false,
This isn't quite true. The empty array was actually the right thing here before in regards to the value being a singleton. `false` disables normalization, so the object will be embedded in the parent. Here's are the differences in what the cache would look like with these two:

`keyFields: false`
```js
ROOT_QUERY: {
  "allProducts": {
    __typename: "AllProducts",
    // ... other fields
  }
}
```

`keyFields: []`
```js
ROOT_QUERY: {
  "allProducts": {
    __ref: "AllProducts:{}",
  }
},
"AllProducts:{}": {
  __typename: "AllProducts",
  // ...other fields
}
```

`keyFields: []` has some advantages from the perspective of the `readFragment`/`watchFragment`/`useFragment` APIs since these are now accessible without the need to go through the `ROOT_QUERY` to get the result.

If you want a more real-world example, check out [these type policies](https://github.com/apollographql/spotify-showcase/blob/e52b28974f04318c70c31cbef7b1df4a8600468d/client/src/apollo/client.ts#L93-L97) in the Spotify showcase.

You can read more about disabling normalization with `keyFields: false` in this doc as well: https://www.apollographql.com/docs/react/caching/cache-configuration#disabling-normalization

2024-04-11 16:39 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +        }
```suggestion
      keyFields: (store, context) => {
        if (store.location == "United States") {
          // We can return the array of field specifiers
          return ["state", "storeNumber"];
        } else if (store.location) {
          // Or we can return another function to calculate the cache key as a string
          return ((obj) => "prefix:" + obj.location + obj.storeNumber);
        } else {
          // Or we can indicate that this type is a Singleton
          return false;
        }
```

[nit] Naming this argument after the type might help associate the value with what it is.

2024-04-11 16:39 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +* The `AllProducts` type illustrates a special strategy for a **singleton** type. If the cache will only ever contain one `AllProducts` object and that object has _no_ identifying fields, you can pro
Let's leave this the same as it was before. Perhaps another bullet point stating that `keyFields: false` disables normalization? It doesn't have anything to do with singletons though.

2024-04-11 16:39 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +          return ((obj) => "prefix:" + obj.location + obj.storeNumber);
I can't seem to find anything that supports the idea of returning another function in a `keyFields` function. Here is the [type definition](https://github.com/apollographql/apollo-client/blob/8bc7d4d406402962bf5151cdd2c5c75c9398d10c/src/cache/inmemory/policies.ts#L99-L102) of `KeyFieldsFunction` in our code:

```ts
export type KeyFieldsFunction = (
  object: Readonly<StoreObject>,
  context: KeyFieldsContext
) => KeySpecifier | false | ReturnType<IdGetter>;
```

`IdGetter` is a function that returns `string | undefined`. Looking at the implementation of our type policies, I also don't see anything to support the idea of returning a function here.

Can we omit this or change the example?

2024-04-11 18:54 UTC, smyrick commented on docs/source/caching/cache-configuration.mdx
> +          return ((obj) => "prefix:" + obj.location + obj.storeNumber);
`IdGetter` is exactly what I was trying to implement here. `KeyFieldsFunction` can return an `IdGetter` which itself is a function that returns a string. Is that not how that would be implemented?

2024-04-11 19:00 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +          return ((obj) => "prefix:" + obj.location + obj.storeNumber);
The key difference here though is we are using `ReturnType<IdGetter>`, not `IdGetter`, so we are getting the return type from `IdGetter` rather than the function type itself.

Here's an example:

```ts
type ReturnValue = ReturnType<(value: string) => number | undefined>
//   ^? number | undefined
```

See [this playground](https://www.typescriptlang.org/play?#code/C4TwDgpgBAShwFcBOA7AagQwDYOgXlnmRQBVwIAeACgDdtcAuKAZ2CQEsUBzASijwB8LNpy5QAPlAQoAJhABmnCDIEAoAPTqo2gHoB+IA) for an example. 

In this case `ReturnType<IdGetter>` is `string | undefined`, so if we flatten the types, `KeyFieldsFunction` would return `KeySpecifier | false | string | undefined`.

2024-04-11 21:56 UTC, adamesque commented on docs/source/caching/cache-configuration.mdx
> +          return false;
In a `keyFields` function, returning `false` would indicate that this particular _instance_ of a type shouldn't be normalized and instead embedded in the parent, correct?

2024-04-11 22:00 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +          return false;
@adamesque thats correct! Here is a test that demonstrates returning `false` from a `keyFields` function. You can see the cache is non-normalized: https://github.com/apollographql/apollo-client/blob/8bc7d4d406402962bf5151cdd2c5c75c9398d10c/src/cache/inmemory/__tests__/policies.ts#L5543-L5622

2024-04-11 22:01 UTC, adamesque commented on docs/source/caching/cache-configuration.mdx
> +        if (store.location == "United States") {
I'm curious about this. Based on [this comment](https://github.com/apollographql/apollo-client/blob/286ff15fd9c095b02d2709d87d682f0894b50d13/src/cache/inmemory/policies.ts#L80-L90) I'd expect this function to call `context.readField('location')` here to safely lookup the location. Is that accurate?

2024-04-11 22:06 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +        if (store.location == "United States") {
Let me phone a friend 😆. I haven't worked too closely with the internals of `keyFields`, but I believe your statement is accurate.

2024-04-11 22:08 UTC, adamesque commented on docs/source/caching/cache-configuration.mdx
> +          return false;
Nice! Million-dollar question — is that true for any falsy value? It _seems_ like it based on [this](https://github.com/apollographql/apollo-client/blob/286ff15fd9c095b02d2709d87d682f0894b50d13/src/cache/inmemory/policies.ts#L404) or [this](https://github.com/apollographql/apollo-client/blob/286ff15fd9c095b02d2709d87d682f0894b50d13/src/cache/inmemory/policies.ts#L782)?

2024-04-11 22:16 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +          return false;
I _think_ thats accurate, but I'd like to verify myself before giving a definitive yes. Intuitively it would make sense that if we don't get an identifier for a particular store object that we'd consider it non-normalized, but again, let me check to make sure thats accurate.

2024-04-11 22:31 UTC, smyrick commented on docs/source/caching/cache-configuration.mdx
> +          return ((obj) => "prefix:" + obj.location + obj.storeNumber);
Ah, got it. Thanks for the explainer. I didn't know `ReturnType<>` actually was able to do that

2024-04-12 16:38 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +          return false;
@adamesque just tried this out and I can confirm it seems that any falsey value will be treated as `false` and won't normalize the record.

2024-04-12 17:01 UTC, adamesque commented on docs/source/caching/cache-configuration.mdx
> +          return false;
Great, thanks! I don't know exactly why `ReturnType<IdGetter>` is important to include in the return type union but it would definitely be clearer if it was just `KeySpecifier | false`.

2024-04-12 17:06 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +        if (store.location == "United States") {
Ok asked around and played around with this myself a bit more.

The first argument seems to reference the record itself that will be written to the store. It doesn't however include any subselected fields, only scalar fields. The key thing here though is that it contains aliases from your query. `context.storeObject` on the other hand de-aliases the record so its keys contain the actual field names. `context.readField` also operates on the de-aliased field name. `context.readField` would also theorectically follow refs, but in my testing, it doesn't look like I could get to any, so I think `context.storeObject` and `context.readField` are more-or-less the same.

So I believe `context.storeObject` and `context.readField` is actually the safer route because you won't need to worry about breakages due to field aliasing. That being said, I talked to Ben and his advice was this:

> All of this leads me to discourage using a `keyFields` function, since the array version automatically gets the de-aliasing logic right, but sometimes you need the control the function version provides.

Does that help?

2024-04-12 17:07 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +          return false;
I agree! I'll see if we can simplify that type.

2024-04-12 17:08 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +        if (store.location == "United States") {
Oh and I was given https://github.com/apollographql/apollo-client/pull/8996 to look at. The PR description has some good stuff about `keyFields` functions and de-aliasing in it as well 🙂

2024-04-13 02:24 UTC, smyrick commented on docs/source/caching/cache-configuration.mdx
> +      keyFields: false,
I updated the section on this to just demo empty array and `false` now. 

TBH I am just reading your comments and adding this in so feel free to commit yourself any clarification or suggestions

2024-04-13 02:31 UTC, jerelmiller commented on docs/source/caching/cache-configuration.mdx
> +      keyFields: false,
That works for me! Thanks for the help in making some updates here to make this more clear. Much appreciated!

2024-04-13 02:33 UTC, smyrick commented
@jerelmiller @adamesque I made some doc updates, but feel free to add inline suggestions or more context as needed

2024-04-17 16:21 UTC, adamesque commented on docs/source/caching/cache-configuration.mdx
> +      }
Based on this [comment](https://github.com/apollographql/apollo-client/pull/11778#discussion_r1562878651), I believe this should be `context.readField("location")` or `context.storeObject.location` and we should steer folks away from using the first arg altogether since it represents the raw server response which includes aliased fields and won't follow refs (aka instead of refs to other nested cache objects you'll only get the fields selected).

2024-04-17 16:22 UTC, adamesque commented on docs/source/caching/cache-configuration.mdx
> +      }
I see you mention this in a later bullet point, but my worry is that folks will read the code example and not the following notes and be surprised.

2024-04-22 09:15 UTC, phryneas commented on docs/source/caching/cache-configuration.mdx
> +          return false;
`false` is explicitly checked for in some situations (e.g. https://github.com/apollographql/apollo-client/blob/29a9855a1f33361b058b20b56ef52781c4e37d02/src/cache/inmemory/policies.ts#L463-L464 ) so that's not the same as `undefined`.

`undefined` would then end up in ` || simpleKeyArgsFn`, so we'd get the default behaviour.

`ReturnType<IdGetter>` *does* add `undefined` (which is a bit pointless, given it's an optional value anyways) and `string`, which is important - the `keyFn` function can not only return an array of field names, but also directly an identifier (although I'd advise against using that in many situations and leave the field-reading to the InMemoryCache instead).

=> The type is not written ergonomically, but I believe there's nothing we can really remove here.

2024-04-23 08:51 UTC, phryneas commented on docs/source/caching/cache-configuration.mdx
> +        if (context.readField("location", context.readField("state"))) {
Do we really have an object with

```json
{
  "__typename": "Location",
  "location": {
    "state": "New York"
  }
}
```

here?

If we had something more like

```json
{
  "__typename": "Location",
  "state": "New York"
}
```
I believe this would need to be `context.readField("state")`.

2025-04-14 22:30 UTC, svc-apollo-docs commented
### 🛠️ Docs preview building...

The preview is currently being built.

**Build ID**: b730ec5e22573f1ffdcdd497

2025-04-16 00:44 UTC, jerelmiller approved these changes
Looks good to me! Thanks for adding this 🎉

2025-04-16 00:45 UTC, merged