Keep fragment when it doesn't have @client directive
apollographql/apollo-client pull request #6322
Opened 2020-05-20 16:05 UTC by mtsmfm

### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

---

Fix https://github.com/apollographql/apollo-client/issues/6311

2022-11-28 18:07 UTC, jerelmiller requested changes
Hey @mtsmfm 👋! Thanks for your patience! I've noticed your 2 tests seem to conflict in logic with each other. I'd like to see if we can keep the behavior as consistent as possible. I see this is related to an issue that worked in v2 but not in v3. Can you confirm this is still an issue in the latest versions of Apollo (v3.7.1 at the time of this writing)?

Feel free to close or amend this PR as need be. Thanks!

2022-11-28 18:07 UTC, jerelmiller commented on src/utilities/graphql/__tests__/transform.ts
> +      }
I'm not quite sure this is the behavior we want here. In fact, this test seems to conflict with the logic in the second test. A fragment with a `__typename` only selection is valid GraphQL as proven by the test below. In this case, I think the `isLoggedIn` field should be the only one removed, but the `toBeRemoved` fragment should remain with `__typename` as the only field selection.

2022-12-04 01:24 UTC, chloe-glowy commented on src/utilities/graphql/__tests__/transform.ts
> +      }
@jerelmiller That makes sense to me but do you know why the code to remove fragments that have `__typename` as their only field after pruning fields with the `@client` directive might have been added in the first place? It was added in a large PR (#4338) and I can't figure out from reading that PR why this particular behavior was added.

Maybe in some scenarios `__typename` fields are added automatically?

2023-02-02 17:43 UTC, alessbell commented on src/utilities/graphql/__tests__/transform.ts
> +      }
Looks like this test exists to preserve existing behavior whereby a fragment is removed if it contains fields annotated with `@client` _in addition to_ `__typename`.

We do add `__typename` by default (via [addTypename](https://www.apollographql.com/docs/react/caching/cache-configuration/#addtypename) which defaults to true), though I'm not clear how that would impact this change.

Though I'm not clear on the original reasoning for removing fragments that contain `@client` as well as `__typename`, ensuring backward-compatibility seems like the best way to get this fix in.

2023-02-02 18:15 UTC, alessbell commented on src/__tests__/local-state/resolvers.ts
> -        ...Foo2
This test was added recently and has a `__typename`-only fragment which would have been previously removed from the document by the buggy behavior we're fixing :) It can simply be omitted here.

2023-02-03 21:54 UTC, alessbell commented
Doing some tidying before merging this: I cherry-picked the commit from https://github.com/apollographql/apollo-client/pull/7488 since the PRs are somewhat related (and both needed minor updates based on when they were opened), and just removed the `removeTypenameOnlyFragment` option which wasn't necessary from what I can see.

The only outstanding item here is I'd like to move the second call to `visit` back out of `removeDirectivesFromDocument` since this performs an entire second traversal of the document AST, and `removeDirectivesFromDocument` is called (via other fns) in relatively hot paths of the library. That and I forgot to also cherry-pick the changeset from #7488 :)

2023-02-06 20:35 UTC, alessbell commented
After discussing with @benjamn, I've done some light refactoring here (there are more improvements we can make in the future, but for now I was able to remove one call to `visit`).

This PR is ready for review 😄

2023-02-10 16:42 UTC, alessbell commented
@benjamn after our last chat about this I added some tests where the fragment appears before the query, and the one failing test is for `should remove @client and __typename only fragment`, but this test is also failing on `main`. (The fragment spread is never removed because it has not yet been registered via `fragmentSpreadsInUse`, not one introduced by removing the `visit` from `removeClientSetsFromDocument`.)

Since this is the existing behavior, I'll keep the test with a comment to the issue I've opened https://github.com/apollographql/apollo-client/issues/10539 and `.skip` it for now. Otherwise I think this PR is ready for a final review 👍

2023-02-15 19:30 UTC, alessbell commented
Closing in favor of https://github.com/apollographql/apollo-client/pull/10560.

2023-02-15 19:30 UTC, closed without merging