Document undefined `data` cases for queries and mutations
apollographql/apollo-client pull request #6549
Opened 2020-07-06 03:08 UTC by PowerKiKi

Unfortunately `data` legitimately can be undefined in some edge cases
for both queries and mutations. It is slightly annoying because in most
normal cases it will never be undefined, but this cannot be reflected in
typing as we have to also support those edge cases.

So end-user will have to use `result.data!.foo.bar` syntax in most cases
if they enable strict null checks.

Fixes #5662

### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

2020-11-05 00:39 UTC, PowerKiKi commented
@benjamn, in 56ae475ecac6eac7a58dc2f069e248f6a980632a you made query results non-optional again. This is a great improvement. So I rebased this PR to only document optional result mutations. Because unfortunately they can still be undefined AFAIK, and it might be a bit counter-intuitive for newcomers.

2020-12-21 05:30 UTC, PowerKiKi commented
Rebased on top of latest main.

@StephenBarlow, you've been auto-assigned to review this PR. Did you get a chance to have a look at it ?

2022-01-18 08:35 UTC, PowerKiKi commented
@benjamn, might I ask you to give this a quick review ? it should be rather straightforward

2022-05-24 09:40 UTC, PowerKiKi commented
Rebased on main. I would be nice to merge this and get rid of useless test case.

2022-08-30 03:52 UTC, MrDoomBringer commented
Hey @PowerKiKi, thanks so much for keeping this PR open! The code comments/documentation seem good to me.

My only ask is that it might be better to add a test affirming the edge case (i.e. setting `errorPolicy` to ignore and checking for an undefined `data`,) rather than removing the existing test.

2022-08-30 08:41 UTC, PowerKiKi commented
@MrDoomBringer, I added a test, although I am not so sure it brings much value, and rebased the whole thing.

2022-11-19 12:35 UTC, PowerKiKi commented
@jerelmiller, since you are cleaning up PRs, this should be a no-brainer to merge, because it doesn't actually change production code, only tests and docs.

The failing CI seems unrelated and running `npm run test:ci` locally finishes without error.

2022-11-21 17:49 UTC, jerelmiller requested changes

2022-11-21 17:49 UTC, jerelmiller commented on src/__tests__/mutationResults.ts
> -    itAsync('mutate<MyType>() data should never be `undefined` in case of success', (resolve, reject) => {
I think we should still keep this case around. I see this as a fundamentally different test since this tests the "success" case with the default error policy while the test you've introduced checks how the `ignore` error policy works with the result.

Would you be willing to restore this test and make yours a separate distinct test?

2022-11-21 17:49 UTC, jerelmiller commented on src/__tests__/mutationResults.ts
> +          observer.next({
Since we are checking an error policy in this test, could we instead model the response here with an error to check the behavior? I'd argue that `data: undefined` is an impossible success case in GraphQL if the server is implemented to spec. Per the [spec:](https://spec.graphql.org/October2021/#sec-Errors)

> If the `data` entry in the response is not present, the `errors` entry in the response must not be empty. It must contain at least one error. The errors it contains should indicate why no data was able to be returned.

In this case, I would expect this test to check that an `errorPolicy: 'ignore'` would result in both `data: undefined`, and `error: undefined` in the result.

Would you mind updating this test to return an error and check the result of that?

2022-12-11 18:56 UTC, mccraveiro commented on src/core/ApolloClient.ts
> +   * error. In some cases `data` might be undefined, for example when `errorPolicy` is set
```suggestion
   * error. In some cases both `data` and `errors` might be undefined, for example when `errorPolicy` is set
```

2024-02-02 23:44 UTC, jerelmiller commented on src/core/ApolloClient.ts
> +   * error. In some cases `data` might be undefined, for example when `errorPolicy` is set
Thanks for the suggestion! Applied it in [d5208d8](https://github.com/apollographql/apollo-client/pull/6549/commits/d5208d85d08f5a4d00d7f8aca092cf2809ace21e)

2024-02-02 23:44 UTC, jerelmiller commented on src/__tests__/mutationResults.ts
> -    itAsync('mutate<MyType>() data should never be `undefined` in case of success', (resolve, reject) => {
Restored in [85e1cd9](https://github.com/apollographql/apollo-client/pull/6549/commits/85e1cd91e38fd7eab7f374c1adb936f8da2ae9f4)

2024-02-02 23:48 UTC, jerelmiller commented on src/__tests__/mutationResults.ts
> +          observer.next({
Resolved in [0a8689e](https://github.com/apollographql/apollo-client/pull/6549/commits/0a8689ebea21b795dc01d15aa8cf0013d455dd2e)

2024-02-02 23:49 UTC, jerelmiller approved these changes
Sorry it took so long to get back to this @PowerKiKi! Appreciate the willingness to add an additional test here to document this behavior. I'll get this merged!

2024-02-02 23:56 UTC, merged

2024-02-05 05:05 UTC, PowerKiKi commented
Thank you for helping me with this. I can finally close the browser tab I kept open for the past 3.5 years :nerd_face:

2024-02-05 18:52 UTC, jerelmiller commented
Wow 3.5 years?!?! Thats some dedication! I feel like we need to toast to that 🥂. This was our oldest opened PR at the time, so I'm glad we were able to get this in!