Adjust SSR restore docs to parse stringified cache state
apollographql/apollo-client pull request #7036
Opened 2020-09-17 18:16 UTC by hwillson

Small tweaks to make sure the SSR cache `restore` examples show to `parse` the JSON stringified cache state.

Fixes #6996

2020-09-18 15:06 UTC, benjamn requested changes
I don't think this quite works, unfortunately. Let's take this opportunity to make sure our cache rehydration recommendations are consistent and correct.

2020-09-18 15:06 UTC, benjamn commented on docs/source/caching/advanced-topics.mdx
> +cache: new Cache().restore(JSON.parse(window.__APOLLO_STATE__))
I don't think this is quite right, because `window.__APOLLO_STATE__` will not be a string given the strategy we recommend for initializing it above:
```js
`<script>
  window.__APOLLO_STATE__=${JSON.stringify(cache.extract()).replace(/</g, '\\u003c')}
</script>`
```
This code _interpolates_ the string returned by `JSON.stringify` into the `<script>` tag, without enclosing quotes, so the code ends up looking like
```html
<script>
  window.__APOLLO_STATE__ = {...}
</script>
```
rather than
```html
<script>
  window.__APOLLO_STATE__ = "{...}"
</script>
```
If we want to make `window.__APOLLO_STATE__` be a string, I think there needs to be a second stringification, to produce a new string that preserves the enclosing quotes of the first string:
```js
`<script>
  window.__APOLLO_STATE__=${JSON.stringify(JSON.stringify(cache.extract()).replace(/</g, '\\u003c'))}
</script>`
```
Then (and only then) will it make sense to do `JSON.parse(window.__APOLLO_STATE__)`.

2020-09-18 16:04 UTC, hwillson commented on docs/source/caching/advanced-topics.mdx
> +cache: new Cache().restore(JSON.parse(window.__APOLLO_STATE__))
Good catch @benjamn - hmm, maybe we can adjust the recommendation (since calling `stringify` twice here looks odd).

2020-09-19 12:39 UTC, hwillson commented on docs/source/caching/advanced-topics.mdx
> +cache: new Cache().restore(JSON.parse(window.__APOLLO_STATE__))
Wait - why are we duplicating this info between 2 parts of the docs? I don't see a lot of value in having the `Server side rendering` section in the cache docs, when we have more details (that are accurate) in the `Performance > Server-side rendering` docs. And the cache docs just give a snippet, then direct people to the larger docs anyways. I'm all for removing this section completely. Any objections @benjamn?

2020-09-25 17:51 UTC, benjamn commented on docs/source/caching/advanced-topics.mdx
> +cache: new Cache().restore(JSON.parse(window.__APOLLO_STATE__))
@hwillson I support this simplification!

2020-09-27 11:53 UTC, hwillson commented on docs/source/caching/advanced-topics.mdx
> +cache: new Cache().restore(JSON.parse(window.__APOLLO_STATE__))
Great, done @benjamn!

2020-12-11 21:14 UTC, StephenBarlow commented
Incorporated into #7442

2020-12-11 21:14 UTC, closed without merging