Disable missing cache fields warning when using returnPartialData
apollographql/apollo-client pull request #7055
Opened 2020-09-22 19:30 UTC by hwillson

If `returnPartialData` is set to `true` for a query, disable the `QueryManager` `Missing cache result fields` warning, since developers have explicitly stated they want to work with partial data.

Fixes #7040

2020-09-22 23:17 UTC, benjamn requested changes
Just a couple of 🥦  suggestions. Not trying to make more work for you, by the way—let me know if you run out of time to keep working on this, and I'm happy to take over.

2020-09-22 23:17 UTC, benjamn commented on src/core/__tests__/QueryManager/index.ts
> +  describe('warnings', () => {
```suggestion
  describe('missing cache field warnings', () => {
```
A little more specific?

2020-09-22 23:17 UTC, benjamn commented on src/core/__tests__/QueryManager/index.ts
> +      const query1 = gql`
Since you have this handy `describe` scope for these two tests, and some of the local variables used by the two tests seem the same (`query1`, `query2`, etc), would you mind hoisting the common variables up into the `describe` scope?

2020-09-22 23:17 UTC, benjamn commented on src/core/QueryManager.ts
> +          !returnPartialData) {
Already in scope, great!

2020-09-23 12:10 UTC, hwillson commented on src/core/__tests__/QueryManager/index.ts
> +      const query1 = gql`
@benjamn I'm happy to change this, but just a heads up I did this intentionally. I just find it easier to work with tests that include everything they need to run, in isolation, when it comes to future maintenance, tweaks, refactoring. It's nice to know that you're making changes to data that's only needed by the current test you're modifying, without creating a domino effect of other broken tests. Even though these are the only 2 tests in the new `describe`, if more are added we'll then have to adjust. Which isn't a big deal of course - this is just personal preference - the DRY-ness part of my brain always argues with me when I do this, so I'll happily adjust.

2020-09-23 12:27 UTC, hwillson commented on src/core/__tests__/QueryManager/index.ts
> +      const query1 = gql`
@benjamn how about https://github.com/apollographql/apollo-client/pull/7055/commits/958edbf43bf9851610173d04a52bdd23281224ff as another option?

2020-09-23 14:55 UTC, benjamn commented on src/core/__tests__/QueryManager/index.ts
> +      const query1 = gql`
@hwillson Looks great!

2020-09-23 15:06 UTC, merged