Fix cleanup observer blocking unsubscribe (2) (#6985)
apollographql/apollo-client pull request #7170
Opened 2020-10-15 07:55 UTC by javier-garcia-meteologica

This patch decrements the `addCount` tally so `this.sub` can be unsubscribed and queries are aborted.

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2020-10-15 07:55 UTC, apollo-cla commented
@javier-garcia-meteologica: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2020-10-15 18:24 UTC, dotansimha commented
This is great! Really waiting for this to get merged. We noticed another issue we are investigating now, seems like it's related to GraphQL `subscription`s. We see some weak references that retain in memory.

2020-10-15 19:47 UTC, benjamn commented
@javier-garcia-meteologica Thanks for adding a test!

I was able to fix the test failure by adding a `Promise.resolve().then` delay to the `sub.unsubscribe()` call, which seems important for backwards compatibility (so unsubscribing the last observer and then immediately subscribing another observer does not terminate the underlying subscription).

I also noticed that we were not always terminating `cleanup` observers if there are any left in `this.observers` when the last non-`cleanup` observer is removed by `removeObserver`, so now that's handled better.

2020-10-15 19:49 UTC, benjamn approved these changes

2020-10-15 22:17 UTC, benjamn commented on src/utilities/testing/mocking/mockLink.ts
> +    options: MockLinkOptions = {}
@javier-garcia-meteologica I think this might be a breaking change for anyone who was passing a `boolean` for `addTypename` before, since `MockLink` is a public API. Do you think you could rework your test so that these changes to `MockLink` are not necessary, perhaps by just using `ApolloLink` directly, instead of `MockLink`?

2020-10-15 22:19 UTC, benjamn requested changes
@javier-garcia-meteologica I think this is close, but I'd like to see if we can avoid the changes to `MockLink` (see https://github.com/apollographql/apollo-client/pull/7170#discussion_r505895804). What do you think?

2020-10-16 06:47 UTC, javier-garcia-meteologica commented on src/utilities/testing/mocking/mockLink.ts
> +    options: MockLinkOptions = {}
Of course, I didn't know MockLink was public. Now it's fixed.

2020-10-16 15:27 UTC, benjamn approved these changes
@javier-garcia-meteologica Perfect, thanks!

2020-10-16 15:28 UTC, merged