Reduce confusion about the query component
apollographql/apollo-client pull request #7271
Opened 2020-10-31 08:42 UTC by sharils

The query component has never been mentioned in the page, to reduce confusion, a link to its page would explain that it’s deprecated

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2020-10-31 08:42 UTC, apollo-cla commented
@sharils: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2022-05-05 23:16 UTC, jpvajda requested changes

2022-05-05 23:16 UTC, jpvajda commented on docs/source/data/queries.mdx
> +of this information, we set the `notifyOnNetworkStatusChange` option to `true` so our [query component](../api/react/components/ "Components - Client (React) - Apollo GraphQL Docs") re-renders while
@benjamn @brainkim I'm curious if we should exclude the reference to the deprecated Apollo query component all together and say something like:

we set the `notifyOnNetworkStatusChange` option to `true` so the query component  re-renders while a refetch is in flight:

2022-05-20 16:24 UTC, jpvajda approved these changes

2022-05-20 16:24 UTC, jpvajda commented
I re-reviewed this and I think it's a good idea to link the components docs page in this text. Thanks for the contribution!

2022-05-20 16:24 UTC, jpvajda approved these changes

2022-05-20 17:09 UTC, StephenBarlow approved these changes

2022-05-20 21:51 UTC, jpvajda commented
The checks won't run on this PR, so I opted to open a new one #9747 with this change.

2022-05-20 21:51 UTC, closed without merging