Preserve no-cache fetchPolicy with notifyOnNetworkStatusChange
apollographql/apollo-client pull request #7761
Opened 2021-02-26 19:37 UTC by jcreighton

Fixes #7611. While we want to force delivery for an incomplete cache result with `loading: true`, we should preserve the `no-cache` fetchPolicy. An additional check has been added to avoid resetting the fetch policy to "cache-and-network" when it's set to "no-cache".

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2021-03-02 23:54 UTC, benjamn requested changes
This is on the right track, but I think this will make `notifyOnNetworkStatusChange: true` have no effect when `fetchPolicy: "no-cache"`, which is probably safe/fine in many cases, but potentially not what people expect when they combine those options.

There may be an opportunity here to get rid of the `cache-and-network` trick altogether, since we have access to `options.notifyOnNetworkStatusChange`, `options.fetchPolicy`, and `networkStatus` inside the `switch` statement in `fetchQueryByPolicy`. I believe the `notifyOnNetworkStatusChange` trickery was only applicable for `network-only` and `no-cache` before (since all the other policies deliver an immediate result), so those might be the only two `case`s that need modification. Specifically, the `network-only` case would need to continue behaving like `cache-and-network` when `notifyOnNetworkStatusChange` is enabled, but the `no-cache` case would need to deliver an extra `loading: true` result _without_ reading from the cache.

If this works out, the logic in these important methods will be a lot easier to reason about, which is exciting (to me, at least)!

2021-03-09 20:21 UTC, benjamn commented on src/core/QueryManager.ts
> -    }
Love to see this gone!

2021-03-09 20:23 UTC, benjamn approved these changes
It would be good to add some tests of `no-cache` plus `notifyOnNetworkStatusChange` (in case we don't have enough already), but otherwise I'm happy with this. Thanks for digging into the simplification I suggested!

2021-03-09 20:25 UTC, benjamn commented on src/core/QueryManager.ts
> +          return [resultsFromCache(queryInfo.getDiff()), resultsFromLink(false)];
In 1d798906d2db8db785aaef6328dee65b1a617799, I made sure `queryInfo.getDiff()` will not call `cache.diff` for `no-cache` queries, and added a comment about this line.

2021-03-12 21:31 UTC, merged

2021-09-28 15:48 UTC, kliakos commented
>While we want to force delivery for an incomplete cache result with loading: true

2021-09-28 15:51 UTC, kliakos commented
>While we want to force delivery for an incomplete cache result with loading: true

Shouldn't this be controlled by the `returnPartialData: false` option? I mean, what if I don't want to receive a partial result while `loading: true`, what do I have to do to achieve this, besides `fetchPolicy: 'no-cache'`?

2021-12-03 16:38 UTC, vknez commented
> > While we want to force delivery for an incomplete cache result with loading: true
> 
> Shouldn't this be controlled by the `returnPartialData: false` option? I mean, what if I don't want to receive a partial result while `loading: true`, what do I have to do to achieve this, besides `fetchPolicy: 'no-cache'`?

I agree with @kliakos. This created an issue in our large codebase because the types are not correct anymore. TypeScript expects a non-nullable field, but receives `undefined`, because a partial result was retrieved from cache, even though I never enabled `returnPartialData`. Is this behavior documented somewhere?