Add apollo-link-observable to community links
apollographql/apollo-client pull request #8234
Opened 2021-05-16 12:59 UTC by dragozin

### PR description
Add information about `apollo-link-observable` to client docs.

### About the link
Link that allows you to make side effects of graphql queries using [RxJS](http://github.com/ReactiveX/RxJS)

### Motivation for creating the link
1. Organization of application side effects such as logging, accessing the browser cache, recording analytics events etc.
1. A part of the application with longer lifecycle than a component's one.
1. Creating a complex application business logic.
1. Performing REST queries as a reaction to the graphql query.
1. Local state changes that are triggered by graphql queries.

### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

2021-05-16 12:59 UTC, apollo-cla commented
@dragozin: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2022-05-12 00:04 UTC, jpvajda requested changes
Thanks for wanting to add this to our community links, I had a question for you.

 It's currently tagged as release 0.0.1 and there is no description and no recent updates to the code. I wanted to check if this project is still supported and if you could validate it's ready to be publicly shared within our community links as it might drive a lot of interest to the project.

2022-05-12 08:14 UTC, dragozin commented
Hi, @jpvajda! 

Thank you for your interest in my PR! This is the first release and I'm using the link in my projects. I suppose it might be helpful to other people. I have a description with motivation and examples of use here : https://github.com/dragozin/apollo-link-observable#readme . The project is currently supported by me.

2022-05-12 16:00 UTC, jpvajda commented
@dragozin Thanks for the quick response! We'd be happy to add it to the community links! Thanks for putting in the effort to help Apollo Client users leverage RxJS.

2022-05-12 16:08 UTC, merged