Draft: Remove insignificant whitespace from queries when possible
apollographql/apollo-client pull request #8549
Opened 2021-07-27 15:23 UTC by sarahgp

This PR replaces the native GraphQL print function with one wrapped in `stripIgnoredCharacters` as discussed in https://gitlab.com/gitlab-org/gitlab/-/issues/329895#note_624306089.

**It is currently in a draft state.**

### Checklist:

- [ ] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [ ] Make sure all of the significant new logic is covered by tests

2021-07-27 15:23 UTC, apollo-cla commented
@sarahgp: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2021-07-27 15:25 UTC, sarahgp commented
@hwillson Do you mind taking a look at this and letting me know if it seems like the correct approach? I still need to add tests for this addition, but since I am new to this codebase and not much of a Typescripter, I want to be sure it's roughly correct. Thanks!

2021-07-28 11:03 UTC, hwillson requested changes
This is awesome @sarahgp - thanks very much for working on this! I've outlined one small change regarding keeping the new `print` function internal. Regarding the file size test failure, you can fix this by:

1. Running `npm run bundlesize` in your checkout.
2. After things build, you'll see a message like `FAIL  ./dist/apollo-client.cjs.min.js: 25.63KB > maxSize 25.6KB (gzip)`
3. Increase the `maxSize` property value in the `package.json` to match the increase (in this case bumping it up to `25.7 kB` is  👍).

Thanks again for this!

2021-07-28 17:32 UTC, sarahgp commented on src/link/http/index.ts
> +export { print } from './print';
Yep, no problem!

2021-07-29 16:45 UTC, sarahgp commented
@hwillson I've added the specs and taken this out of draft status.

2021-07-29 16:48 UTC, sarahgp commented on src/link/http/print.ts
> +import { DocumentNode, print as originalPrint, stripIgnoredCharacters } from 'graphql';
I brought my GraphQL version down to `14.1.1` to check that the Typescript compiler did not barf on importing an undefined function — `stripIgnoredCharacters`. It did not, but do you know whether this will cause issues with folks' Webpack builds / have test projects you can test it against? 

We can always `import * as ... ` and deconstruct if we need to, but it seems messy if we don't. 😉

2021-08-03 20:11 UTC, benjamn reviewed
Hello @sarahgp! Thanks for diving into this work.

Since `HttpLink` is a class we expect everyone to use, we have to be super careful about changing its behavior or unnecessarily increasing bundle size (not just new code in `HttpLink`, but also new code from dependencies it imports). In that spirit, I think I'd like to propose a different approach here, which I believe will help answer the questions that have come up so far.

Here's the proposal: what if we made the `print` function _configurable_ as an option to `HttpLink` and `createHttpLink` (and `PersistedQueriesLink` and the other places it's used), the way the [`fetch`](https://www.apollographql.com/docs/react/api/link/apollo-link-http/#customizing-fetch) function currently is?

If we make `print` configurable, the `HttpLink` code will not have to import `stripIgnoredCharacters` from `graphql`, which answers the question about how to safely import `stripIgnoredCharacters`: that's for whoever creates the `HttpLink` to decide.

If the creator of the `HttpLink` decides not to use a custom `print` function (or decides to implement it some other way), the code for `stripIgnoredCharacters` won't have to be bundled, since it isn't explicitly used within the `HttpLink` implementation.

Also, if we make `print` configurable, we won't be changing the default printing behavior on anyone by surprise, which means we can more easily ship this change in any version of Apollo Client, rather than a major version. Even when a change makes a ton of sense like this one does, we can limit the risk of disrupting existing applications by making the new behavior opt-in.

Ideally, I think the signature of this new function should be like the original `print` function (which is a `(node: ASTNode) => string`), but with the original `print` function provided as a second argument:
```ts
import type { ASTNode, print } from "graphql";

export interface HttpOptions {
  // ...
  print?: (
    node: ASTNode,
    originalPrint: typeof print,
  ) => string;
  // ...
}
```
so you have the option of using the original `print` function as part of your custom `print` function.

Implementation-wise, this will probably require changes like passing the configured `print` function as a parameter to the `selectHttpOptionsAndBody` function, rather than importing `print` directly in that module, and your test code will need to configure the `print` function rather than testing the default behavior. I'm sure I'm missing some pointers that you'll discover along the way, but please let us know if you get stuck on anything.

While you're at it, could you also rebase? The [big `release-3.4` branch](https://github.com/apollographql/apollo-client/pull/7399) was merged since you first opened this PR, so there have been some noteworthy changes.

If this is too much to ask given your available time, that's totally fine—just let us know, and we can pick up the reins. Thanks again for pushing this forward!

2021-08-03 22:20 UTC, glasser commented
One suggestion for @benjamn's idea: when documenting the new option (which I suspect goes in both `docs/source/networking/advanced-http-networking.md` and `docs/source/api/link/apollo-link-http.md`), explicitly suggesting `import { stringIgnoredCharacters } from 'graphql'; print: (node, originalPrint) => stripIgnoredCharacters(originalPrint(node))` as a common value for that option would be helpful.

2021-08-13 13:58 UTC, sarahgp commented
@benjamn No problem, I can pick this up again next week.

2021-08-25 11:22 UTC, sarahghp commented
Closing in favor of new PR: https://github.com/apollographql/apollo-client/pull/8549

2021-08-25 11:22 UTC, closed without merging