Fix default options not being set for useQuery
apollographql/apollo-client pull request #9210
Opened 2021-12-16 15:28 UTC by yasharzolmajdi

This PR is intended to solve the issue of default options in client not setting the correct fetch policy in useQuery.

when user doesn't set a fetch policy option in useQuery, it is defaulted to `cache-first` before it attempts to use the default fetch policy that is set in by the client.

the fetch policy hierarchy currently is:

1. user define fetch policy as parameter in useQuery
2. default to `cache-first` in useQuery
_it completely ignores default fetch policy from the client_

with this PR it will be:

1. user define fetch policy as parameter in useQuery
2. user define fetch policy as default value in client
3. default to `cache-first` in useQuery

fixes apollographql/apollo-client#9105

2022-01-02 10:47 UTC, matrinox commented
@yasharzolmajdi Tested this locally and it fixed it for me. The defaultOptions is used on the react hooks from 3.0.1 but I think somewhere between then and 3.5.6 (the one I'm using right now) it stopped using the defaults.

2022-01-04 14:33 UTC, hwillson requested changes
Thanks for this @yasharzolmajdi! If you could add a test(s) to help verify this works as expected (and to help avoid regressions in the future), that would be helpful.

2022-01-05 03:54 UTC, yasharzolmajdi commented
> Thanks for this @yasharzolmajdi! If you could add a test(s) to help verify this works as expected (and to help avoid regressions in the future), that would be helpful.

@hwillson Thanks, I have added a test which currently fails on the main branch but passes with my changes

2022-01-05 11:52 UTC, hwillson approved these changes
Thanks for the test @yasharzolmajdi - this looks great to me. @brainkim @benjamn any objections to merging?

2022-01-10 17:05 UTC, brainkim approved these changes
Thank you for this!

2022-01-10 17:15 UTC, benjamn approved these changes
LGTM, and I can confirm the test fails when the changes are reverted. Thanks @yasharzolmajdi!

2022-01-10 17:19 UTC, merged