Fields without `@client` directive should not be resolved locally
apollographql/apollo-client pull request #9573
Opened 2022-04-01 15:05 UTC by vladar

# Description

This PR fixes an incorrect behavior when local resolvers are executed even for fields without a `@client` directive (reproduction is in the PR tests). This happens because Apollo walks through every single selectionSet in LocalState without checking if this selectionSet actually has a `@client` directive.

This problem also affects query performance significantly in some cases, see [the benchmark](https://github.com/vladar/apollo-at-client-bench).

For server GraphQL results like this:

```js
{
  items: [
    { id: "0", foo: "foo-0" },
    { id: "1", foo: "foo-1" },
    // ...
    { id: "99", foo: "foo-99" },
  ]
  serverOrClient: `server`
}
```

The benchmark shows the following numbers:

```
Without client resolver
100 items x 1,078 ops/sec ±4.69% (58 runs sampled)
1000 items x 128 ops/sec ±5.05% (57 runs sampled)
10000 items x 11.90 ops/sec ±8.81% (55 runs sampled)

With client resolver (before the PR)
100 items x 494 ops/sec ±7.05% (59 runs sampled)
1000 items x 56.21 ops/sec ±6.67% (56 runs sampled)
10000 items x 5.10 ops/sec ±10.75% (28 runs sampled)

With client resolver (after the PR)
100 items x 1,002 ops/sec ±7.57% (60 runs sampled)
1000 items x 123 ops/sec ±7.82% (55 runs sampled)
10000 items x 12.80 ops/sec ±8.15% (58 runs sampled)
```

Fixes #9571

2022-04-01 15:05 UTC, apollo-cla commented
@vladar: Thank you for submitting a pull request! Before we can merge it, you'll need to sign the Apollo Contributor License Agreement here: https://contribute.apollographql.com/

2022-05-19 14:16 UTC, vladar commented
@benjamn @brainkim A gentle ping on this PR - performance implications of even a single `@client` field are quite significant (especially noticeable for frequent subscriptions with big payloads). I think it deserves to be addressed.

2023-01-27 23:54 UTC, jerelmiller requested changes
Hey @vladar 👋 !

Thanks so much for your patience. I really like the work you've done here and think this will be a tremendous improvement to the client. I've left only minor bits of feedback for you, but overall really like the strategy you took here. Glad its also been confirmed that this solution [works for others](https://github.com/apollographql/apollo-client/issues/9571#issuecomment-1097028531). I'd like to get this merged as soon as you're able to address some of the feedback. Thanks again for the contribution!

2023-01-27 23:54 UTC, jerelmiller commented on src/core/LocalState.ts
> +    const isNode = (node: ASTNode | readonly ASTNode[]): node is ASTNode => !Array.isArray(node);
Since this function operates exclusively on an `ASTNode` type, I'd suggest naming this to something like `isSingleNode` to better capture that you're trying to narrow down to only the `ancestors` that aren't multiple nodes.

2023-01-27 23:54 UTC, jerelmiller commented on src/core/LocalState.ts
> +  private selectionsToResolve = new WeakMap<ExecutableDefinitionNode, Set<SelectionNode>>()
I see that in `ExecContext`, you're also declaring a property called `selectionsToResolve`, but its type differs from this one. I was a bit confused at certain points looking through this PR since these are named the same but have different value types.

If I'm understanding this property correctly, this acts more of a cache so that you can avoid recomputing selection sets correct? In that case, you might consider naming this something like `selectionsCache` which I think better serves its intention.

2023-01-30 17:00 UTC, jerelmiller commented on src/__tests__/local-state/resolvers.ts
> +        bar: () => ({ __typename: `Bar`, baz: false }),
Updated in [ff1c69f](https://github.com/apollographql/apollo-client/pull/9573/commits/ff1c69f7a722f6a3ed6754f605569295ff32f039)

2023-01-30 17:01 UTC, jerelmiller commented on src/core/LocalState.ts
> +    const isNode = (node: ASTNode | readonly ASTNode[]): node is ASTNode => !Array.isArray(node);
Updated in [597e0df](https://github.com/apollographql/apollo-client/pull/9573/commits/597e0dfb8d2c397fb16e4c82dff01ba647c8a944)

2023-01-30 17:10 UTC, jerelmiller approved these changes
@vladar thanks so much again for the contribution! Looking forward to getting this released 🎉 🎉

2023-01-30 17:16 UTC, merged