Update the getting started guide to use the FlyBy API
apollographql/apollo-client pull request #9851
Opened 2022-06-24 00:50 UTC by rkoron007

The Apollo Client [Getting started](https://www.apollographql.com/docs/react/get-started) article currently relies on a Codesandbox instance that queries the Coinbase API. We decided that it'd be better to better to update this article to use an API that Apollo manages and updates (I ended up going with the [FlyBy API ](https://odyssey-flyby.netlify.app/) from [Voyage I](https://www.apollographql.com/tutorials/voyage-part1/intro-to-federation)).

2022-06-24 00:59 UTC, rkoron007 commented
@jpvajda Wasn't sure if you wanted to review this too— but wanted to let you know we were updating the "Getting Started" guide! (I also added a note about downgrading `graphql` for those running into this problem: https://github.com/apollographql/apollo-client/issues/9659 )

2022-06-24 20:51 UTC, StephenBarlow requested changes
Looking good! Finished a feedback pass

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +> For an introduction to the entire Apollo platform, [check out **Odyssey**, Apollo's new learning platform](https://odyssey.apollographql.com?utm_source=apollo_docs&utm_medium=referral).
```suggestion
> For an introduction to the entire Apollo platform, [check out **Odyssey**, Apollo's interactive learning platform](https://www.apollographql.com/tutorials/?utm_source=apollo_docs&utm_medium=referral).
```

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +> For an introduction to the entire Apollo platform, [check out **Odyssey**, Apollo's new learning platform](https://odyssey.apollographql.com?utm_source=apollo_docs&utm_medium=referral).
Might as well cut "new" at this point 😄

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +> If you are using a React sandbox and running into issues, try downgrading your `graphql` package. You can use `npm install graphql@15.8.0` to downgrade.
Is this specifically about an issue within Codesandbox, or can it also occur locally? We might need to make this more general if both

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +Before starting this tutorial, we recommend you either:
```suggestion
To start this tutorial, do one of the following:
```

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +We'll use the [FlyBy API](https://flyby-gateway.herokuapp.com/) from the [Voyage I: Federation from Day One](https://www.apollographql.com/tutorials/voyage-part1/) Odyssey course as our GraphQL serve
```suggestion
Our example application will use the [FlyBy GraphQL API](https://flyby-gateway.herokuapp.com/) from the [Voyage tutorial series](https://www.apollographql.com/tutorials/voyage-part1/) in Apollo Odyssey. This API provides a list of intergalactic travel locations and details about those locations 👽
```

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +In `index.js`, let's first import the things we need from `@apollo/client`:
```suggestion
In `index.js`, let's first import the symbols we need from `@apollo/client`:
```

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +More on the `uri` and `cache` fields below:
```suggestion
```

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +More on the `uri` and `cache` fields below:
Despite flying in the face of the style guide, I personally don't think this particular list requires an intro sentence because it's directly addressing the immediately preceding codeblock. But feel free to keep if you disagree!

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +  query getLocations {
```suggestion
  query GetLocations {
```

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +- Apollo Client tracks a query's error and loading states for you, reflected in the `loading` and `error` properties.
```suggestion
- Apollo Client automatically tracks a query's loading and error states, which are reflected in the `loading` and `error` properties.
```

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +- Apollo Client tracks a query's error and loading states for you, reflected in the `loading` and `error` properties.
Agree this sentence needed a tweak, realized we should probably list "loading" and "error" in the same order in both places

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +When your app reloads, you should briefly see a loading indicator, followed by a list of locations and details about those locations! If you don't, you can compare your code against the [completed ap
```suggestion
When your app reloads, you should briefly see a loading indicator, followed by a list of locations and details about those locations! If you don't, you can compare your code against the [completed app on CodeSandbox](https://codesandbox.io/s/get-started-apollo-client-demo-bert8s).
```

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +In `index.js`, let's first import the things we need from `@apollo/client`:
Avoid "things" wherever possible

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +We'll use the [FlyBy API](https://flyby-gateway.herokuapp.com/) from the [Voyage I: Federation from Day One](https://www.apollographql.com/tutorials/voyage-part1/) Odyssey course as our GraphQL serve
(alien emoji very optional 😄 )

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +      query getLocations {
```suggestion
      query GetLocations {
```

2022-06-24 20:51 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +      query getLocations {
PascalCase for operation names

2022-06-24 23:34 UTC, jpvajda approved these changes
This looks great from my perspective, thanks for improving this guide!

2022-06-28 19:21 UTC, StephenBarlow commented on docs/source/get-started.mdx
>  function App() {
In both my CRA app and the default codesandbox React template, `App` is pulled in from `App.js` as opposed to defined directly in `index.js`. I reckon we should conform to the same pattern here.

2022-06-28 19:21 UTC, StephenBarlow commented on docs/source/get-started.mdx
>  function App() {
In fact yes, let's do that and move all of the actual query logic and the component structure into `App.js`

2022-06-28 20:16 UTC, rkoron007 commented
As per our conversation @StephenBarlow, I updated this tutorial to directly use the `App.js` file instead of putting everything in `index.js`. I also updated the CodeSandbox to match!

2022-06-28 23:52 UTC, StephenBarlow approved these changes
Woo thanks for incorporating all these pesky changes! Just a last couple things and then merge whenever's good! 🎉

2022-06-28 23:52 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +```jsx title="index.js" {22-24}
```suggestion
```jsx title="index.js" {15-17}
```

2022-06-28 23:52 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +```jsx title="index.js" {22-24}
Highlighted lines got moved a bit

2022-06-28 23:52 UTC, StephenBarlow commented on docs/source/get-started.mdx
> +> If you are using a React sandbox from CodeSandbox and running into issues, try downgrading your `graphql` package. You can use `npm install graphql@15.8.0` to downgrade.
```suggestion
> If you're using a React sandbox from CodeSandbox and you encounter a `TypeError`, try downgrading the version of the `graphql` package to `15.8.0` in the Dependencies panel. If you encounter a _different_ error after downgrading, refresh the page.
```

2022-06-29 01:38 UTC, merged