Use reactive var hook
apollographql/apollo-client pull request #9906
Opened 2022-07-15 22:48 UTC by jpvajda

This PR attempts to better document the `useReactivevVar` hook introduced in #6867

2022-07-15 22:51 UTC, jpvajda commented
👋  [@alessbell](https://github.com/alessbell) [@MrDoomBringer](https://github.com/MrDoomBringer) [@hwillson](https://github.com/hwillson) [@benjamn](https://github.com/benjamn)

Here's an attempt to document this feature! Could someone provide a quick review?

2022-07-16 13:29 UTC, hwillson requested changes
Thanks @jpvajda! See my comments inline, but a few additional things:

1. I think we should move this new content down further on the page. The `useReactiveVar` hook is a nice feature, but it is additive to the reactive variable functionality of the Apollo Client core. For this reason, I think we should introduce people to reactive variables as a core library concept first, then introduce them to the hook. I think your content would fit well merged into the `Reacting` part of this page, replacing the `With the useReactiveVar hook ...` paragraph.

2. I think we should also document `useReactiveVar` alongside our other hooks, in the API section of the docs: https://www.apollographql.com/docs/react/api/react/hooks

Thanks again!

2022-07-16 13:29 UTC, hwillson commented on docs/source/local-state/reactive-variables.mdx
> +Implementing `useReactiveVar` required generalizing the `ReactiveVar<T>` API to allow arbitrary listeners (not just InMemoryCache objects) like so:
I think we should remove this line - very inside baseball.

2022-07-16 13:29 UTC, hwillson commented on docs/source/local-state/reactive-variables.mdx
> +```
This example doesn't show how to use `useReactiveVar`. It could be replaced with something that demonstrates building a React component that leverages `useReactiveVar` like:

```ts
import { makeVar, useReactiveVar } from "@apollo/client";
export const cartItemsVar = makeVar([]);

export function Cart() {
  const cartItems = useReactiveVar(cartItemsVar);
  // ...
```

2022-07-18 17:32 UTC, jpvajda commented on docs/source/local-state/reactive-variables.mdx
> +```
Fixed locally.

2022-07-18 18:53 UTC, jpvajda commented
@hwillson I added to the API hooks docs, though you may want to review the function signature I pulled that out definition out of this change [in the PR ](https://github.com/apollographql/apollo-client/pull/6867/files#diff-d18b4eb7cdd4643b2a8374ae5d066ae09ddb0d219965ac5744423e87432f3d5d)

2022-07-18 23:27 UTC, hwillson commented on docs/source/api/react/hooks.mdx
> +  return value;
Maybe just remove these lines to keep the function signature aligned with the other sections, so it becomes just:

```ts
function useReactiveVar<T>(rv: ReactiveVar<T>): T {}
```

2022-07-18 23:28 UTC, hwillson approved these changes
Awesome @jpvajda - just one more small thing then I think we're 👍. Thanks!

2022-07-19 14:39 UTC, alessbell approved these changes
Left a couple of stylistic nits that I'll let Stephen confirm/reject when he's back online, but overall found this very clear and easy to follow 😄

2022-07-19 14:39 UTC, alessbell commented on docs/source/api/react/hooks.mdx
> +Previously, the only way for a reactive variable to trigger a React component rerender was through the use of `useQuery`. Now you don't have to be using `useQuery` to benefit from the reactivity that
Nit: I propose we copy the React docs with respect to `re-render` (with hyphen) for consistency

```suggestion
Previously, the only way for a reactive variable to trigger a React component re-render was through the use of `useQuery`. Now you don't have to be using `useQuery` to benefit from the reactivity that `ReactiveVar<T>` provides.
```

2022-07-19 14:39 UTC, alessbell commented on docs/source/api/react/hooks.mdx
> +export const cartItemsVar = makeVar([]);
Nit: elsewhere we have a newline after the h3 subheading

```suggestion
### Example

```tsx
import { makeVar, useReactiveVar } from "@apollo/client";
export const cartItemsVar = makeVar([]);
```

2022-07-19 14:39 UTC, alessbell commented on docs/source/api/react/hooks.mdx
> +The `useReactiveVar` hook can be used to read from a reactive variable in a way that allows the React component to rerender if/when the variable is next updated.
Same suggestion about `re-render`

```suggestion
The `useReactiveVar` hook can be used to read from a reactive variable in a way that allows the React component to re-render if/when the variable is next updated.
```

2022-07-19 14:39 UTC, alessbell commented on docs/source/local-state/reactive-variables.mdx
> +Previously, the only way for a reactive variable to trigger a React component rerender was through the use of `useQuery`. Now you don't have to be using `useQuery` to benefit from the reactivity that
Same suggestion about `re-render`

```suggestion
The `useReactiveVar` hook can be used to read from a reactive variable in a way that allows the React component to re-render if/when the variable is next updated.

Previously, the only way for a reactive variable to trigger a React component re-render was through the use of `useQuery`. Now you don't have to be using `useQuery` to benefit from the reactivity that `ReactiveVar<T>` provides.
```

2022-07-19 14:39 UTC, alessbell commented on docs/source/local-state/reactive-variables.mdx
> +
Nit: not sure if the two empty lines at the bottom of this file were intentional additions

2022-07-19 21:00 UTC, jpvajda commented on docs/source/api/react/hooks.mdx
> +Previously, the only way for a reactive variable to trigger a React component rerender was through the use of `useQuery`. Now you don't have to be using `useQuery` to benefit from the reactivity that
Thanks, I'll make this change on my local branch and commit.

2022-07-19 22:24 UTC, jpvajda commented
This is failing a single test in CI, but passes on my local branch. 

```
Summary of all failing tests
 FAIL  link/batch/__tests__/batchLink.ts
  ● BatchLink › correctly follows batch interval

    expect(received).toBe(expected) // Object.is equality

    Expected: 2
    Received: 1

      622 |       // The batch shouldn't be fired yet, so we can add one more request.
      623 |       const sub3 = batcher.enqueueRequest({operation: operation3}).subscribe(() => reject('next should never be called'));
    > 624 |       expect(batcher["batchesByKey"].get('')!.size).toBe(2);
          |                                                     ^
      625 |
      626 |       sub3.unsubscribe();
      627 |       expect(batcher["batchesByKey"].get('')!.size).toBe(1);

      at link/batch/__tests__/batchLink.ts:624:53
      at Timeout.task [as _onTimeout] (../node_modules/jsdom/lib/jsdom/browser/Window.js:514:19)


Test Suites: 1 failed, 115 passed, 116 total
Tests:       1 failed, 15 skipped, 1769 passed, 1785 total
Snapshots:   135 passed, 135 total
Time:        83.38 s
Ran all test suites.
```
![Screen Shot 2022-07-19 at 4 23 06 PM](https://user-images.githubusercontent.com/1395158/179858627-e5ae0a2f-6eb1-4e6f-869b-b701c0c26988.png)

2022-07-19 22:45 UTC, jpvajda commented
re running the test in Circle CI got it to pass. 🤷

2022-07-19 22:45 UTC, merged