Quick doc change to clarify subscriptions don't work in client schema
apollographql/apollo-client pull request #9944
Opened 2022-07-26 19:10 UTC by MrDoomBringer

Adds explicit clarification that we don't support subscriptions polling the client state. See the long-open issue https://github.com/apollographql/apollo-client/issues/5322 for more information.

### Checklist:

- [x] If this PR is a new feature, please reference an issue where a consensus about the design was reached (not necessary for small changes)
- [x] Make sure all of the significant new logic is covered by tests

2022-07-27 01:01 UTC, hwillson requested changes
Thanks for this @MrDoomBringer! I'm wondering if we can expand the note a bit - see below.

2022-07-27 01:01 UTC, hwillson commented on docs/source/data/subscriptions.mdx
> +> **Note**: Subscriptions cannot be used to listen to client events.
Maybe we can add a few more details like:

```suggestion
> **Note**: Subscriptions cannot be used to listen to local client events, like subscribing to changes in the cache. Subscriptions are intended to be used to subscribe to external data changes, and have those received changes be stored in the cache. You can then leverage Apollo Client's observability model to watch for changes in the cache, using [`client.watchQuery`](../api/core/ApolloClient#ApolloClient.watchQuery) or [`useQuery`](../api/react/hooks#usequery).
```

2022-07-28 20:16 UTC, MrDoomBringer commented on docs/source/data/subscriptions.mdx
> +> **Note**: Subscriptions cannot be used to listen to client events.
This looks perfect to me!

2022-07-28 20:29 UTC, StephenBarlow approved these changes

2022-07-29 07:42 UTC, merged